SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE SYS_USER (
  USER_ID NUMBER(19) NOT NULL,
  USERNAME VARCHAR2(100) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  REAL_NAME VARCHAR2(100) NOT NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  INSTITUTION VARCHAR2(200),
  STATUS VARCHAR2(20) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_SYS_USER PRIMARY KEY (USER_ID),
  CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
  CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
  CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE SYS_ROLE (
  ROLE_ID NUMBER(19) NOT NULL,
  ROLE_CODE VARCHAR2(50) NOT NULL,
  ROLE_NAME VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_SYS_ROLE PRIMARY KEY (ROLE_ID),
  CONSTRAINT UK_SYS_ROLE_CODE UNIQUE (ROLE_CODE)
);

CREATE TABLE SYS_USER_ROLE (
  USER_ROLE_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  ROLE_ID NUMBER(19) NOT NULL,
  CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
  CONSTRAINT UK_SYS_USER_ROLE UNIQUE (USER_ID, ROLE_ID)
);

CREATE TABLE USER_RESEARCH_AREA (
  USER_RESEARCH_AREA_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  AREA_CODE VARCHAR2(50) NOT NULL,
  AREA_NAME VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_USER_RESEARCH_AREA PRIMARY KEY (USER_RESEARCH_AREA_ID),
  CONSTRAINT UK_USER_RESEARCH_AREA UNIQUE (USER_ID, AREA_CODE)
);

CREATE TABLE MANUSCRIPT (
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  SUBMITTER_ID NUMBER(19) NOT NULL,
  CURRENT_VERSION_ID NUMBER(19),
  CURRENT_STATUS VARCHAR2(40) NOT NULL,
  CURRENT_ROUND_NO NUMBER(10) DEFAULT 0 NOT NULL,
  BLIND_MODE VARCHAR2(30) NOT NULL,
  SUBMITTED_AT TIMESTAMP,
  LAST_DECISION_CODE VARCHAR2(40),
  CONSTRAINT PK_MANUSCRIPT PRIMARY KEY (MANUSCRIPT_ID),
  CONSTRAINT CK_MANUSCRIPT_STATUS CHECK (
    CURRENT_STATUS IN (
      'DRAFT',
      'SUBMITTED',
      'UNDER_SCREENING',
      'DESK_REJECTED',
      'UNDER_REVIEW',
      'REVISION_REQUIRED',
      'REVISED_SUBMITTED',
      'ACCEPTED',
      'REJECTED'
    )
  ),
  CONSTRAINT CK_MANUSCRIPT_BLIND_MODE CHECK (BLIND_MODE IN ('DOUBLE_BLIND', 'SINGLE_BLIND', 'OPEN')),
  CONSTRAINT CK_MANUSCRIPT_LAST_DECISION CHECK (
    LAST_DECISION_CODE IS NULL OR LAST_DECISION_CODE IN (
      'ACCEPT',
      'REJECT',
      'MINOR_REVISION',
      'MAJOR_REVISION',
      'DESK_REJECT'
    )
  )
);

CREATE TABLE MANUSCRIPT_VERSION (
  VERSION_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  VERSION_NO NUMBER(10) NOT NULL,
  VERSION_TYPE VARCHAR2(30) NOT NULL,
  TITLE VARCHAR2(500) NOT NULL,
  ABSTRACT CLOB,
  KEYWORDS VARCHAR2(500),
  PDF_FILE BLOB,
  PDF_FILE_NAME VARCHAR2(255),
  PDF_FILE_SIZE NUMBER(19),
  SUBMITTED_BY NUMBER(19) NOT NULL,
  SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  SOURCE_DECISION_ID NUMBER(19),
  CONSTRAINT PK_MANUSCRIPT_VERSION PRIMARY KEY (VERSION_ID),
  CONSTRAINT UK_MANUSCRIPT_VERSION UNIQUE (MANUSCRIPT_ID, VERSION_NO),
  CONSTRAINT CK_MANUSCRIPT_VERSION_TYPE CHECK (VERSION_TYPE IN ('INITIAL', 'REVISION', 'RESUBMISSION'))
);

CREATE TABLE MANUSCRIPT_AUTHOR (
  MANUSCRIPT_AUTHOR_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19),
  AUTHOR_NAME VARCHAR2(200) NOT NULL,
  EMAIL VARCHAR2(150),
  INSTITUTION VARCHAR2(200),
  AUTHOR_ORDER NUMBER(10) NOT NULL,
  IS_CORRESPONDING NUMBER(1) DEFAULT 0 NOT NULL,
  IS_EXTERNAL NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_MANUSCRIPT_AUTHOR PRIMARY KEY (MANUSCRIPT_AUTHOR_ID),
  CONSTRAINT UK_MANUSCRIPT_AUTHOR_ORDER UNIQUE (MANUSCRIPT_ID, VERSION_ID, AUTHOR_ORDER),
  CONSTRAINT CK_MANUSCRIPT_AUTHOR_CORR CHECK (IS_CORRESPONDING IN (0, 1)),
  CONSTRAINT CK_MANUSCRIPT_AUTHOR_EXTERNAL CHECK (IS_EXTERNAL IN (0, 1)),
  CONSTRAINT CK_MANUSCRIPT_AUTHOR_ORDER CHECK (AUTHOR_ORDER > 0)
);

CREATE TABLE REVIEW_ROUND (
  ROUND_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  ROUND_NO NUMBER(10) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  ROUND_STATUS VARCHAR2(20) NOT NULL,
  ASSIGNMENT_STRATEGY VARCHAR2(30) NOT NULL,
  SCREENING_REQUIRED NUMBER(1) DEFAULT 1 NOT NULL,
  DEADLINE_AT TIMESTAMP,
  CREATED_BY NUMBER(19) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_REVIEW_ROUND PRIMARY KEY (ROUND_ID),
  CONSTRAINT UK_REVIEW_ROUND UNIQUE (MANUSCRIPT_ID, ROUND_NO),
  CONSTRAINT CK_REVIEW_ROUND_STATUS CHECK (ROUND_STATUS IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT CK_REVIEW_ROUND_STRATEGY CHECK (ASSIGNMENT_STRATEGY IN ('REUSE_REVIEWERS', 'REALLOCATE_REVIEWERS')),
  CONSTRAINT CK_REVIEW_ROUND_SCREENING CHECK (SCREENING_REQUIRED IN (0, 1))
);

CREATE TABLE REVIEW_ASSIGNMENT (
  ASSIGNMENT_ID NUMBER(19) NOT NULL,
  ROUND_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  REVIEWER_ID NUMBER(19) NOT NULL,
  TASK_STATUS VARCHAR2(20) NOT NULL,
  ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ACCEPTED_AT TIMESTAMP,
  DECLINED_AT TIMESTAMP,
  DECLINE_REASON CLOB,
  DEADLINE_AT TIMESTAMP,
  SUBMITTED_AT TIMESTAMP,
  REASSIGNED_FROM_ID NUMBER(19),
  CONSTRAINT PK_REVIEW_ASSIGNMENT PRIMARY KEY (ASSIGNMENT_ID),
  CONSTRAINT UK_REVIEW_ASSIGNMENT UNIQUE (ROUND_ID, REVIEWER_ID),
  CONSTRAINT CK_REVIEW_ASSIGNMENT_STATUS CHECK (
    TASK_STATUS IN (
      'ASSIGNED',
      'ACCEPTED',
      'DECLINED',
      'IN_REVIEW',
      'SUBMITTED',
      'OVERDUE',
      'REASSIGNED',
      'CANCELLED'
    )
  )
);

CREATE TABLE CONFLICT_CHECK_RECORD (
  CONFLICT_ID NUMBER(19) NOT NULL,
  ASSIGNMENT_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  REVIEWER_ID NUMBER(19) NOT NULL,
  CONFLICT_TYPE VARCHAR2(50) NOT NULL,
  CONFLICT_DESC CLOB,
  SOURCE VARCHAR2(30) NOT NULL,
  DECLARED_BY NUMBER(19),
  DECLARED_AT TIMESTAMP,
  DETECTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONFIRMED_BY_CHAIR NUMBER(19),
  CONSTRAINT PK_CONFLICT_CHECK_RECORD PRIMARY KEY (CONFLICT_ID),
  CONSTRAINT CK_CONFLICT_CHECK_SOURCE CHECK (SOURCE IN ('SYSTEM_DETECTED', 'SELF_DECLARED'))
);

CREATE TABLE REVIEW_REPORT (
  REVIEW_ID NUMBER(19) NOT NULL,
  ASSIGNMENT_ID NUMBER(19) NOT NULL,
  ROUND_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  REVIEWER_ID NUMBER(19) NOT NULL,
  NOVELTY_SCORE NUMBER(2) NOT NULL,
  METHOD_SCORE NUMBER(2) NOT NULL,
  EXPERIMENT_SCORE NUMBER(2) NOT NULL,
  WRITING_SCORE NUMBER(2) NOT NULL,
  OVERALL_SCORE NUMBER(2) NOT NULL,
  CONFIDENCE_LEVEL VARCHAR2(10) NOT NULL,
  STRENGTHS CLOB,
  WEAKNESSES CLOB,
  COMMENTS_TO_AUTHOR CLOB,
  COMMENTS_TO_CHAIR CLOB,
  RECOMMENDATION VARCHAR2(40) NOT NULL,
  SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_REVIEW_REPORT PRIMARY KEY (REVIEW_ID),
  CONSTRAINT UK_REVIEW_REPORT_ASSIGNMENT UNIQUE (ASSIGNMENT_ID),
  CONSTRAINT CK_REVIEW_REPORT_SCORE_NOVELTY CHECK (NOVELTY_SCORE BETWEEN 1 AND 5),
  CONSTRAINT CK_REVIEW_REPORT_SCORE_METHOD CHECK (METHOD_SCORE BETWEEN 1 AND 5),
  CONSTRAINT CK_REVIEW_REPORT_SCORE_EXPERIMENT CHECK (EXPERIMENT_SCORE BETWEEN 1 AND 5),
  CONSTRAINT CK_REVIEW_REPORT_SCORE_WRITING CHECK (WRITING_SCORE BETWEEN 1 AND 5),
  CONSTRAINT CK_REVIEW_REPORT_SCORE_OVERALL CHECK (OVERALL_SCORE BETWEEN 1 AND 5),
  CONSTRAINT CK_REVIEW_REPORT_CONFIDENCE CHECK (CONFIDENCE_LEVEL IN ('HIGH', 'MEDIUM', 'LOW')),
  CONSTRAINT CK_REVIEW_REPORT_RECOMMENDATION CHECK (
    RECOMMENDATION IN (
      'ACCEPT',
      'REJECT',
      'MINOR_REVISION',
      'MAJOR_REVISION',
      'DESK_REJECT'
    )
  )
);

CREATE TABLE DECISION_RECORD (
  DECISION_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  ROUND_ID NUMBER(19) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  DECISION_CODE VARCHAR2(40) NOT NULL,
  DECISION_REASON CLOB,
  DECIDED_BY NUMBER(19) NOT NULL,
  DECIDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_DECISION_RECORD PRIMARY KEY (DECISION_ID),
  CONSTRAINT UK_DECISION_RECORD_ROUND UNIQUE (ROUND_ID),
  CONSTRAINT CK_DECISION_RECORD_CODE CHECK (
    DECISION_CODE IN ('ACCEPT', 'REJECT', 'MINOR_REVISION', 'MAJOR_REVISION', 'DESK_REJECT')
  )
);

CREATE TABLE AGENT_ANALYSIS_TASK (
  TASK_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  ROUND_ID NUMBER(19),
  TASK_TYPE VARCHAR2(40) NOT NULL,
  TASK_STATUS VARCHAR2(30) NOT NULL,
  REQUEST_PAYLOAD CLOB,
  RESULT_SUMMARY CLOB,
  EXTERNAL_TASK_ID VARCHAR2(100),
  RETRY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FINISHED_AT TIMESTAMP,
  CONSTRAINT PK_AGENT_ANALYSIS_TASK PRIMARY KEY (TASK_ID),
  CONSTRAINT UK_AGENT_ANALYSIS_TASK_EXT UNIQUE (EXTERNAL_TASK_ID),
  CONSTRAINT CK_AGENT_ANALYSIS_TASK_TYPE CHECK (
    TASK_TYPE IN ('SCREENING_ANALYSIS', 'REVIEW_ASSIST_ANALYSIS', 'DECISION_CONFLICT_ANALYSIS')
  ),
  CONSTRAINT CK_AGENT_ANALYSIS_TASK_STATUS CHECK (
    TASK_STATUS IN ('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED')
  ),
  CONSTRAINT CK_AGENT_ANALYSIS_TASK_RETRY CHECK (RETRY_COUNT >= 0)
);

CREATE TABLE AGENT_ANALYSIS_RESULT (
  RESULT_ID NUMBER(19) NOT NULL,
  TASK_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  RESULT_TYPE VARCHAR2(60) NOT NULL,
  RAW_RESULT_JSON CLOB,
  REDACTED_RESULT_JSON CLOB,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_AGENT_ANALYSIS_RESULT PRIMARY KEY (RESULT_ID),
  CONSTRAINT UK_AGENT_ANALYSIS_RESULT_TASK UNIQUE (TASK_ID)
);

CREATE TABLE AGENT_FEEDBACK (
  FEEDBACK_ID NUMBER(19) NOT NULL,
  TASK_ID NUMBER(19) NOT NULL,
  RESULT_TYPE VARCHAR2(60) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  RATING NUMBER(1) NOT NULL,
  FEEDBACK_COMMENT CLOB,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_AGENT_FEEDBACK PRIMARY KEY (FEEDBACK_ID),
  CONSTRAINT CK_AGENT_FEEDBACK_RATING CHECK (RATING BETWEEN 1 AND 5)
);

CREATE TABLE SYS_NOTIFICATION (
  NOTIFICATION_ID NUMBER(19) NOT NULL,
  RECEIVER_ID NUMBER(19) NOT NULL,
  BIZ_TYPE VARCHAR2(50) NOT NULL,
  BIZ_ID NUMBER(19) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB,
  IS_READ NUMBER(1) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_SYS_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
  CONSTRAINT CK_SYS_NOTIFICATION_IS_READ CHECK (IS_READ IN (0, 1))
);

CREATE TABLE AUDIT_LOG (
  LOG_ID NUMBER(19) NOT NULL,
  OPERATOR_ID NUMBER(19),
  OPERATION_TYPE VARCHAR2(50) NOT NULL,
  BIZ_TYPE VARCHAR2(50) NOT NULL,
  BIZ_ID NUMBER(19),
  DETAIL_JSON CLOB,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);

CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SYS_ROLE START WITH 5 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SYS_USER_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER_RESEARCH_AREA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MANUSCRIPT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MANUSCRIPT_VERSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MANUSCRIPT_AUTHOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW_ROUND START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW_ASSIGNMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONFLICT_CHECK_RECORD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEW_REPORT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DECISION_RECORD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AGENT_ANALYSIS_TASK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AGENT_ANALYSIS_RESULT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AGENT_FEEDBACK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SYS_NOTIFICATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDIT_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE SYS_USER_ROLE
  ADD CONSTRAINT FK_SYS_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE SYS_USER_ROLE
  ADD CONSTRAINT FK_SYS_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID);

ALTER TABLE USER_RESEARCH_AREA
  ADD CONSTRAINT FK_USER_RESEARCH_AREA_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE MANUSCRIPT
  ADD CONSTRAINT FK_MANUSCRIPT_SUBMITTER FOREIGN KEY (SUBMITTER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE MANUSCRIPT_VERSION
  ADD CONSTRAINT FK_MANUSCRIPT_VERSION_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE MANUSCRIPT_VERSION
  ADD CONSTRAINT FK_MANUSCRIPT_VERSION_SUBMITTED_BY FOREIGN KEY (SUBMITTED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE MANUSCRIPT_AUTHOR
  ADD CONSTRAINT FK_MANUSCRIPT_AUTHOR_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE MANUSCRIPT_AUTHOR
  ADD CONSTRAINT FK_MANUSCRIPT_AUTHOR_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE MANUSCRIPT_AUTHOR
  ADD CONSTRAINT FK_MANUSCRIPT_AUTHOR_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE REVIEW_ROUND
  ADD CONSTRAINT FK_REVIEW_ROUND_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE REVIEW_ROUND
  ADD CONSTRAINT FK_REVIEW_ROUND_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE REVIEW_ROUND
  ADD CONSTRAINT FK_REVIEW_ROUND_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE REVIEW_ASSIGNMENT
  ADD CONSTRAINT FK_REVIEW_ASSIGNMENT_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID);

ALTER TABLE REVIEW_ASSIGNMENT
  ADD CONSTRAINT FK_REVIEW_ASSIGNMENT_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE REVIEW_ASSIGNMENT
  ADD CONSTRAINT FK_REVIEW_ASSIGNMENT_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE REVIEW_ASSIGNMENT
  ADD CONSTRAINT FK_REVIEW_ASSIGNMENT_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE REVIEW_ASSIGNMENT
  ADD CONSTRAINT FK_REVIEW_ASSIGNMENT_REASSIGNED_FROM FOREIGN KEY (REASSIGNED_FROM_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID);

ALTER TABLE CONFLICT_CHECK_RECORD
  ADD CONSTRAINT FK_CONFLICT_CHECK_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID);

ALTER TABLE CONFLICT_CHECK_RECORD
  ADD CONSTRAINT FK_CONFLICT_CHECK_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE CONFLICT_CHECK_RECORD
  ADD CONSTRAINT FK_CONFLICT_CHECK_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE CONFLICT_CHECK_RECORD
  ADD CONSTRAINT FK_CONFLICT_CHECK_DECLARED_BY FOREIGN KEY (DECLARED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE CONFLICT_CHECK_RECORD
  ADD CONSTRAINT FK_CONFLICT_CHECK_CONFIRMED_BY FOREIGN KEY (CONFIRMED_BY_CHAIR) REFERENCES SYS_USER (USER_ID);

ALTER TABLE REVIEW_REPORT
  ADD CONSTRAINT FK_REVIEW_REPORT_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID);

ALTER TABLE REVIEW_REPORT
  ADD CONSTRAINT FK_REVIEW_REPORT_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID);

ALTER TABLE REVIEW_REPORT
  ADD CONSTRAINT FK_REVIEW_REPORT_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE REVIEW_REPORT
  ADD CONSTRAINT FK_REVIEW_REPORT_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE DECISION_RECORD
  ADD CONSTRAINT FK_DECISION_RECORD_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE DECISION_RECORD
  ADD CONSTRAINT FK_DECISION_RECORD_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID);

ALTER TABLE DECISION_RECORD
  ADD CONSTRAINT FK_DECISION_RECORD_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE DECISION_RECORD
  ADD CONSTRAINT FK_DECISION_RECORD_DECIDED_BY FOREIGN KEY (DECIDED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE AGENT_ANALYSIS_TASK
  ADD CONSTRAINT FK_AGENT_ANALYSIS_TASK_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE AGENT_ANALYSIS_TASK
  ADD CONSTRAINT FK_AGENT_ANALYSIS_TASK_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE AGENT_ANALYSIS_TASK
  ADD CONSTRAINT FK_AGENT_ANALYSIS_TASK_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID);

ALTER TABLE AGENT_ANALYSIS_RESULT
  ADD CONSTRAINT FK_AGENT_ANALYSIS_RESULT_TASK FOREIGN KEY (TASK_ID) REFERENCES AGENT_ANALYSIS_TASK (TASK_ID);

ALTER TABLE AGENT_ANALYSIS_RESULT
  ADD CONSTRAINT FK_AGENT_ANALYSIS_RESULT_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE AGENT_ANALYSIS_RESULT
  ADD CONSTRAINT FK_AGENT_ANALYSIS_RESULT_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE AGENT_FEEDBACK
  ADD CONSTRAINT FK_AGENT_FEEDBACK_TASK FOREIGN KEY (TASK_ID) REFERENCES AGENT_ANALYSIS_TASK (TASK_ID);

ALTER TABLE AGENT_FEEDBACK
  ADD CONSTRAINT FK_AGENT_FEEDBACK_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE SYS_NOTIFICATION
  ADD CONSTRAINT FK_SYS_NOTIFICATION_RECEIVER FOREIGN KEY (RECEIVER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE AUDIT_LOG
  ADD CONSTRAINT FK_AUDIT_LOG_OPERATOR FOREIGN KEY (OPERATOR_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE MANUSCRIPT
  ADD CONSTRAINT FK_MANUSCRIPT_CURRENT_VERSION FOREIGN KEY (CURRENT_VERSION_ID)
  REFERENCES MANUSCRIPT_VERSION (VERSION_ID)
  DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE MANUSCRIPT_VERSION
  ADD CONSTRAINT FK_MANUSCRIPT_VERSION_SOURCE_DECISION FOREIGN KEY (SOURCE_DECISION_ID)
  REFERENCES DECISION_RECORD (DECISION_ID)
  DEFERRABLE INITIALLY DEFERRED;
