SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

INSERT INTO SYS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (1, 'AUTHOR', 'Author');
INSERT INTO SYS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (2, 'REVIEWER', 'Reviewer');
INSERT INTO SYS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (3, 'CHAIR', 'Chair');
INSERT INTO SYS_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME) VALUES (4, 'ADMIN', 'Admin');

COMMIT;

