SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE OR REPLACE PROCEDURE PRC_REVIEW_COMPLETION_STATS (
  P_MANUSCRIPT_ID IN NUMBER,
  P_TOTAL_ASSIGNMENTS OUT NUMBER,
  P_SUBMITTED_REPORTS OUT NUMBER,
  P_COMPLETION_RATE OUT NUMBER
) AS
BEGIN
  SELECT COUNT(*),
         NVL(SUM(CASE WHEN TASK_STATUS = 'SUBMITTED' THEN 1 ELSE 0 END), 0)
    INTO P_TOTAL_ASSIGNMENTS,
         P_SUBMITTED_REPORTS
    FROM REVIEW_ASSIGNMENT
   WHERE MANUSCRIPT_ID = P_MANUSCRIPT_ID;

  IF P_TOTAL_ASSIGNMENTS = 0 THEN
    P_COMPLETION_RATE := 0;
  ELSE
    P_COMPLETION_RATE := ROUND(P_SUBMITTED_REPORTS / P_TOTAL_ASSIGNMENTS, 4);
  END IF;
END;
/

CREATE OR REPLACE PROCEDURE PRC_REVIEW_WORKLOAD_SUMMARY (
  P_REVIEWER_ID IN NUMBER,
  P_WORKLOAD_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_WORKLOAD_CURSOR FOR
    SELECT TASK_STATUS, COUNT(*) AS TASK_COUNT
      FROM REVIEW_ASSIGNMENT
     WHERE REVIEWER_ID = P_REVIEWER_ID
     GROUP BY TASK_STATUS
     ORDER BY TASK_STATUS;
END;
/

CREATE OR REPLACE PROCEDURE PRC_AGENT_TASK_STATUS_SUMMARY (
  P_MANUSCRIPT_ID IN NUMBER,
  P_STATUS_CURSOR OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_STATUS_CURSOR FOR
    SELECT TASK_TYPE, TASK_STATUS, COUNT(*) AS TASK_COUNT
      FROM AGENT_ANALYSIS_TASK
     WHERE MANUSCRIPT_ID = P_MANUSCRIPT_ID
     GROUP BY TASK_TYPE, TASK_STATUS
     ORDER BY TASK_TYPE, TASK_STATUS;
END;
/
