SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE OR REPLACE TRIGGER TRG_SYS_USER_BI
BEFORE INSERT ON SYS_USER
FOR EACH ROW
BEGIN
  IF :NEW.USER_ID IS NULL THEN
    :NEW.USER_ID := SEQ_SYS_USER.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SYS_ROLE_BI
BEFORE INSERT ON SYS_ROLE
FOR EACH ROW
BEGIN
  IF :NEW.ROLE_ID IS NULL THEN
    :NEW.ROLE_ID := SEQ_SYS_ROLE.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SYS_USER_ROLE_BI
BEFORE INSERT ON SYS_USER_ROLE
FOR EACH ROW
BEGIN
  IF :NEW.USER_ROLE_ID IS NULL THEN
    :NEW.USER_ROLE_ID := SEQ_SYS_USER_ROLE.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_USER_RESEARCH_AREA_BI
BEFORE INSERT ON USER_RESEARCH_AREA
FOR EACH ROW
BEGIN
  IF :NEW.USER_RESEARCH_AREA_ID IS NULL THEN
    :NEW.USER_RESEARCH_AREA_ID := SEQ_USER_RESEARCH_AREA.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MANUSCRIPT_BI
BEFORE INSERT ON MANUSCRIPT
FOR EACH ROW
BEGIN
  IF :NEW.MANUSCRIPT_ID IS NULL THEN
    :NEW.MANUSCRIPT_ID := SEQ_MANUSCRIPT.NEXTVAL;
  END IF;
  IF :NEW.CURRENT_ROUND_NO IS NULL THEN
    :NEW.CURRENT_ROUND_NO := 0;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MANUSCRIPT_VERSION_BI
BEFORE INSERT ON MANUSCRIPT_VERSION
FOR EACH ROW
BEGIN
  IF :NEW.VERSION_ID IS NULL THEN
    :NEW.VERSION_ID := SEQ_MANUSCRIPT_VERSION.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MANUSCRIPT_AUTHOR_BI
BEFORE INSERT ON MANUSCRIPT_AUTHOR
FOR EACH ROW
BEGIN
  IF :NEW.MANUSCRIPT_AUTHOR_ID IS NULL THEN
    :NEW.MANUSCRIPT_AUTHOR_ID := SEQ_MANUSCRIPT_AUTHOR.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_ROUND_BI
BEFORE INSERT ON REVIEW_ROUND
FOR EACH ROW
BEGIN
  IF :NEW.ROUND_ID IS NULL THEN
    :NEW.ROUND_ID := SEQ_REVIEW_ROUND.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_ASSIGNMENT_BI
BEFORE INSERT ON REVIEW_ASSIGNMENT
FOR EACH ROW
BEGIN
  IF :NEW.ASSIGNMENT_ID IS NULL THEN
    :NEW.ASSIGNMENT_ID := SEQ_REVIEW_ASSIGNMENT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONFLICT_CHECK_RECORD_BI
BEFORE INSERT ON CONFLICT_CHECK_RECORD
FOR EACH ROW
BEGIN
  IF :NEW.CONFLICT_ID IS NULL THEN
    :NEW.CONFLICT_ID := SEQ_CONFLICT_CHECK_RECORD.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_REPORT_BI
BEFORE INSERT ON REVIEW_REPORT
FOR EACH ROW
BEGIN
  IF :NEW.REVIEW_ID IS NULL THEN
    :NEW.REVIEW_ID := SEQ_REVIEW_REPORT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DECISION_RECORD_BI
BEFORE INSERT ON DECISION_RECORD
FOR EACH ROW
BEGIN
  IF :NEW.DECISION_ID IS NULL THEN
    :NEW.DECISION_ID := SEQ_DECISION_RECORD.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AGENT_ANALYSIS_TASK_BI
BEFORE INSERT ON AGENT_ANALYSIS_TASK
FOR EACH ROW
BEGIN
  IF :NEW.TASK_ID IS NULL THEN
    :NEW.TASK_ID := SEQ_AGENT_ANALYSIS_TASK.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AGENT_ANALYSIS_RESULT_BI
BEFORE INSERT ON AGENT_ANALYSIS_RESULT
FOR EACH ROW
BEGIN
  IF :NEW.RESULT_ID IS NULL THEN
    :NEW.RESULT_ID := SEQ_AGENT_ANALYSIS_RESULT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AGENT_FEEDBACK_BI
BEFORE INSERT ON AGENT_FEEDBACK
FOR EACH ROW
BEGIN
  IF :NEW.FEEDBACK_ID IS NULL THEN
    :NEW.FEEDBACK_ID := SEQ_AGENT_FEEDBACK.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SYS_NOTIFICATION_BI
BEFORE INSERT ON SYS_NOTIFICATION
FOR EACH ROW
BEGIN
  IF :NEW.NOTIFICATION_ID IS NULL THEN
    :NEW.NOTIFICATION_ID := SEQ_SYS_NOTIFICATION.NEXTVAL;
  END IF;
  IF :NEW.IS_READ IS NULL THEN
    :NEW.IS_READ := 0;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDIT_LOG_BIU
BEFORE INSERT OR UPDATE ON AUDIT_LOG
FOR EACH ROW
BEGIN
  IF :NEW.LOG_ID IS NULL THEN
    :NEW.LOG_ID := SEQ_AUDIT_LOG.NEXTVAL;
  END IF;
  IF INSERTING OR UPDATING THEN
    :NEW.CREATED_AT := NVL(:NEW.CREATED_AT, CURRENT_TIMESTAMP);
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_MANUSCRIPT_AUDIT_TRACE_AU
AFTER UPDATE ON MANUSCRIPT
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_LOG (
    LOG_ID,
    OPERATION_TYPE,
    BIZ_TYPE,
    BIZ_ID,
    DETAIL_JSON,
    CREATED_AT
  ) VALUES (
    NULL,
    'MANUSCRIPT_UPDATE',
    'MANUSCRIPT',
    :NEW.MANUSCRIPT_ID,
    JSON_OBJECT(
      'oldStatus' VALUE :OLD.CURRENT_STATUS,
      'newStatus' VALUE :NEW.CURRENT_STATUS,
      'oldRound' VALUE :OLD.CURRENT_ROUND_NO,
      'newRound' VALUE :NEW.CURRENT_ROUND_NO
      RETURNING CLOB
    ),
    CURRENT_TIMESTAMP
  );
END;
/
