SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- Hashes generated with BCrypt cost=10 for password "demo123".

MERGE INTO SYS_USER U
USING (
  SELECT 1001 AS USER_ID, 'author_demo' AS USERNAME, '$2a$10$Al2Fi5T2ZEwE2Yi2ds6gp.7qKpiXar4e9.VBDPgU.8XtAfoe7UUDq' AS PASSWORD_HASH, 'Author Demo' AS REAL_NAME, 'author_demo@example.com' AS EMAIL, 'Southeast University' AS INSTITUTION, 'ACTIVE' AS STATUS FROM DUAL
  UNION ALL
  SELECT 1002, 'reviewer_demo', '$2a$10$Al2Fi5T2ZEwE2Yi2ds6gp.7qKpiXar4e9.VBDPgU.8XtAfoe7UUDq', 'Reviewer Demo', 'reviewer_demo@example.com', 'Nanjing University', 'ACTIVE' FROM DUAL
  UNION ALL
  SELECT 1003, 'chair_demo', '$2a$10$Al2Fi5T2ZEwE2Yi2ds6gp.7qKpiXar4e9.VBDPgU.8XtAfoe7UUDq', 'Chair Demo', 'chair_demo@example.com', 'Fudan University', 'ACTIVE' FROM DUAL
  UNION ALL
  SELECT 1004, 'admin_demo', '$2a$10$Al2Fi5T2ZEwE2Yi2ds6gp.7qKpiXar4e9.VBDPgU.8XtAfoe7UUDq', 'Admin Demo', 'admin_demo@example.com', 'Platform Ops', 'ACTIVE' FROM DUAL
  UNION ALL
  SELECT 1005, 'disabled_demo', '$2a$10$Al2Fi5T2ZEwE2Yi2ds6gp.7qKpiXar4e9.VBDPgU.8XtAfoe7UUDq', 'Disabled Demo', 'disabled_demo@example.com', 'Legacy Account', 'DISABLED' FROM DUAL
) S
ON (U.USERNAME = S.USERNAME)
WHEN MATCHED THEN
  UPDATE SET
    U.PASSWORD_HASH = S.PASSWORD_HASH,
    U.REAL_NAME = S.REAL_NAME,
    U.EMAIL = S.EMAIL,
    U.INSTITUTION = S.INSTITUTION,
    U.STATUS = S.STATUS
WHEN NOT MATCHED THEN
  INSERT (USER_ID, USERNAME, PASSWORD_HASH, REAL_NAME, EMAIL, INSTITUTION, STATUS, CREATED_AT)
  VALUES (S.USER_ID, S.USERNAME, S.PASSWORD_HASH, S.REAL_NAME, S.EMAIL, S.INSTITUTION, S.STATUS, CURRENT_TIMESTAMP);

MERGE INTO SYS_USER_ROLE UR
USING (
  SELECT 1101 AS USER_ROLE_ID, 1001 AS USER_ID, 1 AS ROLE_ID FROM DUAL
  UNION ALL
  SELECT 1102, 1002, 2 FROM DUAL
  UNION ALL
  SELECT 1103, 1003, 3 FROM DUAL
  UNION ALL
  SELECT 1104, 1004, 4 FROM DUAL
  UNION ALL
  SELECT 1105, 1005, 1 FROM DUAL
) S
ON (UR.USER_ID = S.USER_ID AND UR.ROLE_ID = S.ROLE_ID)
WHEN NOT MATCHED THEN
  INSERT (USER_ROLE_ID, USER_ID, ROLE_ID)
  VALUES (S.USER_ROLE_ID, S.USER_ID, S.ROLE_ID);

MERGE INTO USER_RESEARCH_AREA A
USING (
  SELECT 1201 AS USER_RESEARCH_AREA_ID, 1002 AS USER_ID, 'NLP' AS AREA_CODE, 'Natural Language Processing' AS AREA_NAME FROM DUAL
) S
ON (A.USER_ID = S.USER_ID AND A.AREA_CODE = S.AREA_CODE)
WHEN MATCHED THEN
  UPDATE SET
    A.AREA_NAME = S.AREA_NAME
WHEN NOT MATCHED THEN
  INSERT (USER_RESEARCH_AREA_ID, USER_ID, AREA_CODE, AREA_NAME)
  VALUES (S.USER_RESEARCH_AREA_ID, S.USER_ID, S.AREA_CODE, S.AREA_NAME);

COMMIT;
