SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

-- Idempotent demo workflow data for Task 12 verification and classroom demos.
-- The fixed IDs intentionally sit far above sequence-generated test data.

MERGE INTO SYS_USER U
USING (
  SELECT 1012 AS USER_ID,
         'conflicted_reviewer_demo' AS USERNAME,
         '$2a$10$Al2Fi5T2ZEwE2Yi2ds6gp.7qKpiXar4e9.VBDPgU.8XtAfoe7UUDq' AS PASSWORD_HASH,
         'Conflict Reviewer Demo' AS REAL_NAME,
         'conflicted_reviewer_demo@example.com' AS EMAIL,
         'Zhejiang University' AS INSTITUTION,
         'ACTIVE' AS STATUS
  FROM DUAL
) S
ON (U.USERNAME = S.USERNAME)
WHEN MATCHED THEN
  UPDATE SET
    U.PASSWORD_HASH = S.PASSWORD_HASH,
    U.REAL_NAME = S.REAL_NAME,
    U.EMAIL = S.EMAIL,
    U.INSTITUTION = S.INSTITUTION,
    U.STATUS = S.STATUS
WHEN NOT MATCHED THEN
  INSERT (USER_ID, USERNAME, PASSWORD_HASH, REAL_NAME, EMAIL, INSTITUTION, STATUS, CREATED_AT)
  VALUES (S.USER_ID, S.USERNAME, S.PASSWORD_HASH, S.REAL_NAME, S.EMAIL, S.INSTITUTION, S.STATUS, CURRENT_TIMESTAMP);

MERGE INTO SYS_USER_ROLE UR
USING (
  SELECT 1112 AS USER_ROLE_ID, 1012 AS USER_ID, 2 AS ROLE_ID FROM DUAL
) S
ON (UR.USER_ID = S.USER_ID AND UR.ROLE_ID = S.ROLE_ID)
WHEN NOT MATCHED THEN
  INSERT (USER_ROLE_ID, USER_ID, ROLE_ID)
  VALUES (S.USER_ROLE_ID, S.USER_ID, S.ROLE_ID);

MERGE INTO USER_RESEARCH_AREA A
USING (
  SELECT 1212 AS USER_RESEARCH_AREA_ID, 1012 AS USER_ID, 'ML_SYS' AS AREA_CODE, 'Machine Learning Systems' AS AREA_NAME FROM DUAL
) S
ON (A.USER_ID = S.USER_ID AND A.AREA_CODE = S.AREA_CODE)
WHEN MATCHED THEN
  UPDATE SET
    A.AREA_NAME = S.AREA_NAME
WHEN NOT MATCHED THEN
  INSERT (USER_RESEARCH_AREA_ID, USER_ID, AREA_CODE, AREA_NAME)
  VALUES (S.USER_RESEARCH_AREA_ID, S.USER_ID, S.AREA_CODE, S.AREA_NAME);

MERGE INTO MANUSCRIPT M
USING (
  SELECT 9001 AS MANUSCRIPT_ID,
         1001 AS SUBMITTER_ID,
         'SUBMITTED' AS CURRENT_STATUS,
         0 AS CURRENT_ROUND_NO,
         'DOUBLE_BLIND' AS BLIND_MODE
  FROM DUAL
) S
ON (M.MANUSCRIPT_ID = S.MANUSCRIPT_ID)
WHEN MATCHED THEN
  UPDATE SET
    M.SUBMITTER_ID = S.SUBMITTER_ID,
    M.CURRENT_STATUS = S.CURRENT_STATUS,
    M.CURRENT_ROUND_NO = S.CURRENT_ROUND_NO,
    M.BLIND_MODE = S.BLIND_MODE,
    M.SUBMITTED_AT = CURRENT_TIMESTAMP,
    M.LAST_DECISION_CODE = NULL
WHEN NOT MATCHED THEN
  INSERT (MANUSCRIPT_ID, SUBMITTER_ID, CURRENT_VERSION_ID, CURRENT_STATUS, CURRENT_ROUND_NO, BLIND_MODE, SUBMITTED_AT, LAST_DECISION_CODE)
  VALUES (S.MANUSCRIPT_ID, S.SUBMITTER_ID, NULL, S.CURRENT_STATUS, S.CURRENT_ROUND_NO, S.BLIND_MODE, CURRENT_TIMESTAMP, NULL);

MERGE INTO MANUSCRIPT_VERSION V
USING (
  SELECT 9001 AS VERSION_ID,
         9001 AS MANUSCRIPT_ID,
         1 AS VERSION_NO,
         'INITIAL' AS VERSION_TYPE,
         'Human-in-the-Loop Agent Support for Double-Blind Paper Review' AS TITLE,
         'This demo manuscript studies how an agent-assisted review system can summarize manuscripts, redact author-sensitive signals, and surface review conflicts while preserving chair oversight.' AS ABSTRACT,
         'agent assistance,double blind review,workflow automation' AS KEYWORDS,
         UTL_RAW.CAST_TO_RAW(q'~%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length 176 >>
stream
BT
/F1 12 Tf
72 720 Td
(Human in the loop agent support for double blind paper review.) Tj
0 -18 Td
(The method extracts paper sections and highlights conflicts for chairs.) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000242 00000 n 
0000000312 00000 n 
trailer
<< /Root 1 0 R /Size 6 >>
startxref
539
%%EOF
~') AS PDF_FILE,
         LENGTHB(q'~%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>
endobj
4 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
5 0 obj
<< /Length 176 >>
stream
BT
/F1 12 Tf
72 720 Td
(Human in the loop agent support for double blind paper review.) Tj
0 -18 Td
(The method extracts paper sections and highlights conflicts for chairs.) Tj
ET
endstream
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000242 00000 n 
0000000312 00000 n 
trailer
<< /Root 1 0 R /Size 6 >>
startxref
539
%%EOF
~') AS PDF_FILE_SIZE,
         'task12-demo-paper.pdf' AS PDF_FILE_NAME,
         1001 AS SUBMITTED_BY
  FROM DUAL
) S
ON (V.VERSION_ID = S.VERSION_ID)
WHEN MATCHED THEN
  UPDATE SET
    V.MANUSCRIPT_ID = S.MANUSCRIPT_ID,
    V.VERSION_NO = S.VERSION_NO,
    V.VERSION_TYPE = S.VERSION_TYPE,
    V.TITLE = S.TITLE,
    V.ABSTRACT = S.ABSTRACT,
    V.KEYWORDS = S.KEYWORDS,
    V.PDF_FILE = S.PDF_FILE,
    V.PDF_FILE_NAME = S.PDF_FILE_NAME,
    V.PDF_FILE_SIZE = S.PDF_FILE_SIZE,
    V.SUBMITTED_BY = S.SUBMITTED_BY,
    V.SUBMITTED_AT = CURRENT_TIMESTAMP,
    V.SOURCE_DECISION_ID = NULL
WHEN NOT MATCHED THEN
  INSERT (VERSION_ID, MANUSCRIPT_ID, VERSION_NO, VERSION_TYPE, TITLE, ABSTRACT, KEYWORDS, PDF_FILE, PDF_FILE_NAME, PDF_FILE_SIZE, SUBMITTED_BY, SUBMITTED_AT, SOURCE_DECISION_ID)
  VALUES (S.VERSION_ID, S.MANUSCRIPT_ID, S.VERSION_NO, S.VERSION_TYPE, S.TITLE, S.ABSTRACT, S.KEYWORDS, S.PDF_FILE, S.PDF_FILE_NAME, S.PDF_FILE_SIZE, S.SUBMITTED_BY, CURRENT_TIMESTAMP, NULL);

UPDATE MANUSCRIPT
SET CURRENT_VERSION_ID = 9001
WHERE MANUSCRIPT_ID = 9001;

MERGE INTO MANUSCRIPT_AUTHOR A
USING (
  SELECT 9001 AS MANUSCRIPT_AUTHOR_ID,
         9001 AS MANUSCRIPT_ID,
         9001 AS VERSION_ID,
         1001 AS USER_ID,
         'Author Demo' AS AUTHOR_NAME,
         'author_demo@example.com' AS EMAIL,
         'Southeast University' AS INSTITUTION,
         1 AS AUTHOR_ORDER,
         1 AS IS_CORRESPONDING,
         0 AS IS_EXTERNAL
  FROM DUAL
  UNION ALL
  SELECT 9002, 9001, 9001, NULL, 'External Collaborator', 'external@example.com', 'Demo Institute', 2, 0, 1 FROM DUAL
) S
ON (A.MANUSCRIPT_ID = S.MANUSCRIPT_ID AND A.VERSION_ID = S.VERSION_ID AND A.AUTHOR_ORDER = S.AUTHOR_ORDER)
WHEN MATCHED THEN
  UPDATE SET
    A.USER_ID = S.USER_ID,
    A.AUTHOR_NAME = S.AUTHOR_NAME,
    A.EMAIL = S.EMAIL,
    A.INSTITUTION = S.INSTITUTION,
    A.IS_CORRESPONDING = S.IS_CORRESPONDING,
    A.IS_EXTERNAL = S.IS_EXTERNAL
WHEN NOT MATCHED THEN
  INSERT (MANUSCRIPT_AUTHOR_ID, MANUSCRIPT_ID, VERSION_ID, USER_ID, AUTHOR_NAME, EMAIL, INSTITUTION, AUTHOR_ORDER, IS_CORRESPONDING, IS_EXTERNAL)
  VALUES (S.MANUSCRIPT_AUTHOR_ID, S.MANUSCRIPT_ID, S.VERSION_ID, S.USER_ID, S.AUTHOR_NAME, S.EMAIL, S.INSTITUTION, S.AUTHOR_ORDER, S.IS_CORRESPONDING, S.IS_EXTERNAL);

MERGE INTO AGENT_ANALYSIS_TASK T
USING (
  SELECT 9001 AS TASK_ID,
         9001 AS MANUSCRIPT_ID,
         9001 AS VERSION_ID,
         CAST(NULL AS NUMBER(19)) AS ROUND_ID,
         'SCREENING_ANALYSIS' AS TASK_TYPE,
         'SUCCESS' AS TASK_STATUS,
         '{"source":"demo-seed","title":"Human-in-the-Loop Agent Support for Double-Blind Paper Review"}' AS REQUEST_PAYLOAD,
         'Demo screening analysis is ready for the admin monitor.' AS RESULT_SUMMARY,
         'demo-screening-analysis-9001' AS EXTERNAL_TASK_ID,
         0 AS RETRY_COUNT
  FROM DUAL
) S
ON (T.TASK_ID = S.TASK_ID)
WHEN MATCHED THEN
  UPDATE SET
    T.MANUSCRIPT_ID = S.MANUSCRIPT_ID,
    T.VERSION_ID = S.VERSION_ID,
    T.ROUND_ID = S.ROUND_ID,
    T.TASK_TYPE = S.TASK_TYPE,
    T.TASK_STATUS = S.TASK_STATUS,
    T.REQUEST_PAYLOAD = S.REQUEST_PAYLOAD,
    T.RESULT_SUMMARY = S.RESULT_SUMMARY,
    T.EXTERNAL_TASK_ID = S.EXTERNAL_TASK_ID,
    T.RETRY_COUNT = S.RETRY_COUNT,
    T.FINISHED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (TASK_ID, MANUSCRIPT_ID, VERSION_ID, ROUND_ID, TASK_TYPE, TASK_STATUS, REQUEST_PAYLOAD, RESULT_SUMMARY, EXTERNAL_TASK_ID, RETRY_COUNT, CREATED_AT, FINISHED_AT)
  VALUES (S.TASK_ID, S.MANUSCRIPT_ID, S.VERSION_ID, S.ROUND_ID, S.TASK_TYPE, S.TASK_STATUS, S.REQUEST_PAYLOAD, S.RESULT_SUMMARY, S.EXTERNAL_TASK_ID, S.RETRY_COUNT, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

MERGE INTO AGENT_ANALYSIS_RESULT R
USING (
  SELECT 9001 AS RESULT_ID,
         9001 AS TASK_ID,
         9001 AS MANUSCRIPT_ID,
         9001 AS VERSION_ID,
         'SCREENING_ANALYSIS' AS RESULT_TYPE,
         '{"summary":"The paper is in scope and ready for chair screening.","risks":["Requires reviewer validation of claimed workflow impact."]}' AS RAW_RESULT_JSON,
         '{"summary":"The paper is in scope and ready for chair screening."}' AS REDACTED_RESULT_JSON
  FROM DUAL
) S
ON (R.TASK_ID = S.TASK_ID)
WHEN MATCHED THEN
  UPDATE SET
    R.MANUSCRIPT_ID = S.MANUSCRIPT_ID,
    R.VERSION_ID = S.VERSION_ID,
    R.RESULT_TYPE = S.RESULT_TYPE,
    R.RAW_RESULT_JSON = S.RAW_RESULT_JSON,
    R.REDACTED_RESULT_JSON = S.REDACTED_RESULT_JSON,
    R.CREATED_AT = CURRENT_TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (RESULT_ID, TASK_ID, MANUSCRIPT_ID, VERSION_ID, RESULT_TYPE, RAW_RESULT_JSON, REDACTED_RESULT_JSON, CREATED_AT)
  VALUES (S.RESULT_ID, S.TASK_ID, S.MANUSCRIPT_ID, S.VERSION_ID, S.RESULT_TYPE, S.RAW_RESULT_JSON, S.REDACTED_RESULT_JSON, CURRENT_TIMESTAMP);

COMMIT;
