SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE ANALYSIS_INTENT (
  INTENT_ID NUMBER(19) NOT NULL,
  ANALYSIS_TYPE VARCHAR2(40) NOT NULL,
  BUSINESS_ANCHOR_TYPE VARCHAR2(30) NOT NULL,
  BUSINESS_ANCHOR_ID NUMBER(19) NOT NULL,
  REQUESTED_BY NUMBER(19) NOT NULL,
  IDEMPOTENCY_KEY VARCHAR2(200) NOT NULL,
  BUSINESS_STATUS VARCHAR2(30) NOT NULL,
  EXECUTION_JOB_ID VARCHAR2(100),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ANALYSIS_INTENT PRIMARY KEY (INTENT_ID),
  CONSTRAINT UK_ANALYSIS_INTENT_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
  CONSTRAINT CK_ANALYSIS_INTENT_TYPE CHECK (ANALYSIS_TYPE IN ('REVIEWER_ASSIST', 'CONFLICT_ANALYSIS', 'SCREENING')),
  CONSTRAINT CK_ANALYSIS_INTENT_ANCHOR CHECK (BUSINESS_ANCHOR_TYPE IN ('ASSIGNMENT', 'ROUND', 'MANUSCRIPT')),
  CONSTRAINT CK_ANALYSIS_INTENT_STATUS CHECK (BUSINESS_STATUS IN ('REQUESTED', 'AVAILABLE', 'FAILED_VISIBLE', 'SUPERSEDED'))
);

CREATE TABLE ANALYSIS_PROJECTION (
  PROJECTION_ID NUMBER(19) NOT NULL,
  INTENT_ID NUMBER(19) NOT NULL,
  ANALYSIS_TYPE VARCHAR2(40) NOT NULL,
  VISIBILITY_LEVEL VARCHAR2(30) NOT NULL,
  BUSINESS_STATUS VARCHAR2(30) NOT NULL,
  SUMMARY_TEXT CLOB,
  REDACTED_RESULT CLOB,
  RAW_RESULT_REFERENCE VARCHAR2(100),
  IS_SUPERSEDED NUMBER(1) DEFAULT 0 NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ANALYSIS_PROJECTION PRIMARY KEY (PROJECTION_ID),
  CONSTRAINT UK_ANALYSIS_PROJECTION_INTENT UNIQUE (INTENT_ID),
  CONSTRAINT CK_ANALYSIS_PROJECTION_TYPE CHECK (ANALYSIS_TYPE IN ('REVIEWER_ASSIST', 'CONFLICT_ANALYSIS', 'SCREENING')),
  CONSTRAINT CK_ANALYSIS_PROJECTION_VISIBILITY CHECK (VISIBILITY_LEVEL IN ('NONE', 'REDACTED_ONLY', 'RAW_AND_REDACTED')),
  CONSTRAINT CK_ANALYSIS_PROJECTION_STATUS CHECK (BUSINESS_STATUS IN ('REQUESTED', 'AVAILABLE', 'FAILED_VISIBLE', 'SUPERSEDED')),
  CONSTRAINT CK_ANALYSIS_PROJECTION_SUPERSEDED CHECK (IS_SUPERSEDED IN (0, 1))
);

CREATE TABLE ANALYSIS_OUTBOX (
  OUTBOX_ID NUMBER(19) NOT NULL,
  INTENT_ID NUMBER(19) NOT NULL,
  MESSAGE_TYPE VARCHAR2(80) NOT NULL,
  MESSAGE_KEY VARCHAR2(200) NOT NULL,
  MESSAGE_PAYLOAD CLOB NOT NULL,
  MESSAGE_STATUS VARCHAR2(20) NOT NULL,
  RETRY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PUBLISHED_AT TIMESTAMP,
  CONSTRAINT PK_ANALYSIS_OUTBOX PRIMARY KEY (OUTBOX_ID),
  CONSTRAINT UK_ANALYSIS_OUTBOX_KEY UNIQUE (MESSAGE_KEY),
  CONSTRAINT CK_ANALYSIS_OUTBOX_STATUS CHECK (MESSAGE_STATUS IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE TABLE ANALYSIS_INBOX (
  INBOX_ID NUMBER(19) NOT NULL,
  INTENT_ID NUMBER(19),
  MESSAGE_TYPE VARCHAR2(80) NOT NULL,
  MESSAGE_KEY VARCHAR2(200) NOT NULL,
  MESSAGE_PAYLOAD CLOB NOT NULL,
  PROCESS_STATUS VARCHAR2(20) NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PROCESSED_AT TIMESTAMP,
  CONSTRAINT PK_ANALYSIS_INBOX PRIMARY KEY (INBOX_ID),
  CONSTRAINT UK_ANALYSIS_INBOX_KEY UNIQUE (MESSAGE_KEY),
  CONSTRAINT CK_ANALYSIS_INBOX_STATUS CHECK (PROCESS_STATUS IN ('PENDING', 'PROCESSED', 'FAILED'))
);

CREATE TABLE EXECUTION_JOB (
  JOB_ID VARCHAR2(100) NOT NULL,
  INTENT_ID NUMBER(19) NOT NULL,
  IDEMPOTENCY_KEY VARCHAR2(200) NOT NULL,
  ANALYSIS_TYPE VARCHAR2(40) NOT NULL,
  EXECUTION_STATE VARCHAR2(40) NOT NULL,
  INPUT_SNAPSHOT CLOB NOT NULL,
  FAILURE_REASON CLOB,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_EXECUTION_JOB PRIMARY KEY (JOB_ID),
  CONSTRAINT UK_EXECUTION_JOB_IDEMPOTENCY UNIQUE (IDEMPOTENCY_KEY),
  CONSTRAINT CK_EXECUTION_JOB_TYPE CHECK (ANALYSIS_TYPE IN ('REVIEWER_ASSIST', 'CONFLICT_ANALYSIS', 'SCREENING')),
  CONSTRAINT CK_EXECUTION_JOB_STATE CHECK (
    EXECUTION_STATE IN (
      'QUEUED',
      'DISPATCHED',
      'RUNNING',
      'SUCCEEDED',
      'FAILED_RETRYABLE',
      'FAILED_TERMINAL',
      'DEAD_LETTERED'
    )
  )
);

CREATE TABLE EXECUTION_ATTEMPT (
  ATTEMPT_ID NUMBER(19) NOT NULL,
  JOB_ID VARCHAR2(100) NOT NULL,
  ATTEMPT_NO NUMBER(10) NOT NULL,
  ATTEMPT_STATE VARCHAR2(40) NOT NULL,
  PROVIDER_NAME VARCHAR2(80),
  STARTED_AT TIMESTAMP,
  FINISHED_AT TIMESTAMP,
  ERROR_MESSAGE CLOB,
  CONSTRAINT PK_EXECUTION_ATTEMPT PRIMARY KEY (ATTEMPT_ID),
  CONSTRAINT UK_EXECUTION_ATTEMPT UNIQUE (JOB_ID, ATTEMPT_NO),
  CONSTRAINT CK_EXECUTION_ATTEMPT_STATE CHECK (
    ATTEMPT_STATE IN ('STARTED', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_TERMINAL')
  )
);

CREATE TABLE EXECUTION_ARTIFACT (
  ARTIFACT_ID NUMBER(19) NOT NULL,
  JOB_ID VARCHAR2(100) NOT NULL,
  ARTIFACT_TYPE VARCHAR2(40) NOT NULL,
  ARTIFACT_NAME VARCHAR2(255),
  ARTIFACT_DATA CLOB,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_EXECUTION_ARTIFACT PRIMARY KEY (ARTIFACT_ID),
  CONSTRAINT CK_EXECUTION_ARTIFACT_TYPE CHECK (
    ARTIFACT_TYPE IN ('RAW_RESULT', 'REDACTED_RESULT', 'SUMMARY_PROJECTION', 'ERROR_REPORT')
  )
);

CREATE TABLE EXECUTION_OUTBOX (
  OUTBOX_ID NUMBER(19) NOT NULL,
  JOB_ID VARCHAR2(100) NOT NULL,
  MESSAGE_TYPE VARCHAR2(80) NOT NULL,
  MESSAGE_KEY VARCHAR2(200) NOT NULL,
  MESSAGE_PAYLOAD CLOB NOT NULL,
  MESSAGE_STATUS VARCHAR2(20) NOT NULL,
  RETRY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PUBLISHED_AT TIMESTAMP,
  CONSTRAINT PK_EXECUTION_OUTBOX PRIMARY KEY (OUTBOX_ID),
  CONSTRAINT UK_EXECUTION_OUTBOX_KEY UNIQUE (MESSAGE_KEY),
  CONSTRAINT CK_EXECUTION_OUTBOX_STATUS CHECK (MESSAGE_STATUS IN ('PENDING', 'PUBLISHED', 'FAILED'))
);

CREATE TABLE EXECUTION_INBOX (
  INBOX_ID NUMBER(19) NOT NULL,
  JOB_ID VARCHAR2(100),
  MESSAGE_TYPE VARCHAR2(80) NOT NULL,
  MESSAGE_KEY VARCHAR2(200) NOT NULL,
  MESSAGE_PAYLOAD CLOB NOT NULL,
  PROCESS_STATUS VARCHAR2(20) NOT NULL,
  RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PROCESSED_AT TIMESTAMP,
  CONSTRAINT PK_EXECUTION_INBOX PRIMARY KEY (INBOX_ID),
  CONSTRAINT UK_EXECUTION_INBOX_KEY UNIQUE (MESSAGE_KEY),
  CONSTRAINT CK_EXECUTION_INBOX_STATUS CHECK (PROCESS_STATUS IN ('PENDING', 'PROCESSED', 'FAILED'))
);

CREATE SEQUENCE SEQ_ANALYSIS_INTENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANALYSIS_PROJECTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANALYSIS_OUTBOX START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANALYSIS_INBOX START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXECUTION_ATTEMPT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXECUTION_ARTIFACT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXECUTION_OUTBOX START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EXECUTION_INBOX START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ANALYSIS_INTENT_BI
BEFORE INSERT ON ANALYSIS_INTENT
FOR EACH ROW
BEGIN
  IF :NEW.INTENT_ID IS NULL THEN
    :NEW.INTENT_ID := SEQ_ANALYSIS_INTENT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ANALYSIS_PROJECTION_BI
BEFORE INSERT ON ANALYSIS_PROJECTION
FOR EACH ROW
BEGIN
  IF :NEW.PROJECTION_ID IS NULL THEN
    :NEW.PROJECTION_ID := SEQ_ANALYSIS_PROJECTION.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ANALYSIS_OUTBOX_BI
BEFORE INSERT ON ANALYSIS_OUTBOX
FOR EACH ROW
BEGIN
  IF :NEW.OUTBOX_ID IS NULL THEN
    :NEW.OUTBOX_ID := SEQ_ANALYSIS_OUTBOX.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ANALYSIS_INBOX_BI
BEFORE INSERT ON ANALYSIS_INBOX
FOR EACH ROW
BEGIN
  IF :NEW.INBOX_ID IS NULL THEN
    :NEW.INBOX_ID := SEQ_ANALYSIS_INBOX.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXECUTION_ATTEMPT_BI
BEFORE INSERT ON EXECUTION_ATTEMPT
FOR EACH ROW
BEGIN
  IF :NEW.ATTEMPT_ID IS NULL THEN
    :NEW.ATTEMPT_ID := SEQ_EXECUTION_ATTEMPT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXECUTION_ARTIFACT_BI
BEFORE INSERT ON EXECUTION_ARTIFACT
FOR EACH ROW
BEGIN
  IF :NEW.ARTIFACT_ID IS NULL THEN
    :NEW.ARTIFACT_ID := SEQ_EXECUTION_ARTIFACT.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXECUTION_OUTBOX_BI
BEFORE INSERT ON EXECUTION_OUTBOX
FOR EACH ROW
BEGIN
  IF :NEW.OUTBOX_ID IS NULL THEN
    :NEW.OUTBOX_ID := SEQ_EXECUTION_OUTBOX.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXECUTION_INBOX_BI
BEFORE INSERT ON EXECUTION_INBOX
FOR EACH ROW
BEGIN
  IF :NEW.INBOX_ID IS NULL THEN
    :NEW.INBOX_ID := SEQ_EXECUTION_INBOX.NEXTVAL;
  END IF;
END;
/

ALTER TABLE ANALYSIS_INTENT
  ADD CONSTRAINT FK_ANALYSIS_INTENT_EXECUTION_JOB FOREIGN KEY (EXECUTION_JOB_ID) REFERENCES EXECUTION_JOB (JOB_ID);

ALTER TABLE ANALYSIS_PROJECTION
  ADD CONSTRAINT FK_ANALYSIS_PROJECTION_INTENT FOREIGN KEY (INTENT_ID) REFERENCES ANALYSIS_INTENT (INTENT_ID);

ALTER TABLE ANALYSIS_OUTBOX
  ADD CONSTRAINT FK_ANALYSIS_OUTBOX_INTENT FOREIGN KEY (INTENT_ID) REFERENCES ANALYSIS_INTENT (INTENT_ID);

ALTER TABLE ANALYSIS_INBOX
  ADD CONSTRAINT FK_ANALYSIS_INBOX_INTENT FOREIGN KEY (INTENT_ID) REFERENCES ANALYSIS_INTENT (INTENT_ID);

ALTER TABLE EXECUTION_ATTEMPT
  ADD CONSTRAINT FK_EXECUTION_ATTEMPT_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOB (JOB_ID);

ALTER TABLE EXECUTION_ARTIFACT
  ADD CONSTRAINT FK_EXECUTION_ARTIFACT_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOB (JOB_ID);

ALTER TABLE EXECUTION_OUTBOX
  ADD CONSTRAINT FK_EXECUTION_OUTBOX_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOB (JOB_ID);

ALTER TABLE EXECUTION_INBOX
  ADD CONSTRAINT FK_EXECUTION_INBOX_JOB FOREIGN KEY (JOB_ID) REFERENCES EXECUTION_JOB (JOB_ID);
