SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE INDEX IDX_REVIEW_ROUND_STATUS_ID ON REVIEW_ROUND (ROUND_STATUS, ROUND_ID);
CREATE INDEX IDX_REVIEW_ASSIGNMENT_ROUND_ID ON REVIEW_ASSIGNMENT (ROUND_ID, ASSIGNMENT_ID);
CREATE INDEX IDX_REVIEW_ASSIGNMENT_ACCESS ON REVIEW_ASSIGNMENT (MANUSCRIPT_ID, VERSION_ID, REVIEWER_ID);
CREATE INDEX IDX_REVIEW_REPORT_ROUND ON REVIEW_REPORT (ROUND_ID, REVIEW_ID);
CREATE INDEX IDX_CONFLICT_CHECK_MANUSCRIPT_REVIEWER ON CONFLICT_CHECK_RECORD (MANUSCRIPT_ID, REVIEWER_ID);
CREATE INDEX IDX_MANUSCRIPT_STATUS_SUBMITTED ON MANUSCRIPT (CURRENT_STATUS, SUBMITTED_AT, MANUSCRIPT_ID);
CREATE INDEX IDX_ANALYSIS_PROJECTION_UPDATED ON ANALYSIS_PROJECTION (UPDATED_AT, PROJECTION_ID);
