SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_index_if_missing(P_INDEX_NAME IN VARCHAR2, P_SQL IN VARCHAR2) AS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = UPPER(P_INDEX_NAME);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE P_SQL;
    END IF;
  END;
BEGIN
  create_index_if_missing(
    'IDX_REVIEW_ROUND_STATUS_ID',
    'CREATE INDEX IDX_REVIEW_ROUND_STATUS_ID ON REVIEW_ROUND (ROUND_STATUS, ROUND_ID)'
  );
  create_index_if_missing(
    'IDX_REVIEW_ASSIGNMENT_ROUND_ID',
    'CREATE INDEX IDX_REVIEW_ASSIGNMENT_ROUND_ID ON REVIEW_ASSIGNMENT (ROUND_ID, ASSIGNMENT_ID)'
  );
  create_index_if_missing(
    'IDX_REVIEW_ASSIGNMENT_ACCESS',
    'CREATE INDEX IDX_REVIEW_ASSIGNMENT_ACCESS ON REVIEW_ASSIGNMENT (MANUSCRIPT_ID, VERSION_ID, REVIEWER_ID)'
  );
  create_index_if_missing(
    'IDX_REVIEW_REPORT_ROUND',
    'CREATE INDEX IDX_REVIEW_REPORT_ROUND ON REVIEW_REPORT (ROUND_ID, REVIEW_ID)'
  );
  create_index_if_missing(
    'IDX_CONFLICT_CHECK_MANUSCRIPT_REVIEWER',
    'CREATE INDEX IDX_CONFLICT_CHECK_MANUSCRIPT_REVIEWER ON CONFLICT_CHECK_RECORD (MANUSCRIPT_ID, REVIEWER_ID)'
  );
  create_index_if_missing(
    'IDX_MANUSCRIPT_STATUS_SUBMITTED',
    'CREATE INDEX IDX_MANUSCRIPT_STATUS_SUBMITTED ON MANUSCRIPT (CURRENT_STATUS, SUBMITTED_AT, MANUSCRIPT_ID)'
  );
  create_index_if_missing(
    'IDX_ANALYSIS_PROJECTION_UPDATED',
    'CREATE INDEX IDX_ANALYSIS_PROJECTION_UPDATED ON ANALYSIS_PROJECTION (UPDATED_AT, PROJECTION_ID)'
  );
END;
/
