SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE drop_object(P_SQL IN VARCHAR2, P_MISSING_CODE IN NUMBER) AS
  BEGIN
    EXECUTE IMMEDIATE P_SQL;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE <> P_MISSING_CODE THEN
        RAISE;
      END IF;
  END;
BEGIN
  drop_object('DROP TRIGGER TRG_AGENT_FEEDBACK_BI', -4080);
  drop_object('DROP TRIGGER TRG_AGENT_ANALYSIS_RESULT_BI', -4080);
  drop_object('DROP TRIGGER TRG_AGENT_ANALYSIS_TASK_BI', -4080);

  drop_object('DROP PROCEDURE PRC_AGENT_TASK_STATUS_SUMMARY', -4043);

  drop_object('DROP TABLE AGENT_FEEDBACK PURGE', -942);
  drop_object('DROP TABLE AGENT_ANALYSIS_RESULT PURGE', -942);
  drop_object('DROP TABLE AGENT_ANALYSIS_TASK PURGE', -942);

  drop_object('DROP SEQUENCE SEQ_AGENT_FEEDBACK', -2289);
  drop_object('DROP SEQUENCE SEQ_AGENT_ANALYSIS_RESULT', -2289);
  drop_object('DROP SEQUENCE SEQ_AGENT_ANALYSIS_TASK', -2289);
END;
/
