SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER TABLE SYS_USER DROP CONSTRAINT CK_SYS_USER_STATUS;

ALTER TABLE SYS_USER MODIFY (STATUS VARCHAR2(40));

ALTER TABLE SYS_USER
  ADD CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED', 'PENDING_EMAIL_VERIFICATION'));

CREATE TABLE USER_ACADEMIC_PROFILE (
  PROFILE_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  HOMEPAGE_URL VARCHAR2(500),
  ORCID VARCHAR2(50),
  DBLP_URL VARCHAR2(500),
  GOOGLE_SCHOLAR_URL VARCHAR2(500),
  REPRESENTATIVE_WORKS_JSON CLOB,
  CONFLICT_DOMAINS_JSON CLOB,
  DEFAULT_MAX_LOAD NUMBER(10) DEFAULT 3 NOT NULL,
  PLANNED_CONFERENCE_TITLE VARCHAR2(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_USER_ACADEMIC_PROFILE PRIMARY KEY (PROFILE_ID),
  CONSTRAINT UK_USER_ACADEMIC_PROFILE_USER UNIQUE (USER_ID),
  CONSTRAINT CK_USER_ACADEMIC_PROFILE_LOAD CHECK (DEFAULT_MAX_LOAD BETWEEN 1 AND 20)
);

CREATE TABLE ROLE_APPLICATION (
  APPLICATION_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  REGISTRATION_TYPE VARCHAR2(30) NOT NULL,
  APPLICATION_STATUS VARCHAR2(40) NOT NULL,
  SUBMITTED_PAYLOAD_JSON CLOB NOT NULL,
  SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  REVIEWED_BY NUMBER(19),
  REVIEWED_AT TIMESTAMP,
  REJECTION_REASON CLOB,
  CONSTRAINT PK_ROLE_APPLICATION PRIMARY KEY (APPLICATION_ID),
  CONSTRAINT UK_ROLE_APPLICATION_USER_TYPE UNIQUE (USER_ID, REGISTRATION_TYPE),
  CONSTRAINT CK_ROLE_APPLICATION_TYPE CHECK (REGISTRATION_TYPE IN ('AUTHOR', 'REVIEWER', 'ORGANIZER')),
  CONSTRAINT CK_ROLE_APPLICATION_STATUS CHECK (
    APPLICATION_STATUS IN ('PENDING_EMAIL_VERIFICATION', 'PENDING_ADMIN_APPROVAL', 'APPROVED', 'REJECTED')
  )
);

CREATE TABLE EMAIL_VERIFICATION_TOKEN (
  TOKEN_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  ROLE_APPLICATION_ID NUMBER(19) NOT NULL,
  TOKEN_HASH VARCHAR2(128) NOT NULL,
  TOKEN_PURPOSE VARCHAR2(40) NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  CONSUMED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_EMAIL_VERIFICATION_TOKEN PRIMARY KEY (TOKEN_ID),
  CONSTRAINT UK_EMAIL_VERIFICATION_TOKEN_HASH UNIQUE (TOKEN_HASH),
  CONSTRAINT CK_EMAIL_VERIFICATION_PURPOSE CHECK (TOKEN_PURPOSE IN ('EMAIL_VERIFICATION'))
);

CREATE SEQUENCE SEQ_USER_ACADEMIC_PROFILE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ROLE_APPLICATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMAIL_VERIFICATION_TOKEN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE USER_ACADEMIC_PROFILE
  ADD CONSTRAINT FK_USER_ACADEMIC_PROFILE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE ROLE_APPLICATION
  ADD CONSTRAINT FK_ROLE_APPLICATION_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE ROLE_APPLICATION
  ADD CONSTRAINT FK_ROLE_APPLICATION_REVIEWED_BY FOREIGN KEY (REVIEWED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE EMAIL_VERIFICATION_TOKEN
  ADD CONSTRAINT FK_EMAIL_VERIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE EMAIL_VERIFICATION_TOKEN
  ADD CONSTRAINT FK_EMAIL_VERIFICATION_APPLICATION FOREIGN KEY (ROLE_APPLICATION_ID) REFERENCES ROLE_APPLICATION (APPLICATION_ID);

CREATE INDEX IDX_ROLE_APPLICATION_STATUS_TYPE ON ROLE_APPLICATION (APPLICATION_STATUS, REGISTRATION_TYPE, APPLICATION_ID);
CREATE INDEX IDX_EMAIL_VERIFICATION_USER_APP ON EMAIL_VERIFICATION_TOKEN (USER_ID, ROLE_APPLICATION_ID);

CREATE OR REPLACE TRIGGER TRG_USER_ACADEMIC_PROFILE_BI
BEFORE INSERT ON USER_ACADEMIC_PROFILE
FOR EACH ROW
BEGIN
  IF :NEW.PROFILE_ID IS NULL THEN
    :NEW.PROFILE_ID := SEQ_USER_ACADEMIC_PROFILE.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ROLE_APPLICATION_BI
BEFORE INSERT ON ROLE_APPLICATION
FOR EACH ROW
BEGIN
  IF :NEW.APPLICATION_ID IS NULL THEN
    :NEW.APPLICATION_ID := SEQ_ROLE_APPLICATION.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EMAIL_VERIFICATION_TOKEN_BI
BEFORE INSERT ON EMAIL_VERIFICATION_TOKEN
FOR EACH ROW
BEGIN
  IF :NEW.TOKEN_ID IS NULL THEN
    :NEW.TOKEN_ID := SEQ_EMAIL_VERIFICATION_TOKEN.NEXTVAL;
  END IF;
END;
/
