SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE INDEX IDX_EMAIL_VERIFICATION_EXPIRES ON EMAIL_VERIFICATION_TOKEN (EXPIRES_AT);
CREATE INDEX IDX_EMAIL_VERIFICATION_USER_PURPOSE ON EMAIL_VERIFICATION_TOKEN (USER_ID, TOKEN_PURPOSE, CONSUMED_AT);
