SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE CONFERENCE (
  CONFERENCE_ID NUMBER(19) NOT NULL,
  NAME VARCHAR2(300) NOT NULL,
  ACRONYM VARCHAR2(60) NOT NULL,
  CONFERENCE_YEAR NUMBER(4) NOT NULL,
  ORGANIZER_USER_ID NUMBER(19) NOT NULL,
  CONFERENCE_STATUS VARCHAR2(40) NOT NULL,
  BLIND_MODE VARCHAR2(30) NOT NULL,
  CFP_TEXT CLOB NOT NULL,
  TOPIC_AREAS_JSON CLOB NOT NULL,
  TARGET_REVIEWS_PER_PAPER NUMBER(10) DEFAULT 3 NOT NULL,
  DEFAULT_REVIEWER_MAX_LOAD NUMBER(10) DEFAULT 3 NOT NULL,
  PUBLIC_SLUG VARCHAR2(150) NOT NULL,
  CFP_PUBLISHED NUMBER(1) DEFAULT 0 NOT NULL,
  APPROVED_BY NUMBER(19),
  APPROVED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CONFERENCE PRIMARY KEY (CONFERENCE_ID),
  CONSTRAINT UK_CONFERENCE_SLUG UNIQUE (PUBLIC_SLUG),
  CONSTRAINT UK_CONFERENCE_ACRONYM_YEAR UNIQUE (ACRONYM, CONFERENCE_YEAR),
  CONSTRAINT CK_CONFERENCE_STATUS CHECK (
    CONFERENCE_STATUS IN (
      'DRAFT',
      'PENDING_APPROVAL',
      'OPEN_FOR_SUBMISSION',
      'SUBMISSION_CLOSED',
      'BIDDING_OPEN',
      'REVIEW_ASSIGNMENT',
      'REVIEWING',
      'DECISION',
      'CLOSED'
    )
  ),
  CONSTRAINT CK_CONFERENCE_BLIND_MODE CHECK (BLIND_MODE IN ('DOUBLE_BLIND', 'SINGLE_BLIND', 'OPEN')),
  CONSTRAINT CK_CONFERENCE_CFP_PUBLISHED CHECK (CFP_PUBLISHED IN (0, 1)),
  CONSTRAINT CK_CONFERENCE_TARGET_REVIEWS CHECK (TARGET_REVIEWS_PER_PAPER BETWEEN 1 AND 10),
  CONSTRAINT CK_CONFERENCE_REVIEWER_LOAD CHECK (DEFAULT_REVIEWER_MAX_LOAD BETWEEN 1 AND 20)
);

CREATE TABLE CONFERENCE_PHASE (
  PHASE_ID NUMBER(19) NOT NULL,
  CONFERENCE_ID NUMBER(19) NOT NULL,
  SUBMISSION_OPEN_AT TIMESTAMP NOT NULL,
  SUBMISSION_CLOSE_AT TIMESTAMP NOT NULL,
  BIDDING_OPEN_AT TIMESTAMP NOT NULL,
  BIDDING_CLOSE_AT TIMESTAMP NOT NULL,
  REVIEW_DEADLINE_AT TIMESTAMP NOT NULL,
  DECISION_RELEASE_AT TIMESTAMP NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CONFERENCE_PHASE PRIMARY KEY (PHASE_ID),
  CONSTRAINT UK_CONFERENCE_PHASE_CONFERENCE UNIQUE (CONFERENCE_ID),
  CONSTRAINT CK_CONFERENCE_PHASE_ORDER CHECK (
    SUBMISSION_OPEN_AT < SUBMISSION_CLOSE_AT
    AND SUBMISSION_CLOSE_AT < BIDDING_OPEN_AT
    AND BIDDING_OPEN_AT < BIDDING_CLOSE_AT
    AND BIDDING_CLOSE_AT < REVIEW_DEADLINE_AT
    AND REVIEW_DEADLINE_AT < DECISION_RELEASE_AT
  )
);

CREATE SEQUENCE SEQ_CONFERENCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONFERENCE_PHASE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE CONFERENCE
  ADD CONSTRAINT FK_CONFERENCE_ORGANIZER FOREIGN KEY (ORGANIZER_USER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE CONFERENCE
  ADD CONSTRAINT FK_CONFERENCE_APPROVED_BY FOREIGN KEY (APPROVED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE CONFERENCE_PHASE
  ADD CONSTRAINT FK_CONFERENCE_PHASE_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID);

CREATE INDEX IDX_CONFERENCE_PUBLIC_STATUS ON CONFERENCE (CFP_PUBLISHED, CONFERENCE_STATUS, CONFERENCE_ID);
CREATE INDEX IDX_CONFERENCE_ORGANIZER_STATUS ON CONFERENCE (ORGANIZER_USER_ID, CONFERENCE_STATUS, CONFERENCE_ID);
CREATE INDEX IDX_CONFERENCE_PHASE_SUBMISSION_CLOSE ON CONFERENCE_PHASE (SUBMISSION_CLOSE_AT, CONFERENCE_ID);
CREATE INDEX IDX_CONFERENCE_PHASE_BIDDING_CLOSE ON CONFERENCE_PHASE (BIDDING_CLOSE_AT, CONFERENCE_ID);

CREATE OR REPLACE TRIGGER TRG_CONFERENCE_BI
BEFORE INSERT ON CONFERENCE
FOR EACH ROW
BEGIN
  IF :NEW.CONFERENCE_ID IS NULL THEN
    :NEW.CONFERENCE_ID := SEQ_CONFERENCE.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONFERENCE_PHASE_BI
BEFORE INSERT ON CONFERENCE_PHASE
FOR EACH ROW
BEGIN
  IF :NEW.PHASE_ID IS NULL THEN
    :NEW.PHASE_ID := SEQ_CONFERENCE_PHASE.NEXTVAL;
  END IF;
END;
/
