SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER TABLE MANUSCRIPT ADD (CONFERENCE_ID NUMBER(19));

MERGE INTO CONFERENCE C
USING (
  SELECT
    0 AS CONFERENCE_ID,
    'Legacy / Platform Default' AS NAME,
    'LEGACY' AS ACRONYM,
    2026 AS CONFERENCE_YEAR,
    1003 AS ORGANIZER_USER_ID,
    'OPEN_FOR_SUBMISSION' AS CONFERENCE_STATUS,
    'DOUBLE_BLIND' AS BLIND_MODE,
    'Default conference for manuscripts created before conference-scoped submissions.' AS CFP_TEXT,
    '["LEGACY"]' AS TOPIC_AREAS_JSON,
    3 AS TARGET_REVIEWS_PER_PAPER,
    3 AS DEFAULT_REVIEWER_MAX_LOAD,
    'legacy-platform-default' AS PUBLIC_SLUG,
    0 AS CFP_PUBLISHED
  FROM DUAL
) S
ON (C.PUBLIC_SLUG = S.PUBLIC_SLUG)
WHEN NOT MATCHED THEN
  INSERT (
    CONFERENCE_ID, NAME, ACRONYM, CONFERENCE_YEAR, ORGANIZER_USER_ID,
    CONFERENCE_STATUS, BLIND_MODE, CFP_TEXT, TOPIC_AREAS_JSON,
    TARGET_REVIEWS_PER_PAPER, DEFAULT_REVIEWER_MAX_LOAD, PUBLIC_SLUG, CFP_PUBLISHED
  ) VALUES (
    S.CONFERENCE_ID, S.NAME, S.ACRONYM, S.CONFERENCE_YEAR, S.ORGANIZER_USER_ID,
    S.CONFERENCE_STATUS, S.BLIND_MODE, S.CFP_TEXT, S.TOPIC_AREAS_JSON,
    S.TARGET_REVIEWS_PER_PAPER, S.DEFAULT_REVIEWER_MAX_LOAD, S.PUBLIC_SLUG, S.CFP_PUBLISHED
  );

MERGE INTO CONFERENCE_PHASE P
USING (
  SELECT
    0 AS PHASE_ID,
    C.CONFERENCE_ID,
    TIMESTAMP '2026-01-01 00:00:00' AS SUBMISSION_OPEN_AT,
    TIMESTAMP '2099-12-30 00:00:00' AS ABSTRACT_SUBMISSION_CLOSE_AT,
    TIMESTAMP '2099-12-31 00:00:00' AS SUBMISSION_CLOSE_AT,
    TIMESTAMP '2100-01-01 00:00:00' AS BIDDING_OPEN_AT,
    TIMESTAMP '2100-01-02 00:00:00' AS BIDDING_CLOSE_AT,
    TIMESTAMP '2100-01-03 00:00:00' AS REVIEW_DEADLINE_AT,
    TIMESTAMP '2100-01-04 00:00:00' AS DECISION_RELEASE_AT
  FROM CONFERENCE C
  WHERE C.PUBLIC_SLUG = 'legacy-platform-default'
) S
ON (P.CONFERENCE_ID = S.CONFERENCE_ID)
WHEN NOT MATCHED THEN
  INSERT (
    PHASE_ID, CONFERENCE_ID, SUBMISSION_OPEN_AT, ABSTRACT_SUBMISSION_CLOSE_AT, SUBMISSION_CLOSE_AT,
    BIDDING_OPEN_AT, BIDDING_CLOSE_AT, REVIEW_DEADLINE_AT, DECISION_RELEASE_AT
  ) VALUES (
    S.PHASE_ID, S.CONFERENCE_ID, S.SUBMISSION_OPEN_AT, S.ABSTRACT_SUBMISSION_CLOSE_AT, S.SUBMISSION_CLOSE_AT,
    S.BIDDING_OPEN_AT, S.BIDDING_CLOSE_AT, S.REVIEW_DEADLINE_AT, S.DECISION_RELEASE_AT
  );

UPDATE MANUSCRIPT
SET CONFERENCE_ID = (
  SELECT CONFERENCE_ID
  FROM CONFERENCE
  WHERE PUBLIC_SLUG = 'legacy-platform-default'
)
WHERE CONFERENCE_ID IS NULL;

ALTER TABLE MANUSCRIPT
  ADD CONSTRAINT FK_MANUSCRIPT_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID);

CREATE INDEX IDX_MANUSCRIPT_CONFERENCE_STATUS ON MANUSCRIPT (CONFERENCE_ID, CURRENT_STATUS, MANUSCRIPT_ID);
