SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER TABLE CONFLICT_CHECK_RECORD MODIFY (ASSIGNMENT_ID NULL);

CREATE TABLE CONFERENCE_REVIEWER (
  CONFERENCE_REVIEWER_ID NUMBER(19) NOT NULL,
  CONFERENCE_ID NUMBER(19) NOT NULL,
  REVIEWER_ID NUMBER(19) NOT NULL,
  MAX_LOAD NUMBER(10) NOT NULL,
  RESEARCH_AREAS_JSON CLOB NOT NULL,
  MEMBERSHIP_STATUS VARCHAR2(20) NOT NULL,
  INVITED_BY NUMBER(19) NOT NULL,
  JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_CONFERENCE_REVIEWER PRIMARY KEY (CONFERENCE_REVIEWER_ID),
  CONSTRAINT UK_CONFERENCE_REVIEWER UNIQUE (CONFERENCE_ID, REVIEWER_ID),
  CONSTRAINT CK_CONFERENCE_REVIEWER_STATUS CHECK (MEMBERSHIP_STATUS IN ('ACTIVE', 'REMOVED')),
  CONSTRAINT CK_CONFERENCE_REVIEWER_MAX_LOAD CHECK (MAX_LOAD BETWEEN 1 AND 20)
);

CREATE TABLE REVIEWER_BID (
  BID_ID NUMBER(19) NOT NULL,
  CONFERENCE_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  REVIEWER_ID NUMBER(19) NOT NULL,
  BID_VALUE VARCHAR2(30) NOT NULL,
  CONFLICT_DECLARED NUMBER(1) DEFAULT 0 NOT NULL,
  BID_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_REVIEWER_BID PRIMARY KEY (BID_ID),
  CONSTRAINT UK_REVIEWER_BID UNIQUE (CONFERENCE_ID, MANUSCRIPT_ID, REVIEWER_ID),
  CONSTRAINT CK_REVIEWER_BID_VALUE CHECK (BID_VALUE IN ('WANT_TO_REVIEW', 'NEUTRAL', 'DECLINE')),
  CONSTRAINT CK_REVIEWER_BID_CONFLICT CHECK (CONFLICT_DECLARED IN (0, 1))
);

CREATE SEQUENCE SEQ_CONFERENCE_REVIEWER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_REVIEWER_BID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE CONFERENCE_REVIEWER
  ADD CONSTRAINT FK_CONFERENCE_REVIEWER_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID);

ALTER TABLE CONFERENCE_REVIEWER
  ADD CONSTRAINT FK_CONFERENCE_REVIEWER_USER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE CONFERENCE_REVIEWER
  ADD CONSTRAINT FK_CONFERENCE_REVIEWER_INVITER FOREIGN KEY (INVITED_BY) REFERENCES SYS_USER (USER_ID);

ALTER TABLE REVIEWER_BID
  ADD CONSTRAINT FK_REVIEWER_BID_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID);

ALTER TABLE REVIEWER_BID
  ADD CONSTRAINT FK_REVIEWER_BID_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE REVIEWER_BID
  ADD CONSTRAINT FK_REVIEWER_BID_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID);

CREATE INDEX IDX_CONFERENCE_REVIEWER_CONF_STATUS ON CONFERENCE_REVIEWER (CONFERENCE_ID, MEMBERSHIP_STATUS, REVIEWER_ID);
CREATE INDEX IDX_CONFERENCE_REVIEWER_REVIEWER ON CONFERENCE_REVIEWER (REVIEWER_ID, CONFERENCE_ID);
CREATE INDEX IDX_REVIEWER_BID_REVIEWER_CONF ON REVIEWER_BID (REVIEWER_ID, CONFERENCE_ID, BID_ID);
CREATE INDEX IDX_REVIEWER_BID_MANUSCRIPT ON REVIEWER_BID (MANUSCRIPT_ID, BID_VALUE);

CREATE OR REPLACE TRIGGER TRG_CONFERENCE_REVIEWER_BI
BEFORE INSERT ON CONFERENCE_REVIEWER
FOR EACH ROW
BEGIN
  IF :NEW.CONFERENCE_REVIEWER_ID IS NULL THEN
    :NEW.CONFERENCE_REVIEWER_ID := SEQ_CONFERENCE_REVIEWER.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEWER_BID_BI
BEFORE INSERT ON REVIEWER_BID
FOR EACH ROW
BEGIN
  IF :NEW.BID_ID IS NULL THEN
    :NEW.BID_ID := SEQ_REVIEWER_BID.NEXTVAL;
  END IF;
END;
/
