SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE ASSIGNMENT_DRAFT (
  ASSIGNMENT_DRAFT_ID NUMBER(19) NOT NULL,
  ROUND_ID NUMBER(19) NOT NULL,
  MANUSCRIPT_ID NUMBER(19) NOT NULL,
  VERSION_ID NUMBER(19) NOT NULL,
  REVIEWER_ID NUMBER(19) NOT NULL,
  RANK_ORDER NUMBER(10) NOT NULL,
  SCORE NUMBER(10) NOT NULL,
  CURRENT_LOAD NUMBER(10) NOT NULL,
  MAX_LOAD NUMBER(10) NOT NULL,
  BID_VALUE VARCHAR2(30),
  REASON VARCHAR2(500),
  DRAFT_STATUS VARCHAR2(20) NOT NULL,
  CREATED_BY NUMBER(19) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_ASSIGNMENT_DRAFT PRIMARY KEY (ASSIGNMENT_DRAFT_ID),
  CONSTRAINT UK_ASSIGNMENT_DRAFT_ROUND_REVIEWER UNIQUE (ROUND_ID, REVIEWER_ID),
  CONSTRAINT CK_ASSIGNMENT_DRAFT_STATUS CHECK (DRAFT_STATUS IN ('PROPOSED', 'CONFIRMED', 'DISMISSED')),
  CONSTRAINT CK_ASSIGNMENT_DRAFT_RANK CHECK (RANK_ORDER > 0),
  CONSTRAINT CK_ASSIGNMENT_DRAFT_LOAD CHECK (CURRENT_LOAD >= 0 AND MAX_LOAD BETWEEN 1 AND 20)
);

CREATE SEQUENCE SEQ_ASSIGNMENT_DRAFT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE ASSIGNMENT_DRAFT
  ADD CONSTRAINT FK_ASSIGNMENT_DRAFT_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID);

ALTER TABLE ASSIGNMENT_DRAFT
  ADD CONSTRAINT FK_ASSIGNMENT_DRAFT_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID);

ALTER TABLE ASSIGNMENT_DRAFT
  ADD CONSTRAINT FK_ASSIGNMENT_DRAFT_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID);

ALTER TABLE ASSIGNMENT_DRAFT
  ADD CONSTRAINT FK_ASSIGNMENT_DRAFT_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID);

ALTER TABLE ASSIGNMENT_DRAFT
  ADD CONSTRAINT FK_ASSIGNMENT_DRAFT_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES SYS_USER (USER_ID);

CREATE INDEX IDX_ASSIGNMENT_DRAFT_ROUND_STATUS ON ASSIGNMENT_DRAFT (ROUND_ID, DRAFT_STATUS, RANK_ORDER);
CREATE INDEX IDX_ASSIGNMENT_DRAFT_REVIEWER ON ASSIGNMENT_DRAFT (REVIEWER_ID, ROUND_ID);
CREATE INDEX IDX_ASSIGNMENT_DRAFT_MANUSCRIPT ON ASSIGNMENT_DRAFT (MANUSCRIPT_ID, REVIEWER_ID);

CREATE OR REPLACE TRIGGER TRG_ASSIGNMENT_DRAFT_BI
BEFORE INSERT ON ASSIGNMENT_DRAFT
FOR EACH ROW
BEGIN
  IF :NEW.ASSIGNMENT_DRAFT_ID IS NULL THEN
    :NEW.ASSIGNMENT_DRAFT_ID := SEQ_ASSIGNMENT_DRAFT.NEXTVAL;
  END IF;
END;
/
