SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER TABLE ANALYSIS_PROJECTION DROP CONSTRAINT CK_ANALYSIS_PROJECTION_TYPE;
ALTER TABLE ANALYSIS_INTENT DROP CONSTRAINT CK_ANALYSIS_INTENT_TYPE;
ALTER TABLE EXECUTION_JOB DROP CONSTRAINT CK_EXECUTION_JOB_TYPE;

ALTER TABLE ANALYSIS_INTENT
  ADD CONSTRAINT CK_ANALYSIS_INTENT_TYPE CHECK (
    ANALYSIS_TYPE IN ('REVIEWER_ASSIST', 'REVIEWER_ASSIGNMENT_ASSIST', 'CONFLICT_ANALYSIS', 'SCREENING')
  );

ALTER TABLE ANALYSIS_PROJECTION
  ADD CONSTRAINT CK_ANALYSIS_PROJECTION_TYPE CHECK (
    ANALYSIS_TYPE IN ('REVIEWER_ASSIST', 'REVIEWER_ASSIGNMENT_ASSIST', 'CONFLICT_ANALYSIS', 'SCREENING')
  );

ALTER TABLE EXECUTION_JOB
  ADD CONSTRAINT CK_EXECUTION_JOB_TYPE CHECK (
    ANALYSIS_TYPE IN ('REVIEWER_ASSIST', 'REVIEWER_ASSIGNMENT_ASSIST', 'CONFLICT_ANALYSIS', 'SCREENING')
  );
