SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_table_if_missing(
    p_table_name IN VARCHAR2,
    p_table_ddl IN CLOB
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = UPPER(p_table_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_table_ddl;
    END IF;
  END;

  PROCEDURE create_sequence_if_missing(
    p_sequence_name IN VARCHAR2,
    p_sequence_ddl IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = UPPER(p_sequence_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sequence_ddl;
    END IF;
  END;

  PROCEDURE add_constraint_if_missing(
    p_constraint_name IN VARCHAR2,
    p_constraint_ddl IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_constraint_ddl;
    END IF;
  END;

  PROCEDURE create_index_if_missing(
    p_index_name IN VARCHAR2,
    p_index_ddl IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = UPPER(p_index_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_index_ddl;
    END IF;
  END;
BEGIN
  create_table_if_missing(
    'REVIEW_DISCUSSION_MESSAGE',
    q'[
      CREATE TABLE REVIEW_DISCUSSION_MESSAGE (
        MESSAGE_ID NUMBER(19) NOT NULL,
        ROUND_ID NUMBER(19) NOT NULL,
        ASSIGNMENT_ID NUMBER(19),
        MANUSCRIPT_ID NUMBER(19) NOT NULL,
        SENDER_ID NUMBER(19) NOT NULL,
        SENDER_ROLE VARCHAR2(30) NOT NULL,
        MESSAGE_SCOPE VARCHAR2(30) NOT NULL,
        MESSAGE_TEXT CLOB NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_REVIEW_DISCUSSION_MESSAGE PRIMARY KEY (MESSAGE_ID),
        CONSTRAINT CK_REVIEW_DISCUSSION_ROLE CHECK (SENDER_ROLE IN ('CHAIR', 'REVIEWER')),
        CONSTRAINT CK_REVIEW_DISCUSSION_SCOPE CHECK (MESSAGE_SCOPE IN ('ROUND', 'ASSIGNMENT', 'META_REVIEW'))
      )
    ]'
  );

  create_table_if_missing(
    'CAMERA_READY_SUBMISSION',
    q'[
      CREATE TABLE CAMERA_READY_SUBMISSION (
        CAMERA_READY_ID NUMBER(19) NOT NULL,
        MANUSCRIPT_ID NUMBER(19) NOT NULL,
        VERSION_ID NUMBER(19) NOT NULL,
        SUBMITTED_BY NUMBER(19) NOT NULL,
        FILE_NAME VARCHAR2(255) NOT NULL,
        FILE_SIZE NUMBER(19) NOT NULL,
        COPYRIGHT_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
        LICENSE_TYPE VARCHAR2(80),
        STATUS VARCHAR2(30) NOT NULL,
        SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_CAMERA_READY_SUBMISSION PRIMARY KEY (CAMERA_READY_ID),
        CONSTRAINT UK_CAMERA_READY_MANUSCRIPT UNIQUE (MANUSCRIPT_ID),
        CONSTRAINT CK_CAMERA_READY_STATUS CHECK (STATUS IN ('SUBMITTED', 'APPROVED', 'REJECTED')),
        CONSTRAINT CK_CAMERA_READY_COPYRIGHT CHECK (COPYRIGHT_CONFIRMED IN (0, 1)),
        CONSTRAINT CK_CAMERA_READY_FILE_SIZE CHECK (FILE_SIZE >= 0)
      )
    ]'
  );

  create_table_if_missing(
    'COMMUNICATION_LOG',
    q'[
      CREATE TABLE COMMUNICATION_LOG (
        COMMUNICATION_ID NUMBER(19) NOT NULL,
        CONFERENCE_ID NUMBER(19),
        MANUSCRIPT_ID NUMBER(19),
        RECIPIENT_ID NUMBER(19) NOT NULL,
        CHANNEL VARCHAR2(30) NOT NULL,
        TEMPLATE_KEY VARCHAR2(100) NOT NULL,
        SUBJECT VARCHAR2(300) NOT NULL,
        DELIVERY_STATUS VARCHAR2(30) NOT NULL,
        BIZ_TYPE VARCHAR2(50),
        BIZ_ID NUMBER(19),
        SENT_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        DETAIL_JSON CLOB,
        CONSTRAINT PK_COMMUNICATION_LOG PRIMARY KEY (COMMUNICATION_ID),
        CONSTRAINT CK_COMMUNICATION_LOG_CHANNEL CHECK (CHANNEL IN ('IN_APP', 'EMAIL')),
        CONSTRAINT CK_COMMUNICATION_LOG_STATUS CHECK (DELIVERY_STATUS IN ('QUEUED', 'SENT', 'FAILED', 'SKIPPED'))
      )
    ]'
  );

  create_sequence_if_missing(
    'SEQ_REVIEW_DISCUSSION_MESSAGE',
    'CREATE SEQUENCE SEQ_REVIEW_DISCUSSION_MESSAGE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'
  );
  create_sequence_if_missing(
    'SEQ_CAMERA_READY_SUBMISSION',
    'CREATE SEQUENCE SEQ_CAMERA_READY_SUBMISSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'
  );
  create_sequence_if_missing(
    'SEQ_COMMUNICATION_LOG',
    'CREATE SEQUENCE SEQ_COMMUNICATION_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'
  );

  add_constraint_if_missing(
    'FK_REVIEW_DISCUSSION_ROUND',
    'ALTER TABLE REVIEW_DISCUSSION_MESSAGE ADD CONSTRAINT FK_REVIEW_DISCUSSION_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID)'
  );
  add_constraint_if_missing(
    'FK_REVIEW_DISCUSSION_ASSIGNMENT',
    'ALTER TABLE REVIEW_DISCUSSION_MESSAGE ADD CONSTRAINT FK_REVIEW_DISCUSSION_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID)'
  );
  add_constraint_if_missing(
    'FK_REVIEW_DISCUSSION_MANUSCRIPT',
    'ALTER TABLE REVIEW_DISCUSSION_MESSAGE ADD CONSTRAINT FK_REVIEW_DISCUSSION_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)'
  );
  add_constraint_if_missing(
    'FK_REVIEW_DISCUSSION_SENDER',
    'ALTER TABLE REVIEW_DISCUSSION_MESSAGE ADD CONSTRAINT FK_REVIEW_DISCUSSION_SENDER FOREIGN KEY (SENDER_ID) REFERENCES SYS_USER (USER_ID)'
  );
  add_constraint_if_missing(
    'FK_CAMERA_READY_MANUSCRIPT',
    'ALTER TABLE CAMERA_READY_SUBMISSION ADD CONSTRAINT FK_CAMERA_READY_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)'
  );
  add_constraint_if_missing(
    'FK_CAMERA_READY_VERSION',
    'ALTER TABLE CAMERA_READY_SUBMISSION ADD CONSTRAINT FK_CAMERA_READY_VERSION FOREIGN KEY (VERSION_ID) REFERENCES MANUSCRIPT_VERSION (VERSION_ID)'
  );
  add_constraint_if_missing(
    'FK_CAMERA_READY_SUBMITTED_BY',
    'ALTER TABLE CAMERA_READY_SUBMISSION ADD CONSTRAINT FK_CAMERA_READY_SUBMITTED_BY FOREIGN KEY (SUBMITTED_BY) REFERENCES SYS_USER (USER_ID)'
  );
  add_constraint_if_missing(
    'FK_COMMUNICATION_LOG_CONFERENCE',
    'ALTER TABLE COMMUNICATION_LOG ADD CONSTRAINT FK_COMMUNICATION_LOG_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)'
  );
  add_constraint_if_missing(
    'FK_COMMUNICATION_LOG_MANUSCRIPT',
    'ALTER TABLE COMMUNICATION_LOG ADD CONSTRAINT FK_COMMUNICATION_LOG_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)'
  );
  add_constraint_if_missing(
    'FK_COMMUNICATION_LOG_RECIPIENT',
    'ALTER TABLE COMMUNICATION_LOG ADD CONSTRAINT FK_COMMUNICATION_LOG_RECIPIENT FOREIGN KEY (RECIPIENT_ID) REFERENCES SYS_USER (USER_ID)'
  );

  create_index_if_missing(
    'IDX_REVIEW_DISCUSSION_ROUND',
    'CREATE INDEX IDX_REVIEW_DISCUSSION_ROUND ON REVIEW_DISCUSSION_MESSAGE (ROUND_ID, MESSAGE_SCOPE, CREATED_AT)'
  );
  create_index_if_missing(
    'IDX_REVIEW_DISCUSSION_ASSIGNMENT',
    'CREATE INDEX IDX_REVIEW_DISCUSSION_ASSIGNMENT ON REVIEW_DISCUSSION_MESSAGE (ASSIGNMENT_ID, CREATED_AT)'
  );
  create_index_if_missing(
    'IDX_CAMERA_READY_MANUSCRIPT',
    'CREATE INDEX IDX_CAMERA_READY_MANUSCRIPT ON CAMERA_READY_SUBMISSION (MANUSCRIPT_ID, STATUS)'
  );
  create_index_if_missing(
    'IDX_CAMERA_READY_STATUS',
    'CREATE INDEX IDX_CAMERA_READY_STATUS ON CAMERA_READY_SUBMISSION (STATUS, UPDATED_AT)'
  );
  create_index_if_missing(
    'IDX_COMMUNICATION_LOG_CONFERENCE',
    'CREATE INDEX IDX_COMMUNICATION_LOG_CONFERENCE ON COMMUNICATION_LOG (CONFERENCE_ID, SENT_AT)'
  );
  create_index_if_missing(
    'IDX_COMMUNICATION_LOG_RECIPIENT',
    'CREATE INDEX IDX_COMMUNICATION_LOG_RECIPIENT ON COMMUNICATION_LOG (RECIPIENT_ID, SENT_AT)'
  );
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_DISCUSSION_MESSAGE_BI
BEFORE INSERT ON REVIEW_DISCUSSION_MESSAGE
FOR EACH ROW
BEGIN
  IF :NEW.MESSAGE_ID IS NULL THEN
    :NEW.MESSAGE_ID := SEQ_REVIEW_DISCUSSION_MESSAGE.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CAMERA_READY_SUBMISSION_BIU
BEFORE INSERT OR UPDATE ON CAMERA_READY_SUBMISSION
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.CAMERA_READY_ID IS NULL THEN
    :NEW.CAMERA_READY_ID := SEQ_CAMERA_READY_SUBMISSION.NEXTVAL;
  END IF;
  IF INSERTING AND :NEW.STATUS IS NULL THEN
    :NEW.STATUS := 'SUBMITTED';
  END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_COMMUNICATION_LOG_BI
BEFORE INSERT ON COMMUNICATION_LOG
FOR EACH ROW
BEGIN
  IF :NEW.COMMUNICATION_ID IS NULL THEN
    :NEW.COMMUNICATION_ID := SEQ_COMMUNICATION_LOG.NEXTVAL;
  END IF;
END;
/
