SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_table_if_missing(
    p_table_name IN VARCHAR2,
    p_table_ddl IN CLOB
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = UPPER(p_table_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_table_ddl;
    END IF;
  END;

  PROCEDURE create_sequence_if_missing(
    p_sequence_name IN VARCHAR2,
    p_sequence_ddl IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = UPPER(p_sequence_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sequence_ddl;
    END IF;
  END;

  PROCEDURE add_constraint_if_missing(
    p_constraint_name IN VARCHAR2,
    p_constraint_ddl IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_constraint_ddl;
    END IF;
  END;

  PROCEDURE create_index_if_missing(
    p_index_name IN VARCHAR2,
    p_index_ddl IN VARCHAR2
  ) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = UPPER(p_index_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_index_ddl;
    END IF;
  END;
BEGIN
  create_table_if_missing(
    'CONFERENCE_FORM_DEFINITION',
    q'[
      CREATE TABLE CONFERENCE_FORM_DEFINITION (
        FORM_ID NUMBER(19) NOT NULL,
        CONFERENCE_ID NUMBER(19) NOT NULL,
        FORM_TYPE VARCHAR2(40) NOT NULL,
        FORM_NAME VARCHAR2(200) NOT NULL,
        ACTIVE_FLAG NUMBER(1) DEFAULT 1 NOT NULL,
        CREATED_BY NUMBER(19) NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_CONFERENCE_FORM_DEFINITION PRIMARY KEY (FORM_ID),
        CONSTRAINT CK_CONF_FORM_TYPE CHECK (FORM_TYPE IN ('SUBMISSION', 'REVIEW', 'META_REVIEW', 'AUTHOR_FEEDBACK', 'CAMERA_READY')),
        CONSTRAINT CK_CONF_FORM_ACTIVE CHECK (ACTIVE_FLAG IN (0, 1))
      )
    ]'
  );

  create_table_if_missing(
    'CONFERENCE_FORM_FIELD',
    q'[
      CREATE TABLE CONFERENCE_FORM_FIELD (
        FIELD_ID NUMBER(19) NOT NULL,
        FORM_ID NUMBER(19) NOT NULL,
        FIELD_KEY VARCHAR2(100) NOT NULL,
        FIELD_LABEL VARCHAR2(300) NOT NULL,
        FIELD_TYPE VARCHAR2(40) NOT NULL,
        REQUIRED_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
        VISIBILITY VARCHAR2(40) NOT NULL,
        DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
        OPTIONS_JSON CLOB,
        CONSTRAINT PK_CONFERENCE_FORM_FIELD PRIMARY KEY (FIELD_ID),
        CONSTRAINT UK_CONFERENCE_FORM_FIELD_KEY UNIQUE (FORM_ID, FIELD_KEY),
        CONSTRAINT CK_CONF_FORM_FIELD_TYPE CHECK (FIELD_TYPE IN ('TEXT', 'LONG_TEXT', 'NUMBER', 'SCORE', 'BOOLEAN', 'SELECT')),
        CONSTRAINT CK_CONF_FORM_FIELD_REQUIRED CHECK (REQUIRED_FLAG IN (0, 1)),
        CONSTRAINT CK_CONF_FORM_FIELD_VIS CHECK (VISIBILITY IN ('AUTHOR_VISIBLE', 'CHAIR_ONLY', 'REVIEWER_ONLY', 'PUBLIC_SUMMARY'))
      )
    ]'
  );

  create_table_if_missing(
    'REVIEW_FORM_RESPONSE',
    q'[
      CREATE TABLE REVIEW_FORM_RESPONSE (
        RESPONSE_ID NUMBER(19) NOT NULL,
        FORM_ID NUMBER(19) NOT NULL,
        ASSIGNMENT_ID NUMBER(19) NOT NULL,
        REVIEWER_ID NUMBER(19) NOT NULL,
        RESPONSE_STATUS VARCHAR2(30) NOT NULL,
        ANSWERS_JSON CLOB NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        SUBMITTED_AT TIMESTAMP,
        CONSTRAINT PK_REVIEW_FORM_RESPONSE PRIMARY KEY (RESPONSE_ID),
        CONSTRAINT UK_REVIEW_FORM_RESPONSE UNIQUE (FORM_ID, ASSIGNMENT_ID),
        CONSTRAINT CK_REVIEW_FORM_RESPONSE_STATUS CHECK (RESPONSE_STATUS IN ('DRAFT', 'SUBMITTED'))
      )
    ]'
  );

  create_table_if_missing(
    'AUTHOR_FEEDBACK',
    q'[
      CREATE TABLE AUTHOR_FEEDBACK (
        FEEDBACK_ID NUMBER(19) NOT NULL,
        MANUSCRIPT_ID NUMBER(19) NOT NULL,
        SUBMITTED_BY NUMBER(19) NOT NULL,
        FEEDBACK_TYPE VARCHAR2(40) NOT NULL,
        FEEDBACK_TEXT CLOB NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_AUTHOR_FEEDBACK PRIMARY KEY (FEEDBACK_ID),
        CONSTRAINT CK_AUTHOR_FEEDBACK_TYPE CHECK (FEEDBACK_TYPE IN ('REBUTTAL', 'AUTHOR_FEEDBACK', 'REVISION_NOTE'))
      )
    ]'
  );

  create_table_if_missing(
    'PAPER_TAG',
    q'[
      CREATE TABLE PAPER_TAG (
        PAPER_TAG_ID NUMBER(19) NOT NULL,
        CONFERENCE_ID NUMBER(19) NOT NULL,
        MANUSCRIPT_ID NUMBER(19) NOT NULL,
        TAG_NAME VARCHAR2(100) NOT NULL,
        TAG_VALUE VARCHAR2(200),
        CREATED_BY NUMBER(19) NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_PAPER_TAG PRIMARY KEY (PAPER_TAG_ID),
        CONSTRAINT UK_PAPER_TAG UNIQUE (CONFERENCE_ID, MANUSCRIPT_ID, TAG_NAME)
      )
    ]'
  );

  create_table_if_missing(
    'IMPORT_BATCH',
    q'[
      CREATE TABLE IMPORT_BATCH (
        IMPORT_BATCH_ID NUMBER(19) NOT NULL,
        CONFERENCE_ID NUMBER(19) NOT NULL,
        IMPORT_TYPE VARCHAR2(40) NOT NULL,
        SUBMITTED_BY NUMBER(19) NOT NULL,
        BATCH_STATUS VARCHAR2(30) NOT NULL,
        ROW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        VALID_ROW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        ERROR_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
        PREVIEW_JSON CLOB NOT NULL,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        APPLIED_AT TIMESTAMP,
        CONSTRAINT PK_IMPORT_BATCH PRIMARY KEY (IMPORT_BATCH_ID),
        CONSTRAINT CK_IMPORT_BATCH_TYPE CHECK (IMPORT_TYPE IN ('TAGS')),
        CONSTRAINT CK_IMPORT_BATCH_STATUS CHECK (BATCH_STATUS IN ('PREVIEWED', 'APPLIED', 'FAILED'))
      )
    ]'
  );

  create_table_if_missing(
    'PAPER_ROLE_ASSIGNMENT',
    q'[
      CREATE TABLE PAPER_ROLE_ASSIGNMENT (
        PAPER_ROLE_ID NUMBER(19) NOT NULL,
        CONFERENCE_ID NUMBER(19) NOT NULL,
        MANUSCRIPT_ID NUMBER(19) NOT NULL,
        USER_ID NUMBER(19) NOT NULL,
        ROLE_TYPE VARCHAR2(50) NOT NULL,
        ASSIGNED_BY NUMBER(19) NOT NULL,
        ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CONSTRAINT PK_PAPER_ROLE_ASSIGNMENT PRIMARY KEY (PAPER_ROLE_ID),
        CONSTRAINT UK_PAPER_ROLE_ASSIGNMENT UNIQUE (MANUSCRIPT_ID, USER_ID, ROLE_TYPE),
        CONSTRAINT CK_PAPER_ROLE_TYPE CHECK (ROLE_TYPE IN ('PRIMARY_REVIEWER', 'SECONDARY_REVIEWER', 'META_REVIEWER', 'DISCUSSION_LEAD', 'SHEPHERD', 'PROCEEDINGS_EDITOR'))
      )
    ]'
  );

  create_sequence_if_missing('SEQ_CONFERENCE_FORM_DEFINITION', 'CREATE SEQUENCE SEQ_CONFERENCE_FORM_DEFINITION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_CONFERENCE_FORM_FIELD', 'CREATE SEQUENCE SEQ_CONFERENCE_FORM_FIELD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_REVIEW_FORM_RESPONSE', 'CREATE SEQUENCE SEQ_REVIEW_FORM_RESPONSE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_AUTHOR_FEEDBACK', 'CREATE SEQUENCE SEQ_AUTHOR_FEEDBACK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_PAPER_TAG', 'CREATE SEQUENCE SEQ_PAPER_TAG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_IMPORT_BATCH', 'CREATE SEQUENCE SEQ_IMPORT_BATCH START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_PAPER_ROLE_ASSIGNMENT', 'CREATE SEQUENCE SEQ_PAPER_ROLE_ASSIGNMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');

  add_constraint_if_missing('FK_CONF_FORM_CONFERENCE', 'ALTER TABLE CONFERENCE_FORM_DEFINITION ADD CONSTRAINT FK_CONF_FORM_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_CONF_FORM_CREATED_BY', 'ALTER TABLE CONFERENCE_FORM_DEFINITION ADD CONSTRAINT FK_CONF_FORM_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_CONF_FORM_FIELD_FORM', 'ALTER TABLE CONFERENCE_FORM_FIELD ADD CONSTRAINT FK_CONF_FORM_FIELD_FORM FOREIGN KEY (FORM_ID) REFERENCES CONFERENCE_FORM_DEFINITION (FORM_ID)');
  add_constraint_if_missing('FK_REVIEW_FORM_RESPONSE_FORM', 'ALTER TABLE REVIEW_FORM_RESPONSE ADD CONSTRAINT FK_REVIEW_FORM_RESPONSE_FORM FOREIGN KEY (FORM_ID) REFERENCES CONFERENCE_FORM_DEFINITION (FORM_ID)');
  add_constraint_if_missing('FK_REVIEW_FORM_RESPONSE_ASSIGN', 'ALTER TABLE REVIEW_FORM_RESPONSE ADD CONSTRAINT FK_REVIEW_FORM_RESPONSE_ASSIGN FOREIGN KEY (ASSIGNMENT_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID)');
  add_constraint_if_missing('FK_REVIEW_FORM_RESPONSE_USER', 'ALTER TABLE REVIEW_FORM_RESPONSE ADD CONSTRAINT FK_REVIEW_FORM_RESPONSE_USER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_AUTHOR_FEEDBACK_MANUSCRIPT', 'ALTER TABLE AUTHOR_FEEDBACK ADD CONSTRAINT FK_AUTHOR_FEEDBACK_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_AUTHOR_FEEDBACK_SUBMITTED_BY', 'ALTER TABLE AUTHOR_FEEDBACK ADD CONSTRAINT FK_AUTHOR_FEEDBACK_SUBMITTED_BY FOREIGN KEY (SUBMITTED_BY) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_PAPER_TAG_CONFERENCE', 'ALTER TABLE PAPER_TAG ADD CONSTRAINT FK_PAPER_TAG_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_PAPER_TAG_MANUSCRIPT', 'ALTER TABLE PAPER_TAG ADD CONSTRAINT FK_PAPER_TAG_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_PAPER_TAG_CREATED_BY', 'ALTER TABLE PAPER_TAG ADD CONSTRAINT FK_PAPER_TAG_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_IMPORT_BATCH_CONFERENCE', 'ALTER TABLE IMPORT_BATCH ADD CONSTRAINT FK_IMPORT_BATCH_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_IMPORT_BATCH_SUBMITTED_BY', 'ALTER TABLE IMPORT_BATCH ADD CONSTRAINT FK_IMPORT_BATCH_SUBMITTED_BY FOREIGN KEY (SUBMITTED_BY) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_PAPER_ROLE_CONFERENCE', 'ALTER TABLE PAPER_ROLE_ASSIGNMENT ADD CONSTRAINT FK_PAPER_ROLE_CONFERENCE FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_PAPER_ROLE_MANUSCRIPT', 'ALTER TABLE PAPER_ROLE_ASSIGNMENT ADD CONSTRAINT FK_PAPER_ROLE_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_PAPER_ROLE_USER', 'ALTER TABLE PAPER_ROLE_ASSIGNMENT ADD CONSTRAINT FK_PAPER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_PAPER_ROLE_ASSIGNED_BY', 'ALTER TABLE PAPER_ROLE_ASSIGNMENT ADD CONSTRAINT FK_PAPER_ROLE_ASSIGNED_BY FOREIGN KEY (ASSIGNED_BY) REFERENCES SYS_USER (USER_ID)');

  create_index_if_missing('IDX_CONF_FORM_DEFINITION', 'CREATE INDEX IDX_CONF_FORM_DEFINITION ON CONFERENCE_FORM_DEFINITION (CONFERENCE_ID, FORM_TYPE, ACTIVE_FLAG)');
  create_index_if_missing('IDX_CONF_FORM_FIELD', 'CREATE INDEX IDX_CONF_FORM_FIELD ON CONFERENCE_FORM_FIELD (FORM_ID, DISPLAY_ORDER)');
  create_index_if_missing('IDX_REVIEW_FORM_RESPONSE_ASSIGN', 'CREATE INDEX IDX_REVIEW_FORM_RESPONSE_ASSIGN ON REVIEW_FORM_RESPONSE (ASSIGNMENT_ID, RESPONSE_STATUS)');
  create_index_if_missing('IDX_AUTHOR_FEEDBACK_MANUSCRIPT', 'CREATE INDEX IDX_AUTHOR_FEEDBACK_MANUSCRIPT ON AUTHOR_FEEDBACK (MANUSCRIPT_ID, FEEDBACK_TYPE, CREATED_AT)');
  create_index_if_missing('IDX_PAPER_TAG_LOOKUP', 'CREATE INDEX IDX_PAPER_TAG_LOOKUP ON PAPER_TAG (CONFERENCE_ID, TAG_NAME, MANUSCRIPT_ID)');
  create_index_if_missing('IDX_PAPER_TAG_VALUE', 'CREATE INDEX IDX_PAPER_TAG_VALUE ON PAPER_TAG (CONFERENCE_ID, TAG_NAME, TAG_VALUE)');
  create_index_if_missing('IDX_IMPORT_BATCH_CONFERENCE', 'CREATE INDEX IDX_IMPORT_BATCH_CONFERENCE ON IMPORT_BATCH (CONFERENCE_ID, IMPORT_TYPE, CREATED_AT)');
  create_index_if_missing('IDX_PAPER_ROLE_ASSIGNMENT_USER', 'CREATE INDEX IDX_PAPER_ROLE_ASSIGNMENT_USER ON PAPER_ROLE_ASSIGNMENT (CONFERENCE_ID, USER_ID, ROLE_TYPE)');
  create_index_if_missing('IDX_PAPER_ROLE_ASSIGNMENT_MANUSCRIPT', 'CREATE INDEX IDX_PAPER_ROLE_ASSIGNMENT_MANUSCRIPT ON PAPER_ROLE_ASSIGNMENT (MANUSCRIPT_ID, ROLE_TYPE)');
END;
/

CREATE OR REPLACE TRIGGER TRG_CONFERENCE_FORM_DEFINITION_BIU
BEFORE INSERT OR UPDATE ON CONFERENCE_FORM_DEFINITION
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.FORM_ID IS NULL THEN
    :NEW.FORM_ID := SEQ_CONFERENCE_FORM_DEFINITION.NEXTVAL;
  END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONFERENCE_FORM_FIELD_BI
BEFORE INSERT ON CONFERENCE_FORM_FIELD
FOR EACH ROW
BEGIN
  IF :NEW.FIELD_ID IS NULL THEN
    :NEW.FIELD_ID := SEQ_CONFERENCE_FORM_FIELD.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_FORM_RESPONSE_BIU
BEFORE INSERT OR UPDATE ON REVIEW_FORM_RESPONSE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.RESPONSE_ID IS NULL THEN
    :NEW.RESPONSE_ID := SEQ_REVIEW_FORM_RESPONSE.NEXTVAL;
  END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUTHOR_FEEDBACK_BIU
BEFORE INSERT OR UPDATE ON AUTHOR_FEEDBACK
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.FEEDBACK_ID IS NULL THEN
    :NEW.FEEDBACK_ID := SEQ_AUTHOR_FEEDBACK.NEXTVAL;
  END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAPER_TAG_BIU
BEFORE INSERT OR UPDATE ON PAPER_TAG
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.PAPER_TAG_ID IS NULL THEN
    :NEW.PAPER_TAG_ID := SEQ_PAPER_TAG.NEXTVAL;
  END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_IMPORT_BATCH_BI
BEFORE INSERT ON IMPORT_BATCH
FOR EACH ROW
BEGIN
  IF :NEW.IMPORT_BATCH_ID IS NULL THEN
    :NEW.IMPORT_BATCH_ID := SEQ_IMPORT_BATCH.NEXTVAL;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAPER_ROLE_ASSIGNMENT_BI
BEFORE INSERT ON PAPER_ROLE_ASSIGNMENT
FOR EACH ROW
BEGIN
  IF :NEW.PAPER_ROLE_ID IS NULL THEN
    :NEW.PAPER_ROLE_ID := SEQ_PAPER_ROLE_ASSIGNMENT.NEXTVAL;
  END IF;
END;
/
