SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_table_ddl IN CLOB) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_table_ddl;
    END IF;
  END;

  PROCEDURE create_sequence_if_missing(p_sequence_name IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_sequence_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_sequence_name || ' START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
  END;

  PROCEDURE add_constraint_if_missing(p_constraint_name IN VARCHAR2, p_constraint_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_constraint_ddl;
    END IF;
  END;

  PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_index_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_index_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_index_ddl;
    END IF;
  END;
BEGIN
  create_table_if_missing('REVIEWER_INVITATION', q'[
    CREATE TABLE REVIEWER_INVITATION (
      INVITATION_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      REVIEWER_ID NUMBER(19) NOT NULL,
      INVITATION_STATUS VARCHAR2(30) NOT NULL,
      INVITATION_MESSAGE CLOB,
      INVITED_BY NUMBER(19) NOT NULL,
      INVITED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      RESPONDED_AT TIMESTAMP,
      EXPIRES_AT TIMESTAMP,
      CONSTRAINT PK_REVIEWER_INVITATION PRIMARY KEY (INVITATION_ID),
      CONSTRAINT UK_REVIEWER_INVITATION UNIQUE (CONFERENCE_ID, REVIEWER_ID),
      CONSTRAINT CK_REVIEWER_INVITATION_STATUS CHECK (INVITATION_STATUS IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED'))
    )
  ]');

  create_table_if_missing('EXTERNAL_REVIEWER_DELEGATION', q'[
    CREATE TABLE EXTERNAL_REVIEWER_DELEGATION (
      DELEGATION_ID NUMBER(19) NOT NULL,
      ASSIGNMENT_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      REQUESTED_BY NUMBER(19) NOT NULL,
      EXTERNAL_NAME VARCHAR2(200) NOT NULL,
      EXTERNAL_EMAIL VARCHAR2(320) NOT NULL,
      RATIONALE CLOB,
      DELEGATION_STATUS VARCHAR2(30) NOT NULL,
      DECISION_NOTE CLOB,
      DECIDED_BY NUMBER(19),
      REQUESTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      DECIDED_AT TIMESTAMP,
      CONSTRAINT PK_EXTERNAL_REVIEWER_DELEGATION PRIMARY KEY (DELEGATION_ID),
      CONSTRAINT CK_EXTERNAL_DELEGATION_STATUS CHECK (DELEGATION_STATUS IN ('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELLED'))
    )
  ]');

  create_table_if_missing('CONFLICT_RELATIONSHIP', q'[
    CREATE TABLE CONFLICT_RELATIONSHIP (
      CONFLICT_RELATIONSHIP_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      REVIEWER_ID NUMBER(19) NOT NULL,
      CONFLICT_TYPE VARCHAR2(50) NOT NULL,
      CONFLICT_SOURCE VARCHAR2(50) NOT NULL,
      SEVERITY VARCHAR2(20) NOT NULL,
      NOTE CLOB,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_CONFLICT_RELATIONSHIP PRIMARY KEY (CONFLICT_RELATIONSHIP_ID),
      CONSTRAINT UK_CONFLICT_RELATIONSHIP UNIQUE (CONFERENCE_ID, MANUSCRIPT_ID, REVIEWER_ID, CONFLICT_TYPE),
      CONSTRAINT CK_CONFLICT_REL_SEVERITY CHECK (SEVERITY IN ('SOFT', 'HARD')),
      CONSTRAINT CK_CONFLICT_REL_SOURCE CHECK (CONFLICT_SOURCE IN ('MANUAL', 'PROFILE', 'IMPORT', 'BID', 'SYSTEM'))
    )
  ]');

  create_table_if_missing('REVIEWER_MATCHING_SCORE', q'[
    CREATE TABLE REVIEWER_MATCHING_SCORE (
      MATCHING_SCORE_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      REVIEWER_ID NUMBER(19) NOT NULL,
      SCORE_SOURCE VARCHAR2(50) NOT NULL,
      MATCHING_SCORE NUMBER(8,4) NOT NULL,
      RATIONALE CLOB,
      IMPORTED_BY NUMBER(19) NOT NULL,
      IMPORTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_REVIEWER_MATCHING_SCORE PRIMARY KEY (MATCHING_SCORE_ID),
      CONSTRAINT UK_REVIEWER_MATCHING_SCORE UNIQUE (CONFERENCE_ID, MANUSCRIPT_ID, REVIEWER_ID, SCORE_SOURCE)
    )
  ]');

  create_table_if_missing('ASSIGNMENT_PROPOSAL_BUNDLE', q'[
    CREATE TABLE ASSIGNMENT_PROPOSAL_BUNDLE (
      BUNDLE_ID NUMBER(19) NOT NULL,
      ROUND_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      PROPOSAL_NAME VARCHAR2(200) NOT NULL,
      BUNDLE_STATUS VARCHAR2(30) NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_ASSIGNMENT_PROPOSAL_BUNDLE PRIMARY KEY (BUNDLE_ID),
      CONSTRAINT CK_ASSIGNMENT_PROPOSAL_BUNDLE_STATUS CHECK (BUNDLE_STATUS IN ('PROPOSED', 'CONFIRMED', 'SUPERSEDED'))
    )
  ]');

  create_table_if_missing('ASSIGNMENT_PROPOSAL', q'[
    CREATE TABLE ASSIGNMENT_PROPOSAL (
      PROPOSAL_ID NUMBER(19) NOT NULL,
      BUNDLE_ID NUMBER(19) NOT NULL,
      REVIEWER_ID NUMBER(19) NOT NULL,
      RANK_ORDER NUMBER(10) NOT NULL,
      MATCHING_SCORE NUMBER(8,4),
      ELIGIBILITY_STATUS VARCHAR2(30) NOT NULL,
      RATIONALE CLOB,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_ASSIGNMENT_PROPOSAL PRIMARY KEY (PROPOSAL_ID),
      CONSTRAINT UK_ASSIGNMENT_PROPOSAL UNIQUE (BUNDLE_ID, REVIEWER_ID),
      CONSTRAINT CK_ASSIGNMENT_PROPOSAL_ELIG CHECK (ELIGIBILITY_STATUS IN ('ELIGIBLE', 'SOFT_CONFLICT', 'OVERRIDDEN'))
    )
  ]');

  create_table_if_missing('ASSIGNMENT_OVERRIDE_AUDIT', q'[
    CREATE TABLE ASSIGNMENT_OVERRIDE_AUDIT (
      OVERRIDE_ID NUMBER(19) NOT NULL,
      BUNDLE_ID NUMBER(19) NOT NULL,
      REVIEWER_ID NUMBER(19) NOT NULL,
      OVERRIDE_REASON CLOB NOT NULL,
      OVERRIDDEN_BY NUMBER(19) NOT NULL,
      OVERRIDDEN_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_ASSIGNMENT_OVERRIDE_AUDIT PRIMARY KEY (OVERRIDE_ID)
    )
  ]');

  create_sequence_if_missing('SEQ_REVIEWER_INVITATION');
  create_sequence_if_missing('SEQ_EXTERNAL_REVIEWER_DELEGATION');
  create_sequence_if_missing('SEQ_CONFLICT_RELATIONSHIP');
  create_sequence_if_missing('SEQ_REVIEWER_MATCHING_SCORE');
  create_sequence_if_missing('SEQ_ASSIGNMENT_PROPOSAL_BUNDLE');
  create_sequence_if_missing('SEQ_ASSIGNMENT_PROPOSAL');
  create_sequence_if_missing('SEQ_ASSIGNMENT_OVERRIDE_AUDIT');

  add_constraint_if_missing('FK_REVIEWER_INVITATION_CONF', 'ALTER TABLE REVIEWER_INVITATION ADD CONSTRAINT FK_REVIEWER_INVITATION_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_REVIEWER_INVITATION_USER', 'ALTER TABLE REVIEWER_INVITATION ADD CONSTRAINT FK_REVIEWER_INVITATION_USER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_EXT_DELEGATION_ASSIGN', 'ALTER TABLE EXTERNAL_REVIEWER_DELEGATION ADD CONSTRAINT FK_EXT_DELEGATION_ASSIGN FOREIGN KEY (ASSIGNMENT_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID)');
  add_constraint_if_missing('FK_EXT_DELEGATION_MANUSCRIPT', 'ALTER TABLE EXTERNAL_REVIEWER_DELEGATION ADD CONSTRAINT FK_EXT_DELEGATION_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_CONFLICT_REL_MANUSCRIPT', 'ALTER TABLE CONFLICT_RELATIONSHIP ADD CONSTRAINT FK_CONFLICT_REL_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_CONFLICT_REL_REVIEWER', 'ALTER TABLE CONFLICT_RELATIONSHIP ADD CONSTRAINT FK_CONFLICT_REL_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_MATCH_SCORE_MANUSCRIPT', 'ALTER TABLE REVIEWER_MATCHING_SCORE ADD CONSTRAINT FK_MATCH_SCORE_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_PROPOSAL_BUNDLE_ROUND', 'ALTER TABLE ASSIGNMENT_PROPOSAL_BUNDLE ADD CONSTRAINT FK_PROPOSAL_BUNDLE_ROUND FOREIGN KEY (ROUND_ID) REFERENCES REVIEW_ROUND (ROUND_ID)');
  add_constraint_if_missing('FK_PROPOSAL_BUNDLE_MANUSCRIPT', 'ALTER TABLE ASSIGNMENT_PROPOSAL_BUNDLE ADD CONSTRAINT FK_PROPOSAL_BUNDLE_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_ASSIGNMENT_PROPOSAL_BUNDLE', 'ALTER TABLE ASSIGNMENT_PROPOSAL ADD CONSTRAINT FK_ASSIGNMENT_PROPOSAL_BUNDLE FOREIGN KEY (BUNDLE_ID) REFERENCES ASSIGNMENT_PROPOSAL_BUNDLE (BUNDLE_ID)');
  add_constraint_if_missing('FK_ASSIGNMENT_OVERRIDE_BUNDLE', 'ALTER TABLE ASSIGNMENT_OVERRIDE_AUDIT ADD CONSTRAINT FK_ASSIGNMENT_OVERRIDE_BUNDLE FOREIGN KEY (BUNDLE_ID) REFERENCES ASSIGNMENT_PROPOSAL_BUNDLE (BUNDLE_ID)');

  create_index_if_missing('IDX_REVIEWER_INVITATION_STATUS', 'CREATE INDEX IDX_REVIEWER_INVITATION_STATUS ON REVIEWER_INVITATION (CONFERENCE_ID, INVITATION_STATUS, REVIEWER_ID)');
  create_index_if_missing('IDX_EXTERNAL_DELEGATION_ASSIGN', 'CREATE INDEX IDX_EXTERNAL_DELEGATION_ASSIGN ON EXTERNAL_REVIEWER_DELEGATION (ASSIGNMENT_ID, DELEGATION_STATUS)');
  create_index_if_missing('IDX_CONFLICT_REL_SUBJECT', 'CREATE INDEX IDX_CONFLICT_REL_SUBJECT ON CONFLICT_RELATIONSHIP (CONFERENCE_ID, MANUSCRIPT_ID, SEVERITY)');
  create_index_if_missing('IDX_CONFLICT_REL_OBJECT', 'CREATE INDEX IDX_CONFLICT_REL_OBJECT ON CONFLICT_RELATIONSHIP (CONFERENCE_ID, REVIEWER_ID, SEVERITY)');
  create_index_if_missing('IDX_REVIEWER_MATCHING_LOOKUP', 'CREATE INDEX IDX_REVIEWER_MATCHING_LOOKUP ON REVIEWER_MATCHING_SCORE (CONFERENCE_ID, MANUSCRIPT_ID, MATCHING_SCORE)');
  create_index_if_missing('IDX_ASSIGNMENT_PROPOSAL_BUNDLE', 'CREATE INDEX IDX_ASSIGNMENT_PROPOSAL_BUNDLE ON ASSIGNMENT_PROPOSAL_BUNDLE (ROUND_ID, BUNDLE_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_ASSIGNMENT_PROPOSAL_CANDIDATE', 'CREATE INDEX IDX_ASSIGNMENT_PROPOSAL_CANDIDATE ON ASSIGNMENT_PROPOSAL (BUNDLE_ID, RANK_ORDER, REVIEWER_ID)');
  create_index_if_missing('IDX_ASSIGNMENT_OVERRIDE_BUNDLE', 'CREATE INDEX IDX_ASSIGNMENT_OVERRIDE_BUNDLE ON ASSIGNMENT_OVERRIDE_AUDIT (BUNDLE_ID, REVIEWER_ID)');
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEWER_INVITATION_BI
BEFORE INSERT ON REVIEWER_INVITATION
FOR EACH ROW
BEGIN
  IF :NEW.INVITATION_ID IS NULL THEN :NEW.INVITATION_ID := SEQ_REVIEWER_INVITATION.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXTERNAL_DELEGATION_BI
BEFORE INSERT ON EXTERNAL_REVIEWER_DELEGATION
FOR EACH ROW
BEGIN
  IF :NEW.DELEGATION_ID IS NULL THEN :NEW.DELEGATION_ID := SEQ_EXTERNAL_REVIEWER_DELEGATION.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONFLICT_RELATIONSHIP_BI
BEFORE INSERT ON CONFLICT_RELATIONSHIP
FOR EACH ROW
BEGIN
  IF :NEW.CONFLICT_RELATIONSHIP_ID IS NULL THEN :NEW.CONFLICT_RELATIONSHIP_ID := SEQ_CONFLICT_RELATIONSHIP.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEWER_MATCHING_SCORE_BI
BEFORE INSERT ON REVIEWER_MATCHING_SCORE
FOR EACH ROW
BEGIN
  IF :NEW.MATCHING_SCORE_ID IS NULL THEN :NEW.MATCHING_SCORE_ID := SEQ_REVIEWER_MATCHING_SCORE.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ASSIGNMENT_PROPOSAL_BUNDLE_BI
BEFORE INSERT ON ASSIGNMENT_PROPOSAL_BUNDLE
FOR EACH ROW
BEGIN
  IF :NEW.BUNDLE_ID IS NULL THEN :NEW.BUNDLE_ID := SEQ_ASSIGNMENT_PROPOSAL_BUNDLE.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ASSIGNMENT_PROPOSAL_BI
BEFORE INSERT ON ASSIGNMENT_PROPOSAL
FOR EACH ROW
BEGIN
  IF :NEW.PROPOSAL_ID IS NULL THEN :NEW.PROPOSAL_ID := SEQ_ASSIGNMENT_PROPOSAL.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ASSIGNMENT_OVERRIDE_AUDIT_BI
BEFORE INSERT ON ASSIGNMENT_OVERRIDE_AUDIT
FOR EACH ROW
BEGIN
  IF :NEW.OVERRIDE_ID IS NULL THEN :NEW.OVERRIDE_ID := SEQ_ASSIGNMENT_OVERRIDE_AUDIT.NEXTVAL; END IF;
END;
/
