SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_table_ddl IN CLOB) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table_name);
    IF v_count = 0 THEN EXECUTE IMMEDIATE p_table_ddl; END IF;
  END;
  PROCEDURE create_sequence_if_missing(p_sequence_name IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_sequence_name);
    IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_sequence_name || ' START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE'; END IF;
  END;
  PROCEDURE add_constraint_if_missing(p_constraint_name IN VARCHAR2, p_constraint_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);
    IF v_count = 0 THEN EXECUTE IMMEDIATE p_constraint_ddl; END IF;
  END;
  PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_index_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_index_name);
    IF v_count = 0 THEN EXECUTE IMMEDIATE p_index_ddl; END IF;
  END;
BEGIN
  create_table_if_missing('EMAIL_TEMPLATE', q'[
    CREATE TABLE EMAIL_TEMPLATE (
      TEMPLATE_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      TEMPLATE_KEY VARCHAR2(100) NOT NULL,
      ACTIVE_VERSION_ID NUMBER(19),
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_EMAIL_TEMPLATE PRIMARY KEY (TEMPLATE_ID),
      CONSTRAINT UK_EMAIL_TEMPLATE_KEY UNIQUE (CONFERENCE_ID, TEMPLATE_KEY)
    )
  ]');
  create_table_if_missing('EMAIL_TEMPLATE_VERSION', q'[
    CREATE TABLE EMAIL_TEMPLATE_VERSION (
      TEMPLATE_VERSION_ID NUMBER(19) NOT NULL,
      TEMPLATE_ID NUMBER(19) NOT NULL,
      VERSION_NO NUMBER(10) NOT NULL,
      SUBJECT_TEMPLATE VARCHAR2(500) NOT NULL,
      BODY_TEMPLATE CLOB NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_EMAIL_TEMPLATE_VERSION PRIMARY KEY (TEMPLATE_VERSION_ID),
      CONSTRAINT UK_EMAIL_TEMPLATE_VERSION UNIQUE (TEMPLATE_ID, VERSION_NO)
    )
  ]');
  create_table_if_missing('OUTBOUND_EMAIL_HISTORY', q'[
    CREATE TABLE OUTBOUND_EMAIL_HISTORY (
      EMAIL_HISTORY_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      TEMPLATE_ID NUMBER(19) NOT NULL,
      TEMPLATE_VERSION_ID NUMBER(19) NOT NULL,
      RECIPIENT_EMAIL VARCHAR2(320) NOT NULL,
      SUBJECT_TEXT VARCHAR2(500) NOT NULL,
      BODY_TEXT CLOB NOT NULL,
      DELIVERY_STATUS VARCHAR2(30) NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_OUTBOUND_EMAIL_HISTORY PRIMARY KEY (EMAIL_HISTORY_ID),
      CONSTRAINT CK_OUTBOUND_EMAIL_STATUS CHECK (DELIVERY_STATUS IN ('RECORDED', 'QUEUED', 'SENT', 'FAILED'))
    )
  ]');
  create_table_if_missing('OFFLINE_REVIEW_IMPORT_BATCH', q'[
    CREATE TABLE OFFLINE_REVIEW_IMPORT_BATCH (
      BATCH_ID NUMBER(19) NOT NULL,
      ASSIGNMENT_ID NUMBER(19) NOT NULL,
      REVIEWER_ID NUMBER(19) NOT NULL,
      BATCH_STATUS VARCHAR2(30) NOT NULL,
      ROW_COUNT NUMBER(10) NOT NULL,
      VALID_ROW_COUNT NUMBER(10) NOT NULL,
      ERROR_COUNT NUMBER(10) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      APPLIED_AT TIMESTAMP,
      CONSTRAINT PK_OFFLINE_REVIEW_IMPORT_BATCH PRIMARY KEY (BATCH_ID),
      CONSTRAINT CK_OFFLINE_REVIEW_BATCH_STATUS CHECK (BATCH_STATUS IN ('PREVIEWED', 'APPLIED', 'FAILED'))
    )
  ]');
  create_table_if_missing('OFFLINE_REVIEW_IMPORT_ROW', q'[
    CREATE TABLE OFFLINE_REVIEW_IMPORT_ROW (
      ROW_ID NUMBER(19) NOT NULL,
      BATCH_ID NUMBER(19) NOT NULL,
      ROW_NO NUMBER(10) NOT NULL,
      ROW_STATUS VARCHAR2(30) NOT NULL,
      OVERALL_SCORE NUMBER(3),
      RECOMMENDATION VARCHAR2(50),
      COMMENTS_TO_AUTHOR CLOB,
      ERROR_MESSAGE VARCHAR2(500),
      CONSTRAINT PK_OFFLINE_REVIEW_IMPORT_ROW PRIMARY KEY (ROW_ID),
      CONSTRAINT CK_OFFLINE_REVIEW_ROW_STATUS CHECK (ROW_STATUS IN ('VALID', 'ERROR', 'APPLIED'))
    )
  ]');
  create_table_if_missing('CAMERA_READY_FILE', q'[
    CREATE TABLE CAMERA_READY_FILE (
      CAMERA_READY_FILE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      VERSION_ID NUMBER(19) NOT NULL,
      SUBMITTED_BY NUMBER(19) NOT NULL,
      FILE_NAME VARCHAR2(255) NOT NULL,
      FILE_SIZE NUMBER(19) NOT NULL,
      CHECKSUM_SHA256 VARCHAR2(128) NOT NULL,
      COPYRIGHT_CONFIRMED NUMBER(1) NOT NULL,
      LICENSE_TYPE VARCHAR2(80),
      FILE_STATUS VARCHAR2(30) NOT NULL,
      DECISION_NOTE CLOB,
      SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      DECIDED_AT TIMESTAMP,
      CONSTRAINT PK_CAMERA_READY_FILE PRIMARY KEY (CAMERA_READY_FILE_ID),
      CONSTRAINT CK_CAMERA_READY_FILE_STATUS CHECK (FILE_STATUS IN ('SUBMITTED', 'ACCEPTED', 'REJECTED')),
      CONSTRAINT CK_CAMERA_READY_FILE_COPYRIGHT CHECK (COPYRIGHT_CONFIRMED IN (0, 1))
    )
  ]');
  create_table_if_missing('PUBLICATION_METADATA', q'[
    CREATE TABLE PUBLICATION_METADATA (
      PUBLICATION_METADATA_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      DOI VARCHAR2(200),
      INDEX_KEYWORDS VARCHAR2(1000),
      PUBLICATION_STATUS VARCHAR2(40) NOT NULL,
      UPDATED_BY NUMBER(19) NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_PUBLICATION_METADATA PRIMARY KEY (PUBLICATION_METADATA_ID),
      CONSTRAINT UK_PUBLICATION_METADATA_MANUSCRIPT UNIQUE (MANUSCRIPT_ID),
      CONSTRAINT CK_PUBLICATION_METADATA_STATUS CHECK (PUBLICATION_STATUS IN ('DRAFT', 'READY_FOR_PROCEEDINGS', 'EXPORTED', 'PUBLISHED'))
    )
  ]');
  create_table_if_missing('PROCEEDINGS_EXPORT_BATCH', q'[
    CREATE TABLE PROCEEDINGS_EXPORT_BATCH (
      EXPORT_BATCH_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      EXPORT_NAME VARCHAR2(200) NOT NULL,
      EXPORT_STATUS VARCHAR2(30) NOT NULL,
      PAPER_COUNT NUMBER(10) NOT NULL,
      PREVIEW_JSON CLOB NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_PROCEEDINGS_EXPORT_BATCH PRIMARY KEY (EXPORT_BATCH_ID),
      CONSTRAINT CK_PROCEEDINGS_EXPORT_STATUS CHECK (EXPORT_STATUS IN ('PREVIEWED', 'EXPORTED', 'FAILED'))
    )
  ]');

  create_sequence_if_missing('SEQ_EMAIL_TEMPLATE');
  create_sequence_if_missing('SEQ_EMAIL_TEMPLATE_VERSION');
  create_sequence_if_missing('SEQ_OUTBOUND_EMAIL_HISTORY');
  create_sequence_if_missing('SEQ_OFFLINE_REVIEW_IMPORT_BATCH');
  create_sequence_if_missing('SEQ_OFFLINE_REVIEW_IMPORT_ROW');
  create_sequence_if_missing('SEQ_CAMERA_READY_FILE');
  create_sequence_if_missing('SEQ_PUBLICATION_METADATA');
  create_sequence_if_missing('SEQ_PROCEEDINGS_EXPORT_BATCH');

  add_constraint_if_missing('FK_EMAIL_TEMPLATE_CONF', 'ALTER TABLE EMAIL_TEMPLATE ADD CONSTRAINT FK_EMAIL_TEMPLATE_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_EMAIL_TEMPLATE_VERSION_TEMPLATE', 'ALTER TABLE EMAIL_TEMPLATE_VERSION ADD CONSTRAINT FK_EMAIL_TEMPLATE_VERSION_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES EMAIL_TEMPLATE (TEMPLATE_ID)');
  add_constraint_if_missing('FK_EMAIL_TEMPLATE_ACTIVE_VERSION', 'ALTER TABLE EMAIL_TEMPLATE ADD CONSTRAINT FK_EMAIL_TEMPLATE_ACTIVE_VERSION FOREIGN KEY (ACTIVE_VERSION_ID) REFERENCES EMAIL_TEMPLATE_VERSION (TEMPLATE_VERSION_ID)');
  add_constraint_if_missing('FK_OUTBOUND_EMAIL_TEMPLATE', 'ALTER TABLE OUTBOUND_EMAIL_HISTORY ADD CONSTRAINT FK_OUTBOUND_EMAIL_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES EMAIL_TEMPLATE (TEMPLATE_ID)');
  add_constraint_if_missing('FK_OUTBOUND_EMAIL_VERSION', 'ALTER TABLE OUTBOUND_EMAIL_HISTORY ADD CONSTRAINT FK_OUTBOUND_EMAIL_VERSION FOREIGN KEY (TEMPLATE_VERSION_ID) REFERENCES EMAIL_TEMPLATE_VERSION (TEMPLATE_VERSION_ID)');
  add_constraint_if_missing('FK_OFFLINE_REVIEW_BATCH_ASSIGN', 'ALTER TABLE OFFLINE_REVIEW_IMPORT_BATCH ADD CONSTRAINT FK_OFFLINE_REVIEW_BATCH_ASSIGN FOREIGN KEY (ASSIGNMENT_ID) REFERENCES REVIEW_ASSIGNMENT (ASSIGNMENT_ID)');
  add_constraint_if_missing('FK_OFFLINE_REVIEW_ROW_BATCH', 'ALTER TABLE OFFLINE_REVIEW_IMPORT_ROW ADD CONSTRAINT FK_OFFLINE_REVIEW_ROW_BATCH FOREIGN KEY (BATCH_ID) REFERENCES OFFLINE_REVIEW_IMPORT_BATCH (BATCH_ID)');
  add_constraint_if_missing('FK_CAMERA_READY_FILE_MANUSCRIPT', 'ALTER TABLE CAMERA_READY_FILE ADD CONSTRAINT FK_CAMERA_READY_FILE_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_PUBLICATION_METADATA_MANUSCRIPT', 'ALTER TABLE PUBLICATION_METADATA ADD CONSTRAINT FK_PUBLICATION_METADATA_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_PROCEEDINGS_EXPORT_CONF', 'ALTER TABLE PROCEEDINGS_EXPORT_BATCH ADD CONSTRAINT FK_PROCEEDINGS_EXPORT_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');

  create_index_if_missing('IDX_EMAIL_TEMPLATE_KEY', 'CREATE INDEX IDX_EMAIL_TEMPLATE_KEY ON EMAIL_TEMPLATE (CONFERENCE_ID, TEMPLATE_KEY, TEMPLATE_ID)');
  create_index_if_missing('IDX_EMAIL_TEMPLATE_VERSION', 'CREATE INDEX IDX_EMAIL_TEMPLATE_VERSION ON EMAIL_TEMPLATE_VERSION (TEMPLATE_ID, VERSION_NO, TEMPLATE_VERSION_ID)');
  create_index_if_missing('IDX_OUTBOUND_EMAIL_STATUS', 'CREATE INDEX IDX_OUTBOUND_EMAIL_STATUS ON OUTBOUND_EMAIL_HISTORY (CONFERENCE_ID, DELIVERY_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_OFFLINE_REVIEW_BATCH', 'CREATE INDEX IDX_OFFLINE_REVIEW_BATCH ON OFFLINE_REVIEW_IMPORT_BATCH (ASSIGNMENT_ID, BATCH_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_OFFLINE_REVIEW_ROW', 'CREATE INDEX IDX_OFFLINE_REVIEW_ROW ON OFFLINE_REVIEW_IMPORT_ROW (BATCH_ID, ROW_STATUS)');
  create_index_if_missing('IDX_CAMERA_READY_FILE_STATUS', 'CREATE INDEX IDX_CAMERA_READY_FILE_STATUS ON CAMERA_READY_FILE (MANUSCRIPT_ID, FILE_STATUS, SUBMITTED_AT)');
  create_index_if_missing('IDX_PUBLICATION_METADATA_STATUS', 'CREATE INDEX IDX_PUBLICATION_METADATA_STATUS ON PUBLICATION_METADATA (CONFERENCE_ID, PUBLICATION_STATUS, UPDATED_AT)');
  create_index_if_missing('IDX_PROCEEDINGS_EXPORT_STATUS', 'CREATE INDEX IDX_PROCEEDINGS_EXPORT_STATUS ON PROCEEDINGS_EXPORT_BATCH (CONFERENCE_ID, EXPORT_STATUS, CREATED_AT)');
END;
/

CREATE OR REPLACE TRIGGER TRG_EMAIL_TEMPLATE_BI BEFORE INSERT ON EMAIL_TEMPLATE FOR EACH ROW
BEGIN IF :NEW.TEMPLATE_ID IS NULL THEN :NEW.TEMPLATE_ID := SEQ_EMAIL_TEMPLATE.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_EMAIL_TEMPLATE_VERSION_BI BEFORE INSERT ON EMAIL_TEMPLATE_VERSION FOR EACH ROW
BEGIN IF :NEW.TEMPLATE_VERSION_ID IS NULL THEN :NEW.TEMPLATE_VERSION_ID := SEQ_EMAIL_TEMPLATE_VERSION.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_OUTBOUND_EMAIL_HISTORY_BI BEFORE INSERT ON OUTBOUND_EMAIL_HISTORY FOR EACH ROW
BEGIN IF :NEW.EMAIL_HISTORY_ID IS NULL THEN :NEW.EMAIL_HISTORY_ID := SEQ_OUTBOUND_EMAIL_HISTORY.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_OFFLINE_REVIEW_BATCH_BI BEFORE INSERT ON OFFLINE_REVIEW_IMPORT_BATCH FOR EACH ROW
BEGIN IF :NEW.BATCH_ID IS NULL THEN :NEW.BATCH_ID := SEQ_OFFLINE_REVIEW_IMPORT_BATCH.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_OFFLINE_REVIEW_ROW_BI BEFORE INSERT ON OFFLINE_REVIEW_IMPORT_ROW FOR EACH ROW
BEGIN IF :NEW.ROW_ID IS NULL THEN :NEW.ROW_ID := SEQ_OFFLINE_REVIEW_IMPORT_ROW.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_CAMERA_READY_FILE_BI BEFORE INSERT ON CAMERA_READY_FILE FOR EACH ROW
BEGIN IF :NEW.CAMERA_READY_FILE_ID IS NULL THEN :NEW.CAMERA_READY_FILE_ID := SEQ_CAMERA_READY_FILE.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PUBLICATION_METADATA_BI BEFORE INSERT ON PUBLICATION_METADATA FOR EACH ROW
BEGIN IF :NEW.PUBLICATION_METADATA_ID IS NULL THEN :NEW.PUBLICATION_METADATA_ID := SEQ_PUBLICATION_METADATA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PROCEEDINGS_EXPORT_BATCH_BI BEFORE INSERT ON PROCEEDINGS_EXPORT_BATCH FOR EACH ROW
BEGIN IF :NEW.EXPORT_BATCH_ID IS NULL THEN :NEW.EXPORT_BATCH_ID := SEQ_PROCEEDINGS_EXPORT_BATCH.NEXTVAL; END IF; END;
/
