SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  v_count NUMBER;

  PROCEDURE drop_constraint_if_exists(p_constraint_name IN VARCHAR2) IS
    v_constraint_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_constraint_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);
    IF v_constraint_count > 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE IMPORT_BATCH DROP CONSTRAINT ' || p_constraint_name;
    END IF;
  END;
BEGIN
  drop_constraint_if_exists('CK_IMPORT_BATCH_TYPE');
  EXECUTE IMMEDIATE q'[
    ALTER TABLE IMPORT_BATCH ADD CONSTRAINT CK_IMPORT_BATCH_TYPE
      CHECK (IMPORT_TYPE IN ('TAGS', 'REVIEWER_INVITATIONS', 'MATCHING_SCORES'))
  ]';

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_IMPORT_BATCH_TYPE_STATUS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_IMPORT_BATCH_TYPE_STATUS ON IMPORT_BATCH (IMPORT_TYPE, BATCH_STATUS, CREATED_AT)';
  END IF;
END;
/
