SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_table_ddl IN CLOB) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_table_ddl;
    END IF;
  END;

  PROCEDURE create_sequence_if_missing(p_sequence_name IN VARCHAR2, p_sequence_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_sequence_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_sequence_ddl;
    END IF;
  END;

  PROCEDURE add_column_if_missing(p_table_name IN VARCHAR2, p_column_name IN VARCHAR2, p_column_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_table_name)
       AND COLUMN_NAME = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_column_ddl;
    END IF;
  END;

  PROCEDURE add_constraint_if_missing(p_constraint_name IN VARCHAR2, p_constraint_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_constraint_ddl;
    END IF;
  END;

  PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_index_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_index_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_index_ddl;
    END IF;
  END;
BEGIN
  add_column_if_missing('CONFERENCE_PHASE', 'REBUTTAL_OPEN_AT',
    'ALTER TABLE CONFERENCE_PHASE ADD REBUTTAL_OPEN_AT TIMESTAMP');
  add_column_if_missing('CONFERENCE_PHASE', 'REBUTTAL_CLOSE_AT',
    'ALTER TABLE CONFERENCE_PHASE ADD REBUTTAL_CLOSE_AT TIMESTAMP');
  add_column_if_missing('CONFERENCE_PHASE', 'CAMERA_READY_OPEN_AT',
    'ALTER TABLE CONFERENCE_PHASE ADD CAMERA_READY_OPEN_AT TIMESTAMP');
  add_column_if_missing('CONFERENCE_PHASE', 'CAMERA_READY_CLOSE_AT',
    'ALTER TABLE CONFERENCE_PHASE ADD CAMERA_READY_CLOSE_AT TIMESTAMP');

  create_table_if_missing('WORKFLOW_FORM_RESPONSE', q'[
    CREATE TABLE WORKFLOW_FORM_RESPONSE (
      RESPONSE_ID NUMBER(19) NOT NULL,
      FORM_ID NUMBER(19) NOT NULL,
      SUBJECT_TYPE VARCHAR2(40) NOT NULL,
      SUBJECT_ID NUMBER(19) NOT NULL,
      SUBMITTED_BY NUMBER(19) NOT NULL,
      RESPONSE_STATUS VARCHAR2(30) NOT NULL,
      ANSWERS_JSON CLOB NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      SUBMITTED_AT TIMESTAMP,
      CONSTRAINT PK_WORKFLOW_FORM_RESPONSE PRIMARY KEY (RESPONSE_ID),
      CONSTRAINT UK_WORKFLOW_FORM_RESPONSE UNIQUE (FORM_ID, SUBJECT_TYPE, SUBJECT_ID),
      CONSTRAINT CK_WORKFLOW_FORM_SUBJECT CHECK (SUBJECT_TYPE IN ('MANUSCRIPT')),
      CONSTRAINT CK_WORKFLOW_FORM_STATUS CHECK (RESPONSE_STATUS IN ('DRAFT', 'SUBMITTED'))
    )
  ]');

  create_table_if_missing('REVIEW_FORM_RESPONSE_REVISION', q'[
    CREATE TABLE REVIEW_FORM_RESPONSE_REVISION (
      REVISION_ID NUMBER(19) NOT NULL,
      RESPONSE_ID NUMBER(19) NOT NULL,
      REVISION_NO NUMBER(10) NOT NULL,
      ANSWERS_JSON CLOB NOT NULL,
      SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_REVIEW_FORM_RESPONSE_REV PRIMARY KEY (REVISION_ID),
      CONSTRAINT UK_REVIEW_FORM_RESPONSE_REV UNIQUE (RESPONSE_ID, REVISION_NO)
    )
  ]');

  create_sequence_if_missing('SEQ_WORKFLOW_FORM_RESPONSE', 'CREATE SEQUENCE SEQ_WORKFLOW_FORM_RESPONSE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');
  create_sequence_if_missing('SEQ_REVIEW_FORM_RESPONSE_REV', 'CREATE SEQUENCE SEQ_REVIEW_FORM_RESPONSE_REV START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE');

  add_constraint_if_missing('FK_WORKFLOW_FORM_RESPONSE_FORM',
    'ALTER TABLE WORKFLOW_FORM_RESPONSE ADD CONSTRAINT FK_WORKFLOW_FORM_RESPONSE_FORM FOREIGN KEY (FORM_ID) REFERENCES CONFERENCE_FORM_DEFINITION (FORM_ID)');
  add_constraint_if_missing('FK_WORKFLOW_FORM_RESPONSE_USER',
    'ALTER TABLE WORKFLOW_FORM_RESPONSE ADD CONSTRAINT FK_WORKFLOW_FORM_RESPONSE_USER FOREIGN KEY (SUBMITTED_BY) REFERENCES SYS_USER (USER_ID)');
  add_constraint_if_missing('FK_REVIEW_FORM_REV_RESPONSE',
    'ALTER TABLE REVIEW_FORM_RESPONSE_REVISION ADD CONSTRAINT FK_REVIEW_FORM_REV_RESPONSE FOREIGN KEY (RESPONSE_ID) REFERENCES REVIEW_FORM_RESPONSE (RESPONSE_ID)');

  create_index_if_missing('IDX_WORKFLOW_FORM_RESPONSE_SUBJ',
    'CREATE INDEX IDX_WORKFLOW_FORM_RESPONSE_SUBJ ON WORKFLOW_FORM_RESPONSE (SUBJECT_TYPE, SUBJECT_ID, RESPONSE_STATUS)');
  create_index_if_missing('IDX_CONFERENCE_PHASE_REBUTTAL',
    'CREATE INDEX IDX_CONFERENCE_PHASE_REBUTTAL ON CONFERENCE_PHASE (CONFERENCE_ID, REBUTTAL_OPEN_AT, REBUTTAL_CLOSE_AT)');
  create_index_if_missing('IDX_CONFERENCE_PHASE_CAMERA_READY',
    'CREATE INDEX IDX_CONFERENCE_PHASE_CAMERA_READY ON CONFERENCE_PHASE (CONFERENCE_ID, CAMERA_READY_OPEN_AT, CAMERA_READY_CLOSE_AT)');
END;
/

CREATE OR REPLACE TRIGGER TRG_WORKFLOW_FORM_RESPONSE_BIU
BEFORE INSERT OR UPDATE ON WORKFLOW_FORM_RESPONSE
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.RESPONSE_ID IS NULL THEN
    :NEW.RESPONSE_ID := SEQ_WORKFLOW_FORM_RESPONSE.NEXTVAL;
  END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEW_FORM_RESPONSE_REV_BI
BEFORE INSERT ON REVIEW_FORM_RESPONSE_REVISION
FOR EACH ROW
BEGIN
  IF :NEW.REVISION_ID IS NULL THEN
    :NEW.REVISION_ID := SEQ_REVIEW_FORM_RESPONSE_REV.NEXTVAL;
  END IF;
END;
/
