SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  PROCEDURE create_table_if_missing(p_table_name IN VARCHAR2, p_table_ddl IN CLOB) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_table_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_table_ddl;
    END IF;
  END;

  PROCEDURE create_sequence_if_missing(p_sequence_name IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_sequence_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_sequence_name || ' START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    END IF;
  END;

  PROCEDURE add_constraint_if_missing(p_constraint_name IN VARCHAR2, p_constraint_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_constraint_ddl;
    END IF;
  END;

  PROCEDURE create_index_if_missing(p_index_name IN VARCHAR2, p_index_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = UPPER(p_index_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_index_ddl;
    END IF;
  END;
BEGIN
  create_table_if_missing('WORKBENCH_SAVED_FILTER', q'[
    CREATE TABLE WORKBENCH_SAVED_FILTER (
      SAVED_FILTER_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      FILTER_SCOPE VARCHAR2(40) NOT NULL,
      FILTER_NAME VARCHAR2(120) NOT NULL,
      FILTER_FORMULA VARCHAR2(1000) NOT NULL,
      FILTER_JSON CLOB NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_WORKBENCH_SAVED_FILTER PRIMARY KEY (SAVED_FILTER_ID),
      CONSTRAINT UK_WORKBENCH_SAVED_FILTER UNIQUE (CONFERENCE_ID, FILTER_SCOPE, FILTER_NAME),
      CONSTRAINT CK_WORKBENCH_FILTER_SCOPE CHECK (FILTER_SCOPE IN ('ASSIGNMENT', 'PUBLICATION', 'COMMUNICATION', 'PAPER'))
    )
  ]');

  create_table_if_missing('WORKBENCH_EXPORT_BATCH', q'[
    CREATE TABLE WORKBENCH_EXPORT_BATCH (
      EXPORT_BATCH_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      EXPORT_SCOPE VARCHAR2(40) NOT NULL,
      EXPORT_FORMAT VARCHAR2(20) NOT NULL,
      EXPORT_STATUS VARCHAR2(30) NOT NULL,
      FILTER_JSON CLOB,
      FILE_NAME VARCHAR2(255) NOT NULL,
      FILE_MIME_TYPE VARCHAR2(120) NOT NULL,
      ROW_COUNT NUMBER(10) NOT NULL,
      FILE_BYTES CLOB NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      GENERATED_AT TIMESTAMP,
      CONSTRAINT PK_WORKBENCH_EXPORT_BATCH PRIMARY KEY (EXPORT_BATCH_ID),
      CONSTRAINT CK_WORKBENCH_EXPORT_SCOPE CHECK (EXPORT_SCOPE IN ('PAPERS', 'USERS', 'CONFLICTS', 'PREFERENCES', 'ASSIGNMENTS', 'DECISIONS', 'TAGS')),
      CONSTRAINT CK_WORKBENCH_EXPORT_FORMAT CHECK (EXPORT_FORMAT IN ('CSV', 'JSON')),
      CONSTRAINT CK_WORKBENCH_EXPORT_STATUS CHECK (EXPORT_STATUS IN ('GENERATED', 'DOWNLOADED', 'FAILED'))
    )
  ]');

  create_table_if_missing('BULK_OPERATION_BATCH', q'[
    CREATE TABLE BULK_OPERATION_BATCH (
      BULK_BATCH_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      OPERATION_TYPE VARCHAR2(50) NOT NULL,
      BATCH_STATUS VARCHAR2(30) NOT NULL,
      PREVIEW_JSON CLOB NOT NULL,
      ROW_COUNT NUMBER(10) NOT NULL,
      VALID_ROW_COUNT NUMBER(10) NOT NULL,
      ERROR_COUNT NUMBER(10) NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      APPLIED_AT TIMESTAMP,
      CONSTRAINT PK_BULK_OPERATION_BATCH PRIMARY KEY (BULK_BATCH_ID),
      CONSTRAINT CK_BULK_OPERATION_TYPE CHECK (OPERATION_TYPE IN ('DECISIONS', 'USERS', 'CONFLICTS', 'PREFERENCES', 'PAPER_STATUS', 'ASSIGNMENTS')),
      CONSTRAINT CK_BULK_OPERATION_STATUS CHECK (BATCH_STATUS IN ('PREVIEWED', 'APPLIED', 'FAILED'))
    )
  ]');

  create_table_if_missing('BULK_OPERATION_ROW', q'[
    CREATE TABLE BULK_OPERATION_ROW (
      BULK_ROW_ID NUMBER(19) NOT NULL,
      BULK_BATCH_ID NUMBER(19) NOT NULL,
      ROW_NO NUMBER(10) NOT NULL,
      ROW_STATUS VARCHAR2(30) NOT NULL,
      SUBJECT_TYPE VARCHAR2(50),
      SUBJECT_ID NUMBER(19),
      ROW_PAYLOAD_JSON CLOB NOT NULL,
      ERROR_MESSAGE VARCHAR2(500),
      APPLIED_AT TIMESTAMP,
      CONSTRAINT PK_BULK_OPERATION_ROW PRIMARY KEY (BULK_ROW_ID),
      CONSTRAINT CK_BULK_OPERATION_ROW_STATUS CHECK (ROW_STATUS IN ('VALID', 'ERROR', 'APPLIED', 'SKIPPED'))
    )
  ]');

  create_table_if_missing('ASSIGNMENT_PROPOSAL_CONTEXT', q'[
    CREATE TABLE ASSIGNMENT_PROPOSAL_CONTEXT (
      CONTEXT_ID NUMBER(19) NOT NULL,
      BUNDLE_ID NUMBER(19) NOT NULL,
      PROPOSAL_ID NUMBER(19),
      REVIEWER_ID NUMBER(19) NOT NULL,
      SUBJECT_AREAS_JSON CLOB NOT NULL,
      BID_SUMMARY_JSON CLOB NOT NULL,
      CONFLICT_SUMMARY_JSON CLOB NOT NULL,
      LOAD_SUMMARY_JSON CLOB NOT NULL,
      AGENT_CONTEXT_JSON CLOB NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_ASSIGNMENT_PROPOSAL_CONTEXT PRIMARY KEY (CONTEXT_ID)
    )
  ]');

  create_table_if_missing('STORED_FILE', q'[
    CREATE TABLE STORED_FILE (
      STORED_FILE_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19),
      FILE_PURPOSE VARCHAR2(60) NOT NULL,
      FILE_NAME VARCHAR2(255) NOT NULL,
      CONTENT_TYPE VARCHAR2(120) NOT NULL,
      FILE_SIZE NUMBER(19) NOT NULL,
      CHECKSUM_SHA256 VARCHAR2(128) NOT NULL,
      STORAGE_STATUS VARCHAR2(30) NOT NULL,
      FILE_BYTES CLOB NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_STORED_FILE PRIMARY KEY (STORED_FILE_ID),
      CONSTRAINT CK_STORED_FILE_PURPOSE CHECK (FILE_PURPOSE IN ('CAMERA_READY', 'SUPPLEMENTARY', 'PROCEEDINGS', 'EXPORT', 'OFFLINE_REVIEW')),
      CONSTRAINT CK_STORED_FILE_STATUS CHECK (STORAGE_STATUS IN ('AVAILABLE', 'REPLACED', 'DELETED'))
    )
  ]');

  create_table_if_missing('PROCEEDINGS_EXPORT_FILE', q'[
    CREATE TABLE PROCEEDINGS_EXPORT_FILE (
      PROCEEDINGS_FILE_ID NUMBER(19) NOT NULL,
      EXPORT_BATCH_ID NUMBER(19) NOT NULL,
      STORED_FILE_ID NUMBER(19) NOT NULL,
      FILE_KIND VARCHAR2(40) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT PK_PROCEEDINGS_EXPORT_FILE PRIMARY KEY (PROCEEDINGS_FILE_ID),
      CONSTRAINT CK_PROCEEDINGS_FILE_KIND CHECK (FILE_KIND IN ('MANIFEST_JSON', 'PAPERS_CSV', 'INDEX_JSON'))
    )
  ]');

  create_table_if_missing('DOI_INDEX_ADAPTER_SUBMISSION', q'[
    CREATE TABLE DOI_INDEX_ADAPTER_SUBMISSION (
      ADAPTER_SUBMISSION_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      MANUSCRIPT_ID NUMBER(19) NOT NULL,
      PUBLICATION_METADATA_ID NUMBER(19) NOT NULL,
      ADAPTER_TYPE VARCHAR2(40) NOT NULL,
      ADAPTER_STATUS VARCHAR2(30) NOT NULL,
      REQUEST_JSON CLOB NOT NULL,
      RESPONSE_JSON CLOB,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      SUBMITTED_AT TIMESTAMP,
      CONSTRAINT PK_DOI_INDEX_ADAPTER_SUB PRIMARY KEY (ADAPTER_SUBMISSION_ID),
      CONSTRAINT CK_DOI_INDEX_ADAPTER_TYPE CHECK (ADAPTER_TYPE IN ('DOI', 'INDEX')),
      CONSTRAINT CK_DOI_INDEX_ADAPTER_STATUS CHECK (ADAPTER_STATUS IN ('PREVIEWED', 'SUBMITTED', 'RECORDED', 'FAILED'))
    )
  ]');

  create_table_if_missing('COMMUNICATION_COMPOSE_BATCH', q'[
    CREATE TABLE COMMUNICATION_COMPOSE_BATCH (
      COMPOSE_BATCH_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      TEMPLATE_ID NUMBER(19),
      COMPOSE_SCOPE VARCHAR2(50) NOT NULL,
      SUBJECT_TEXT VARCHAR2(500) NOT NULL,
      BODY_TEXT CLOB NOT NULL,
      RECIPIENT_FILTER_JSON CLOB NOT NULL,
      RECIPIENT_COUNT NUMBER(10) NOT NULL,
      DELIVERY_STATUS VARCHAR2(30) NOT NULL,
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      SENT_AT TIMESTAMP,
      CONSTRAINT PK_COMMUNICATION_COMPOSE_BATCH PRIMARY KEY (COMPOSE_BATCH_ID),
      CONSTRAINT CK_COMM_COMPOSE_SCOPE CHECK (COMPOSE_SCOPE IN ('AUTHORS', 'REVIEWERS', 'CHAIRS', 'CUSTOM')),
      CONSTRAINT CK_COMM_COMPOSE_STATUS CHECK (DELIVERY_STATUS IN ('PREVIEWED', 'RECORDED', 'SENT', 'FAILED'))
    )
  ]');

  create_table_if_missing('COMMUNICATION_REMINDER', q'[
    CREATE TABLE COMMUNICATION_REMINDER (
      REMINDER_ID NUMBER(19) NOT NULL,
      CONFERENCE_ID NUMBER(19) NOT NULL,
      REMINDER_TYPE VARCHAR2(50) NOT NULL,
      TARGET_STATUS VARCHAR2(50),
      SCHEDULED_FOR TIMESTAMP NOT NULL,
      REMINDER_STATUS VARCHAR2(30) NOT NULL,
      COMPOSE_BATCH_ID NUMBER(19),
      CREATED_BY NUMBER(19) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      SENT_AT TIMESTAMP,
      CONSTRAINT PK_COMMUNICATION_REMINDER PRIMARY KEY (REMINDER_ID),
      CONSTRAINT CK_COMM_REMINDER_TYPE CHECK (REMINDER_TYPE IN ('REVIEW_DUE', 'CAMERA_READY_DUE', 'BID_DUE', 'DECISION_NOTICE', 'CUSTOM')),
      CONSTRAINT CK_COMM_REMINDER_STATUS CHECK (REMINDER_STATUS IN ('SCHEDULED', 'RECORDED', 'SENT', 'CANCELLED', 'FAILED'))
    )
  ]');

  create_sequence_if_missing('SEQ_WORKBENCH_SAVED_FILTER');
  create_sequence_if_missing('SEQ_WORKBENCH_EXPORT_BATCH');
  create_sequence_if_missing('SEQ_BULK_OPERATION_BATCH');
  create_sequence_if_missing('SEQ_BULK_OPERATION_ROW');
  create_sequence_if_missing('SEQ_ASSIGNMENT_PROPOSAL_CONTEXT');
  create_sequence_if_missing('SEQ_STORED_FILE');
  create_sequence_if_missing('SEQ_PROCEEDINGS_EXPORT_FILE');
  create_sequence_if_missing('SEQ_DOI_INDEX_ADAPTER_SUB');
  create_sequence_if_missing('SEQ_COMMUNICATION_COMPOSE_BATCH');
  create_sequence_if_missing('SEQ_COMMUNICATION_REMINDER');

  add_constraint_if_missing('FK_WORKBENCH_FILTER_CONF', 'ALTER TABLE WORKBENCH_SAVED_FILTER ADD CONSTRAINT FK_WORKBENCH_FILTER_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_WORKBENCH_EXPORT_CONF', 'ALTER TABLE WORKBENCH_EXPORT_BATCH ADD CONSTRAINT FK_WORKBENCH_EXPORT_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_BULK_OPERATION_CONF', 'ALTER TABLE BULK_OPERATION_BATCH ADD CONSTRAINT FK_BULK_OPERATION_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_BULK_OPERATION_ROW_BATCH', 'ALTER TABLE BULK_OPERATION_ROW ADD CONSTRAINT FK_BULK_OPERATION_ROW_BATCH FOREIGN KEY (BULK_BATCH_ID) REFERENCES BULK_OPERATION_BATCH (BULK_BATCH_ID)');
  add_constraint_if_missing('FK_PROPOSAL_CONTEXT_BUNDLE', 'ALTER TABLE ASSIGNMENT_PROPOSAL_CONTEXT ADD CONSTRAINT FK_PROPOSAL_CONTEXT_BUNDLE FOREIGN KEY (BUNDLE_ID) REFERENCES ASSIGNMENT_PROPOSAL_BUNDLE (BUNDLE_ID)');
  add_constraint_if_missing('FK_PROPOSAL_CONTEXT_PROPOSAL', 'ALTER TABLE ASSIGNMENT_PROPOSAL_CONTEXT ADD CONSTRAINT FK_PROPOSAL_CONTEXT_PROPOSAL FOREIGN KEY (PROPOSAL_ID) REFERENCES ASSIGNMENT_PROPOSAL (PROPOSAL_ID)');
  add_constraint_if_missing('FK_STORED_FILE_CONF', 'ALTER TABLE STORED_FILE ADD CONSTRAINT FK_STORED_FILE_CONF FOREIGN KEY (CONFERENCE_ID) REFERENCES CONFERENCE (CONFERENCE_ID)');
  add_constraint_if_missing('FK_STORED_FILE_MANUSCRIPT', 'ALTER TABLE STORED_FILE ADD CONSTRAINT FK_STORED_FILE_MANUSCRIPT FOREIGN KEY (MANUSCRIPT_ID) REFERENCES MANUSCRIPT (MANUSCRIPT_ID)');
  add_constraint_if_missing('FK_PROCEEDINGS_FILE_EXPORT', 'ALTER TABLE PROCEEDINGS_EXPORT_FILE ADD CONSTRAINT FK_PROCEEDINGS_FILE_EXPORT FOREIGN KEY (EXPORT_BATCH_ID) REFERENCES PROCEEDINGS_EXPORT_BATCH (EXPORT_BATCH_ID)');
  add_constraint_if_missing('FK_PROCEEDINGS_FILE_STORED', 'ALTER TABLE PROCEEDINGS_EXPORT_FILE ADD CONSTRAINT FK_PROCEEDINGS_FILE_STORED FOREIGN KEY (STORED_FILE_ID) REFERENCES STORED_FILE (STORED_FILE_ID)');
  add_constraint_if_missing('FK_DOI_INDEX_METADATA', 'ALTER TABLE DOI_INDEX_ADAPTER_SUBMISSION ADD CONSTRAINT FK_DOI_INDEX_METADATA FOREIGN KEY (PUBLICATION_METADATA_ID) REFERENCES PUBLICATION_METADATA (PUBLICATION_METADATA_ID)');
  add_constraint_if_missing('FK_COMM_COMPOSE_TEMPLATE', 'ALTER TABLE COMMUNICATION_COMPOSE_BATCH ADD CONSTRAINT FK_COMM_COMPOSE_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES EMAIL_TEMPLATE (TEMPLATE_ID)');
  add_constraint_if_missing('FK_COMM_REMINDER_COMPOSE', 'ALTER TABLE COMMUNICATION_REMINDER ADD CONSTRAINT FK_COMM_REMINDER_COMPOSE FOREIGN KEY (COMPOSE_BATCH_ID) REFERENCES COMMUNICATION_COMPOSE_BATCH (COMPOSE_BATCH_ID)');

  create_index_if_missing('IDX_WORKBENCH_FILTER_SCOPE', 'CREATE INDEX IDX_WORKBENCH_FILTER_SCOPE ON WORKBENCH_SAVED_FILTER (CONFERENCE_ID, FILTER_SCOPE, UPDATED_AT)');
  create_index_if_missing('IDX_WORKBENCH_EXPORT_STATUS', 'CREATE INDEX IDX_WORKBENCH_EXPORT_STATUS ON WORKBENCH_EXPORT_BATCH (CONFERENCE_ID, EXPORT_SCOPE, EXPORT_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_BULK_OPERATION_STATUS', 'CREATE INDEX IDX_BULK_OPERATION_STATUS ON BULK_OPERATION_BATCH (CONFERENCE_ID, OPERATION_TYPE, BATCH_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_BULK_OPERATION_ROW_BATCH', 'CREATE INDEX IDX_BULK_OPERATION_ROW_BATCH ON BULK_OPERATION_ROW (BULK_BATCH_ID, ROW_STATUS, ROW_NO)');
  create_index_if_missing('IDX_PROPOSAL_CONTEXT_BUNDLE', 'CREATE INDEX IDX_PROPOSAL_CONTEXT_BUNDLE ON ASSIGNMENT_PROPOSAL_CONTEXT (BUNDLE_ID, REVIEWER_ID)');
  create_index_if_missing('IDX_STORED_FILE_LOOKUP', 'CREATE INDEX IDX_STORED_FILE_LOOKUP ON STORED_FILE (CONFERENCE_ID, MANUSCRIPT_ID, FILE_PURPOSE, STORAGE_STATUS)');
  create_index_if_missing('IDX_PROCEEDINGS_FILE_EXPORT', 'CREATE INDEX IDX_PROCEEDINGS_FILE_EXPORT ON PROCEEDINGS_EXPORT_FILE (EXPORT_BATCH_ID, FILE_KIND)');
  create_index_if_missing('IDX_DOI_INDEX_STATUS', 'CREATE INDEX IDX_DOI_INDEX_STATUS ON DOI_INDEX_ADAPTER_SUBMISSION (CONFERENCE_ID, ADAPTER_TYPE, ADAPTER_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_COMM_COMPOSE_STATUS', 'CREATE INDEX IDX_COMM_COMPOSE_STATUS ON COMMUNICATION_COMPOSE_BATCH (CONFERENCE_ID, COMPOSE_SCOPE, DELIVERY_STATUS, CREATED_AT)');
  create_index_if_missing('IDX_COMM_REMINDER_STATUS', 'CREATE INDEX IDX_COMM_REMINDER_STATUS ON COMMUNICATION_REMINDER (CONFERENCE_ID, REMINDER_TYPE, REMINDER_STATUS, SCHEDULED_FOR)');
END;
/

CREATE OR REPLACE TRIGGER TRG_WORKBENCH_SAVED_FILTER_BIU
BEFORE INSERT OR UPDATE ON WORKBENCH_SAVED_FILTER
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.SAVED_FILTER_ID IS NULL THEN :NEW.SAVED_FILTER_ID := SEQ_WORKBENCH_SAVED_FILTER.NEXTVAL; END IF;
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_WORKBENCH_EXPORT_BATCH_BI
BEFORE INSERT ON WORKBENCH_EXPORT_BATCH
FOR EACH ROW
BEGIN
  IF :NEW.EXPORT_BATCH_ID IS NULL THEN :NEW.EXPORT_BATCH_ID := SEQ_WORKBENCH_EXPORT_BATCH.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BULK_OPERATION_BATCH_BI
BEFORE INSERT ON BULK_OPERATION_BATCH
FOR EACH ROW
BEGIN
  IF :NEW.BULK_BATCH_ID IS NULL THEN :NEW.BULK_BATCH_ID := SEQ_BULK_OPERATION_BATCH.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BULK_OPERATION_ROW_BI
BEFORE INSERT ON BULK_OPERATION_ROW
FOR EACH ROW
BEGIN
  IF :NEW.BULK_ROW_ID IS NULL THEN :NEW.BULK_ROW_ID := SEQ_BULK_OPERATION_ROW.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ASSIGNMENT_PROPOSAL_CTX_BI
BEFORE INSERT ON ASSIGNMENT_PROPOSAL_CONTEXT
FOR EACH ROW
BEGIN
  IF :NEW.CONTEXT_ID IS NULL THEN :NEW.CONTEXT_ID := SEQ_ASSIGNMENT_PROPOSAL_CONTEXT.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_STORED_FILE_BI
BEFORE INSERT ON STORED_FILE
FOR EACH ROW
BEGIN
  IF :NEW.STORED_FILE_ID IS NULL THEN :NEW.STORED_FILE_ID := SEQ_STORED_FILE.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PROCEEDINGS_EXPORT_FILE_BI
BEFORE INSERT ON PROCEEDINGS_EXPORT_FILE
FOR EACH ROW
BEGIN
  IF :NEW.PROCEEDINGS_FILE_ID IS NULL THEN :NEW.PROCEEDINGS_FILE_ID := SEQ_PROCEEDINGS_EXPORT_FILE.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_DOI_INDEX_ADAPTER_SUB_BI
BEFORE INSERT ON DOI_INDEX_ADAPTER_SUBMISSION
FOR EACH ROW
BEGIN
  IF :NEW.ADAPTER_SUBMISSION_ID IS NULL THEN :NEW.ADAPTER_SUBMISSION_ID := SEQ_DOI_INDEX_ADAPTER_SUB.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_COMM_COMPOSE_BATCH_BI
BEFORE INSERT ON COMMUNICATION_COMPOSE_BATCH
FOR EACH ROW
BEGIN
  IF :NEW.COMPOSE_BATCH_ID IS NULL THEN :NEW.COMPOSE_BATCH_ID := SEQ_COMMUNICATION_COMPOSE_BATCH.NEXTVAL; END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_COMMUNICATION_REMINDER_BI
BEFORE INSERT ON COMMUNICATION_REMINDER
FOR EACH ROW
BEGIN
  IF :NEW.REMINDER_ID IS NULL THEN :NEW.REMINDER_ID := SEQ_COMMUNICATION_REMINDER.NEXTVAL; END IF;
END;
/
