SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

UPDATE CONFERENCE
SET CFP_PUBLISHED = 1,
    UPDATED_AT = CURRENT_TIMESTAMP
WHERE PUBLIC_SLUG = 'legacy-platform-default'
  AND CFP_PUBLISHED <> 1;

