SET DEFINE OFF;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  FUNCTION column_exists(p_table_name VARCHAR2, p_column_name VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = UPPER(p_table_name)
       AND COLUMN_NAME = UPPER(p_column_name);
    RETURN v_count = 1;
  END;

  FUNCTION index_exists(p_index_name VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = UPPER(p_index_name);
    RETURN v_count = 1;
  END;

  PROCEDURE drop_constraint_if_exists(p_table_name VARCHAR2, p_constraint_name VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_CONSTRAINTS
     WHERE TABLE_NAME = UPPER(p_table_name)
       AND CONSTRAINT_NAME = UPPER(p_constraint_name);
    IF v_count = 1 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table_name || ' DROP CONSTRAINT ' || p_constraint_name;
    END IF;
  END;
BEGIN
  IF NOT column_exists('CONFERENCE_PHASE', 'ABSTRACT_SUBMISSION_CLOSE_AT') THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CONFERENCE_PHASE ADD (ABSTRACT_SUBMISSION_CLOSE_AT TIMESTAMP)';
  END IF;

  EXECUTE IMMEDIATE q'[
    UPDATE CONFERENCE_PHASE
    SET ABSTRACT_SUBMISSION_CLOSE_AT = SUBMISSION_CLOSE_AT - INTERVAL '1' SECOND
    WHERE ABSTRACT_SUBMISSION_CLOSE_AT IS NULL
  ]';

  EXECUTE IMMEDIATE 'ALTER TABLE CONFERENCE_PHASE MODIFY (ABSTRACT_SUBMISSION_CLOSE_AT TIMESTAMP NOT NULL)';

  drop_constraint_if_exists('CONFERENCE_PHASE', 'CK_CONFERENCE_PHASE_ORDER');
  EXECUTE IMMEDIATE q'[
    ALTER TABLE CONFERENCE_PHASE
      ADD CONSTRAINT CK_CONFERENCE_PHASE_ORDER CHECK (
        SUBMISSION_OPEN_AT < ABSTRACT_SUBMISSION_CLOSE_AT
        AND ABSTRACT_SUBMISSION_CLOSE_AT < SUBMISSION_CLOSE_AT
        AND SUBMISSION_CLOSE_AT < BIDDING_OPEN_AT
        AND BIDDING_OPEN_AT < BIDDING_CLOSE_AT
        AND BIDDING_CLOSE_AT < REVIEW_DEADLINE_AT
        AND REVIEW_DEADLINE_AT < DECISION_RELEASE_AT
      )
  ]';

  IF NOT index_exists('IDX_CONFERENCE_PHASE_ABSTRACT_CLOSE') THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_CONFERENCE_PHASE_ABSTRACT_CLOSE ON CONFERENCE_PHASE (ABSTRACT_SUBMISSION_CLOSE_AT, CONFERENCE_ID)';
  END IF;

  drop_constraint_if_exists('MANUSCRIPT', 'CK_MANUSCRIPT_STATUS');
  EXECUTE IMMEDIATE q'[
    ALTER TABLE MANUSCRIPT
      ADD CONSTRAINT CK_MANUSCRIPT_STATUS CHECK (
        CURRENT_STATUS IN (
          'ABSTRACT_SUBMITTED',
          'DRAFT',
          'SUBMITTED',
          'UNDER_SCREENING',
          'DESK_REJECTED',
          'UNDER_REVIEW',
          'REVISION_REQUIRED',
          'REVISED_SUBMITTED',
          'ACCEPTED',
          'REJECTED'
        )
      )
  ]';
END;
/
