SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  v_table_count NUMBER;
  v_sequence_count NUMBER;
  v_trigger_count NUMBER;
  v_procedure_count NUMBER;
  v_index_count NUMBER;
  v_role_count NUMBER;
  v_invalid_count NUMBER;
  v_error_count NUMBER;
  v_execution_job_attempt_count_column NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_table_count
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'SYS_USER',
     'SYS_ROLE',
     'SYS_USER_ROLE',
     'USER_RESEARCH_AREA',
     'USER_ACADEMIC_PROFILE',
     'ROLE_APPLICATION',
     'EMAIL_VERIFICATION_TOKEN',
     'MANUSCRIPT',
     'MANUSCRIPT_VERSION',
     'MANUSCRIPT_AUTHOR',
     'REVIEW_ROUND',
     'REVIEW_ASSIGNMENT',
     'CONFLICT_CHECK_RECORD',
     'REVIEW_REPORT',
     'DECISION_RECORD',
     'ANALYSIS_INTENT',
     'ANALYSIS_PROJECTION',
     'ANALYSIS_OUTBOX',
     'ANALYSIS_INBOX',
     'EXECUTION_JOB',
     'EXECUTION_ATTEMPT',
     'EXECUTION_ARTIFACT',
     'EXECUTION_OUTBOX',
     'EXECUTION_INBOX',
     'SYS_NOTIFICATION',
     'AUDIT_LOG'
   );

  SELECT COUNT(*)
    INTO v_sequence_count
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME IN (
     'SEQ_SYS_USER',
     'SEQ_SYS_ROLE',
     'SEQ_SYS_USER_ROLE',
     'SEQ_USER_RESEARCH_AREA',
     'SEQ_USER_ACADEMIC_PROFILE',
     'SEQ_ROLE_APPLICATION',
     'SEQ_EMAIL_VERIFICATION_TOKEN',
     'SEQ_MANUSCRIPT',
     'SEQ_MANUSCRIPT_VERSION',
     'SEQ_MANUSCRIPT_AUTHOR',
     'SEQ_REVIEW_ROUND',
     'SEQ_REVIEW_ASSIGNMENT',
     'SEQ_CONFLICT_CHECK_RECORD',
     'SEQ_REVIEW_REPORT',
     'SEQ_DECISION_RECORD',
     'SEQ_ANALYSIS_INTENT',
     'SEQ_ANALYSIS_PROJECTION',
     'SEQ_ANALYSIS_OUTBOX',
     'SEQ_ANALYSIS_INBOX',
     'SEQ_EXECUTION_ATTEMPT',
     'SEQ_EXECUTION_ARTIFACT',
     'SEQ_EXECUTION_OUTBOX',
     'SEQ_EXECUTION_INBOX',
     'SEQ_SYS_NOTIFICATION',
     'SEQ_AUDIT_LOG'
   );

  SELECT COUNT(*)
    INTO v_trigger_count
    FROM USER_TRIGGERS
   WHERE TRIGGER_NAME IN (
     'TRG_SYS_USER_BI',
     'TRG_SYS_ROLE_BI',
     'TRG_SYS_USER_ROLE_BI',
     'TRG_USER_RESEARCH_AREA_BI',
     'TRG_USER_ACADEMIC_PROFILE_BI',
     'TRG_ROLE_APPLICATION_BI',
     'TRG_EMAIL_VERIFICATION_TOKEN_BI',
     'TRG_MANUSCRIPT_BI',
     'TRG_MANUSCRIPT_VERSION_BI',
     'TRG_MANUSCRIPT_AUTHOR_BI',
     'TRG_REVIEW_ROUND_BI',
     'TRG_REVIEW_ASSIGNMENT_BI',
     'TRG_CONFLICT_CHECK_RECORD_BI',
     'TRG_REVIEW_REPORT_BI',
     'TRG_DECISION_RECORD_BI',
     'TRG_ANALYSIS_INTENT_BI',
     'TRG_ANALYSIS_PROJECTION_BI',
     'TRG_ANALYSIS_PROJECTION_BU',
     'TRG_ANALYSIS_OUTBOX_BI',
     'TRG_ANALYSIS_INBOX_BI',
     'TRG_EXECUTION_ATTEMPT_BI',
     'TRG_EXECUTION_ARTIFACT_BI',
     'TRG_EXECUTION_OUTBOX_BI',
     'TRG_EXECUTION_INBOX_BI',
     'TRG_EXECUTION_JOB_BU',
     'TRG_SYS_NOTIFICATION_BI',
     'TRG_AUDIT_LOG_BIU',
     'TRG_MANUSCRIPT_AUDIT_TRACE_AU'
   );

  SELECT COUNT(*)
    INTO v_index_count
    FROM USER_INDEXES
   WHERE INDEX_NAME IN (
     'IDX_SYS_USER_STATUS',
     'IDX_SYS_USER_ROLE_ROLE',
     'IDX_ROLE_APPLICATION_STATUS_TYPE',
     'IDX_EMAIL_VERIFICATION_USER_APP',
     'IDX_EMAIL_VERIFICATION_EXPIRES',
     'IDX_EMAIL_VERIFICATION_USER_PURPOSE',
     'IDX_MANUSCRIPT_SUBMITTER',
     'IDX_MANUSCRIPT_STATUS',
     'IDX_MANUSCRIPT_VERSION_SUBMITTED_BY',
     'IDX_REVIEW_ROUND_VERSION',
     'IDX_REVIEW_ASSIGNMENT_REVIEWER_STATUS',
     'IDX_CONFLICT_CHECK_ASSIGNMENT',
     'IDX_REVIEW_REPORT_MANUSCRIPT',
     'IDX_REVIEW_REPORT_REVIEWER',
     'IDX_DECISION_RECORD_MANUSCRIPT',
     'IDX_SYS_NOTIFICATION_RECEIVER_READ',
     'IDX_AUDIT_LOG_OPERATOR_CREATED',
     'IDX_ANALYSIS_INTENT_REQUESTED_BY_STATUS',
     'IDX_ANALYSIS_INTENT_ANCHOR_LOOKUP',
     'IDX_ANALYSIS_PROJECTION_STATUS_UPDATED',
     'IDX_ANALYSIS_OUTBOX_INTENT',
     'IDX_ANALYSIS_OUTBOX_STATUS_CREATED',
     'IDX_ANALYSIS_INBOX_INTENT',
     'IDX_ANALYSIS_INBOX_STATUS_RECEIVED',
     'IDX_EXECUTION_JOB_STATE_UPDATED',
     'IDX_EXECUTION_ATTEMPT_JOB',
     'IDX_EXECUTION_ARTIFACT_JOB',
     'IDX_EXECUTION_OUTBOX_JOB',
     'IDX_EXECUTION_OUTBOX_STATUS_CREATED',
     'IDX_EXECUTION_INBOX_JOB',
     'IDX_EXECUTION_INBOX_STATUS_RECEIVED',
     'IDX_REVIEW_ROUND_STATUS_ID',
     'IDX_REVIEW_ASSIGNMENT_ROUND_ID',
     'IDX_REVIEW_ASSIGNMENT_ACCESS',
     'IDX_REVIEW_REPORT_ROUND',
     'IDX_CONFLICT_CHECK_MANUSCRIPT_REVIEWER',
     'IDX_MANUSCRIPT_STATUS_SUBMITTED',
     'IDX_ANALYSIS_PROJECTION_UPDATED'
   );

  SELECT COUNT(*)
    INTO v_procedure_count
    FROM USER_OBJECTS
   WHERE OBJECT_TYPE = 'PROCEDURE'
     AND OBJECT_NAME IN (
       'PRC_REVIEW_COMPLETION_STATS',
       'PRC_REVIEW_WORKLOAD_SUMMARY'
     );

  SELECT COUNT(*)
    INTO v_invalid_count
    FROM USER_OBJECTS
   WHERE OBJECT_TYPE IN ('TRIGGER', 'PROCEDURE')
     AND OBJECT_NAME IN (
       'TRG_SYS_USER_BI',
       'TRG_SYS_ROLE_BI',
       'TRG_SYS_USER_ROLE_BI',
       'TRG_USER_RESEARCH_AREA_BI',
       'TRG_USER_ACADEMIC_PROFILE_BI',
       'TRG_ROLE_APPLICATION_BI',
       'TRG_EMAIL_VERIFICATION_TOKEN_BI',
       'TRG_MANUSCRIPT_BI',
       'TRG_MANUSCRIPT_VERSION_BI',
       'TRG_MANUSCRIPT_AUTHOR_BI',
       'TRG_REVIEW_ROUND_BI',
       'TRG_REVIEW_ASSIGNMENT_BI',
       'TRG_CONFLICT_CHECK_RECORD_BI',
       'TRG_REVIEW_REPORT_BI',
       'TRG_DECISION_RECORD_BI',
       'TRG_ANALYSIS_INTENT_BI',
       'TRG_ANALYSIS_PROJECTION_BI',
       'TRG_ANALYSIS_PROJECTION_BU',
       'TRG_ANALYSIS_OUTBOX_BI',
       'TRG_ANALYSIS_INBOX_BI',
       'TRG_EXECUTION_ATTEMPT_BI',
       'TRG_EXECUTION_ARTIFACT_BI',
       'TRG_EXECUTION_OUTBOX_BI',
       'TRG_EXECUTION_INBOX_BI',
       'TRG_EXECUTION_JOB_BU',
       'TRG_SYS_NOTIFICATION_BI',
       'TRG_AUDIT_LOG_BIU',
       'TRG_MANUSCRIPT_AUDIT_TRACE_AU',
       'PRC_REVIEW_COMPLETION_STATS',
       'PRC_REVIEW_WORKLOAD_SUMMARY'
     )
     AND STATUS <> 'VALID';

  SELECT COUNT(*)
    INTO v_error_count
    FROM USER_ERRORS
   WHERE NAME IN (
     'TRG_SYS_USER_BI',
     'TRG_SYS_ROLE_BI',
     'TRG_SYS_USER_ROLE_BI',
     'TRG_USER_RESEARCH_AREA_BI',
     'TRG_USER_ACADEMIC_PROFILE_BI',
     'TRG_ROLE_APPLICATION_BI',
     'TRG_EMAIL_VERIFICATION_TOKEN_BI',
     'TRG_MANUSCRIPT_BI',
     'TRG_MANUSCRIPT_VERSION_BI',
     'TRG_MANUSCRIPT_AUTHOR_BI',
     'TRG_REVIEW_ROUND_BI',
     'TRG_REVIEW_ASSIGNMENT_BI',
     'TRG_CONFLICT_CHECK_RECORD_BI',
     'TRG_REVIEW_REPORT_BI',
     'TRG_DECISION_RECORD_BI',
     'TRG_ANALYSIS_INTENT_BI',
     'TRG_ANALYSIS_PROJECTION_BI',
     'TRG_ANALYSIS_PROJECTION_BU',
     'TRG_ANALYSIS_OUTBOX_BI',
     'TRG_ANALYSIS_INBOX_BI',
     'TRG_EXECUTION_ATTEMPT_BI',
     'TRG_EXECUTION_ARTIFACT_BI',
     'TRG_EXECUTION_OUTBOX_BI',
     'TRG_EXECUTION_INBOX_BI',
     'TRG_EXECUTION_JOB_BU',
     'TRG_SYS_NOTIFICATION_BI',
     'TRG_AUDIT_LOG_BIU',
     'TRG_MANUSCRIPT_AUDIT_TRACE_AU',
     'PRC_REVIEW_COMPLETION_STATS',
     'PRC_REVIEW_WORKLOAD_SUMMARY'
   );

  SELECT COUNT(*)
    INTO v_role_count
    FROM SYS_ROLE;

  SELECT COUNT(*)
    INTO v_execution_job_attempt_count_column
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EXECUTION_JOB'
     AND COLUMN_NAME = 'ATTEMPT_COUNT';

  IF v_table_count <> 26 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Expected 26 tables, found ' || v_table_count);
  END IF;

  IF v_sequence_count <> 25 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Expected 25 sequences, found ' || v_sequence_count);
  END IF;

  IF v_trigger_count <> 28 THEN
    RAISE_APPLICATION_ERROR(-20003, 'Expected 28 triggers, found ' || v_trigger_count);
  END IF;

  IF v_procedure_count <> 2 THEN
    RAISE_APPLICATION_ERROR(-20004, 'Expected 2 procedures, found ' || v_procedure_count);
  END IF;

  IF v_index_count <> 38 THEN
    RAISE_APPLICATION_ERROR(-20005, 'Expected 38 indexes, found ' || v_index_count);
  END IF;

  IF v_role_count <> 4 THEN
    RAISE_APPLICATION_ERROR(-20006, 'Expected 4 role seeds, found ' || v_role_count);
  END IF;

  IF v_execution_job_attempt_count_column <> 1 THEN
    RAISE_APPLICATION_ERROR(-20009, 'Expected EXECUTION_JOB.ATTEMPT_COUNT column to exist');
  END IF;

  IF v_invalid_count <> 0 THEN
    RAISE_APPLICATION_ERROR(-20007, 'Expected all verified triggers/procedures to be VALID, found ' || v_invalid_count || ' invalid object(s)');
  END IF;

  IF v_error_count <> 0 THEN
    RAISE_APPLICATION_ERROR(-20008, 'Expected no USER_ERRORS rows for verified objects, found ' || v_error_count);
  END IF;

  DBMS_OUTPUT.PUT_LINE('Schema verification passed.');
END;
/
