SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
  v_table_count NUMBER;
  v_sequence_count NUMBER;
  v_trigger_count NUMBER;
  v_procedure_count NUMBER;
  v_index_count NUMBER;
  v_role_count NUMBER;
  v_invalid_count NUMBER;
  v_error_count NUMBER;
  v_execution_job_attempt_count_column NUMBER;
  v_execution_job_governance_columns NUMBER;
  v_manuscript_conference_column NUMBER;
  v_manuscript_conference_fk NUMBER;
  v_assignment_assist_type_constraints NUMBER;
  v_business_operations_tables NUMBER;
  v_real_platform_wave6_wave7_tables NUMBER;
  v_assignment_coi_maturity_tables NUMBER;
  v_publication_communication_maturity_tables NUMBER;
  v_wave8_wave9_slice_b_constraint NUMBER;
  v_wave3_wave6_full_closure_objects NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_table_count
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'SYS_USER',
     'SYS_ROLE',
     'SYS_USER_ROLE',
     'USER_RESEARCH_AREA',
     'USER_ACADEMIC_PROFILE',
     'ROLE_APPLICATION',
     'EMAIL_VERIFICATION_TOKEN',
     'CONFERENCE',
     'CONFERENCE_PHASE',
     'CONFERENCE_REVIEWER',
     'REVIEWER_BID',
     'REVIEW_DISCUSSION_MESSAGE',
     'CAMERA_READY_SUBMISSION',
     'COMMUNICATION_LOG',
     'MANUSCRIPT',
     'MANUSCRIPT_VERSION',
     'MANUSCRIPT_AUTHOR',
     'REVIEW_ROUND',
     'ASSIGNMENT_DRAFT',
     'REVIEW_ASSIGNMENT',
     'CONFLICT_CHECK_RECORD',
     'REVIEW_REPORT',
     'DECISION_RECORD',
     'ANALYSIS_INTENT',
     'ANALYSIS_PROJECTION',
     'ANALYSIS_OUTBOX',
     'ANALYSIS_INBOX',
     'EXECUTION_JOB',
     'EXECUTION_ATTEMPT',
     'EXECUTION_ARTIFACT',
     'EXECUTION_OUTBOX',
     'EXECUTION_INBOX',
     'SYS_NOTIFICATION',
     'AUDIT_LOG',
     'CONFERENCE_FORM_DEFINITION',
     'CONFERENCE_FORM_FIELD',
     'REVIEW_FORM_RESPONSE',
     'AUTHOR_FEEDBACK',
     'PAPER_TAG',
     'IMPORT_BATCH',
     'PAPER_ROLE_ASSIGNMENT',
     'REVIEWER_INVITATION',
     'EXTERNAL_REVIEWER_DELEGATION',
     'CONFLICT_RELATIONSHIP',
     'REVIEWER_MATCHING_SCORE',
     'ASSIGNMENT_PROPOSAL_BUNDLE',
     'ASSIGNMENT_PROPOSAL',
     'ASSIGNMENT_OVERRIDE_AUDIT',
     'EMAIL_TEMPLATE',
     'EMAIL_TEMPLATE_VERSION',
     'OUTBOUND_EMAIL_HISTORY',
     'OFFLINE_REVIEW_IMPORT_BATCH',
     'OFFLINE_REVIEW_IMPORT_ROW',
     'CAMERA_READY_FILE',
     'PUBLICATION_METADATA',
     'PROCEEDINGS_EXPORT_BATCH',
     'WORKFLOW_FORM_RESPONSE',
     'REVIEW_FORM_RESPONSE_REVISION'
   );

  SELECT COUNT(*)
    INTO v_sequence_count
    FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME IN (
     'SEQ_SYS_USER',
     'SEQ_SYS_ROLE',
     'SEQ_SYS_USER_ROLE',
     'SEQ_USER_RESEARCH_AREA',
     'SEQ_USER_ACADEMIC_PROFILE',
     'SEQ_ROLE_APPLICATION',
     'SEQ_EMAIL_VERIFICATION_TOKEN',
     'SEQ_CONFERENCE',
     'SEQ_CONFERENCE_PHASE',
     'SEQ_CONFERENCE_REVIEWER',
     'SEQ_REVIEWER_BID',
     'SEQ_REVIEW_DISCUSSION_MESSAGE',
     'SEQ_CAMERA_READY_SUBMISSION',
     'SEQ_COMMUNICATION_LOG',
     'SEQ_MANUSCRIPT',
     'SEQ_MANUSCRIPT_VERSION',
     'SEQ_MANUSCRIPT_AUTHOR',
     'SEQ_REVIEW_ROUND',
     'SEQ_ASSIGNMENT_DRAFT',
     'SEQ_REVIEW_ASSIGNMENT',
     'SEQ_CONFLICT_CHECK_RECORD',
     'SEQ_REVIEW_REPORT',
     'SEQ_DECISION_RECORD',
     'SEQ_ANALYSIS_INTENT',
     'SEQ_ANALYSIS_PROJECTION',
     'SEQ_ANALYSIS_OUTBOX',
     'SEQ_ANALYSIS_INBOX',
     'SEQ_EXECUTION_ATTEMPT',
     'SEQ_EXECUTION_ARTIFACT',
     'SEQ_EXECUTION_OUTBOX',
     'SEQ_EXECUTION_INBOX',
     'SEQ_SYS_NOTIFICATION',
     'SEQ_AUDIT_LOG',
     'SEQ_CONFERENCE_FORM_DEFINITION',
     'SEQ_CONFERENCE_FORM_FIELD',
     'SEQ_REVIEW_FORM_RESPONSE',
     'SEQ_AUTHOR_FEEDBACK',
     'SEQ_PAPER_TAG',
     'SEQ_IMPORT_BATCH',
     'SEQ_PAPER_ROLE_ASSIGNMENT',
     'SEQ_REVIEWER_INVITATION',
     'SEQ_EXTERNAL_REVIEWER_DELEGATION',
     'SEQ_CONFLICT_RELATIONSHIP',
     'SEQ_REVIEWER_MATCHING_SCORE',
     'SEQ_ASSIGNMENT_PROPOSAL_BUNDLE',
     'SEQ_ASSIGNMENT_PROPOSAL',
     'SEQ_ASSIGNMENT_OVERRIDE_AUDIT',
     'SEQ_EMAIL_TEMPLATE',
     'SEQ_EMAIL_TEMPLATE_VERSION',
     'SEQ_OUTBOUND_EMAIL_HISTORY',
     'SEQ_OFFLINE_REVIEW_IMPORT_BATCH',
     'SEQ_OFFLINE_REVIEW_IMPORT_ROW',
     'SEQ_CAMERA_READY_FILE',
     'SEQ_PUBLICATION_METADATA',
     'SEQ_PROCEEDINGS_EXPORT_BATCH',
     'SEQ_WORKFLOW_FORM_RESPONSE',
     'SEQ_REVIEW_FORM_RESPONSE_REV'
   );

  SELECT COUNT(*)
    INTO v_trigger_count
    FROM USER_TRIGGERS
   WHERE TRIGGER_NAME IN (
     'TRG_SYS_USER_BI',
     'TRG_SYS_ROLE_BI',
     'TRG_SYS_USER_ROLE_BI',
     'TRG_USER_RESEARCH_AREA_BI',
     'TRG_USER_ACADEMIC_PROFILE_BI',
     'TRG_ROLE_APPLICATION_BI',
     'TRG_EMAIL_VERIFICATION_TOKEN_BI',
     'TRG_CONFERENCE_BI',
     'TRG_CONFERENCE_PHASE_BI',
     'TRG_CONFERENCE_REVIEWER_BI',
     'TRG_REVIEWER_BID_BI',
     'TRG_REVIEW_DISCUSSION_MESSAGE_BI',
     'TRG_CAMERA_READY_SUBMISSION_BIU',
     'TRG_COMMUNICATION_LOG_BI',
     'TRG_MANUSCRIPT_BI',
     'TRG_MANUSCRIPT_VERSION_BI',
     'TRG_MANUSCRIPT_AUTHOR_BI',
     'TRG_REVIEW_ROUND_BI',
     'TRG_ASSIGNMENT_DRAFT_BI',
     'TRG_REVIEW_ASSIGNMENT_BI',
     'TRG_CONFLICT_CHECK_RECORD_BI',
     'TRG_REVIEW_REPORT_BI',
     'TRG_DECISION_RECORD_BI',
     'TRG_ANALYSIS_INTENT_BI',
     'TRG_ANALYSIS_PROJECTION_BI',
     'TRG_ANALYSIS_PROJECTION_BU',
     'TRG_ANALYSIS_OUTBOX_BI',
     'TRG_ANALYSIS_INBOX_BI',
     'TRG_EXECUTION_ATTEMPT_BI',
     'TRG_EXECUTION_ARTIFACT_BI',
     'TRG_EXECUTION_OUTBOX_BI',
     'TRG_EXECUTION_INBOX_BI',
     'TRG_EXECUTION_JOB_BU',
     'TRG_SYS_NOTIFICATION_BI',
     'TRG_AUDIT_LOG_BIU',
     'TRG_MANUSCRIPT_AUDIT_TRACE_AU',
     'TRG_CONFERENCE_FORM_DEFINITION_BIU',
     'TRG_CONFERENCE_FORM_FIELD_BI',
     'TRG_REVIEW_FORM_RESPONSE_BIU',
     'TRG_AUTHOR_FEEDBACK_BIU',
     'TRG_PAPER_TAG_BIU',
     'TRG_IMPORT_BATCH_BI',
     'TRG_PAPER_ROLE_ASSIGNMENT_BI',
     'TRG_REVIEWER_INVITATION_BI',
     'TRG_EXTERNAL_DELEGATION_BI',
     'TRG_CONFLICT_RELATIONSHIP_BI',
     'TRG_REVIEWER_MATCHING_SCORE_BI',
     'TRG_ASSIGNMENT_PROPOSAL_BUNDLE_BI',
     'TRG_ASSIGNMENT_PROPOSAL_BI',
     'TRG_ASSIGNMENT_OVERRIDE_AUDIT_BI',
     'TRG_EMAIL_TEMPLATE_BI',
     'TRG_EMAIL_TEMPLATE_VERSION_BI',
     'TRG_OUTBOUND_EMAIL_HISTORY_BI',
     'TRG_OFFLINE_REVIEW_BATCH_BI',
     'TRG_OFFLINE_REVIEW_ROW_BI',
     'TRG_CAMERA_READY_FILE_BI',
     'TRG_PUBLICATION_METADATA_BI',
     'TRG_PROCEEDINGS_EXPORT_BATCH_BI',
     'TRG_WORKFLOW_FORM_RESPONSE_BIU',
     'TRG_REVIEW_FORM_RESPONSE_REV_BI'
   );

  SELECT COUNT(*)
    INTO v_index_count
    FROM USER_INDEXES
   WHERE INDEX_NAME IN (
     'IDX_SYS_USER_STATUS',
     'IDX_SYS_USER_ROLE_ROLE',
     'IDX_ROLE_APPLICATION_STATUS_TYPE',
     'IDX_EMAIL_VERIFICATION_USER_APP',
     'IDX_EMAIL_VERIFICATION_EXPIRES',
     'IDX_EMAIL_VERIFICATION_USER_PURPOSE',
     'IDX_CONFERENCE_PUBLIC_STATUS',
     'IDX_CONFERENCE_ORGANIZER_STATUS',
     'IDX_CONFERENCE_PHASE_SUBMISSION_CLOSE',
     'IDX_CONFERENCE_PHASE_BIDDING_CLOSE',
     'IDX_CONFERENCE_REVIEWER_CONF_STATUS',
     'IDX_CONFERENCE_REVIEWER_REVIEWER',
     'IDX_REVIEWER_BID_REVIEWER_CONF',
     'IDX_REVIEWER_BID_MANUSCRIPT',
     'IDX_REVIEW_DISCUSSION_ROUND',
     'IDX_REVIEW_DISCUSSION_ASSIGNMENT',
     'IDX_CAMERA_READY_MANUSCRIPT',
     'IDX_CAMERA_READY_STATUS',
     'IDX_COMMUNICATION_LOG_CONFERENCE',
     'IDX_COMMUNICATION_LOG_RECIPIENT',
     'IDX_MANUSCRIPT_CONFERENCE_STATUS',
     'IDX_MANUSCRIPT_SUBMITTER',
     'IDX_MANUSCRIPT_STATUS',
     'IDX_MANUSCRIPT_VERSION_SUBMITTED_BY',
     'IDX_REVIEW_ROUND_VERSION',
     'IDX_ASSIGNMENT_DRAFT_ROUND_STATUS',
     'IDX_ASSIGNMENT_DRAFT_REVIEWER',
     'IDX_ASSIGNMENT_DRAFT_MANUSCRIPT',
     'IDX_REVIEW_ASSIGNMENT_REVIEWER_STATUS',
     'IDX_CONFLICT_CHECK_ASSIGNMENT',
     'IDX_REVIEW_REPORT_MANUSCRIPT',
     'IDX_REVIEW_REPORT_REVIEWER',
     'IDX_DECISION_RECORD_MANUSCRIPT',
     'IDX_SYS_NOTIFICATION_RECEIVER_READ',
     'IDX_AUDIT_LOG_OPERATOR_CREATED',
     'IDX_ANALYSIS_INTENT_REQUESTED_BY_STATUS',
     'IDX_ANALYSIS_INTENT_ANCHOR_LOOKUP',
     'IDX_ANALYSIS_PROJECTION_STATUS_UPDATED',
     'IDX_ANALYSIS_OUTBOX_INTENT',
     'IDX_ANALYSIS_OUTBOX_STATUS_CREATED',
     'IDX_ANALYSIS_INBOX_INTENT',
     'IDX_ANALYSIS_INBOX_STATUS_RECEIVED',
     'IDX_EXECUTION_JOB_STATE_UPDATED',
     'IDX_EXECUTION_JOB_ERROR_UPDATED',
     'IDX_EXECUTION_JOB_ATTEMPT_AT',
     'IDX_EXECUTION_ATTEMPT_JOB',
     'IDX_EXECUTION_ARTIFACT_JOB',
     'IDX_EXECUTION_OUTBOX_JOB',
     'IDX_EXECUTION_OUTBOX_STATUS_CREATED',
     'IDX_EXECUTION_INBOX_JOB',
     'IDX_EXECUTION_INBOX_STATUS_RECEIVED',
     'IDX_REVIEW_ROUND_STATUS_ID',
     'IDX_REVIEW_ASSIGNMENT_ROUND_ID',
     'IDX_REVIEW_ASSIGNMENT_ACCESS',
     'IDX_REVIEW_REPORT_ROUND',
     'IDX_CONFLICT_CHECK_MANUSCRIPT_REVIEWER',
     'IDX_MANUSCRIPT_STATUS_SUBMITTED',
     'IDX_ANALYSIS_PROJECTION_UPDATED',
     'IDX_CONF_FORM_DEFINITION',
     'IDX_CONF_FORM_FIELD',
     'IDX_REVIEW_FORM_RESPONSE_ASSIGN',
     'IDX_AUTHOR_FEEDBACK_MANUSCRIPT',
     'IDX_PAPER_TAG_LOOKUP',
     'IDX_IMPORT_BATCH_CONFERENCE',
     'IDX_IMPORT_BATCH_TYPE_STATUS',
     'IDX_PAPER_ROLE_ASSIGNMENT_USER',
     'IDX_PAPER_ROLE_ASSIGNMENT_MANUSCRIPT',
     'IDX_PAPER_TAG_VALUE',
     'IDX_REVIEWER_INVITATION_STATUS',
     'IDX_EXTERNAL_DELEGATION_ASSIGN',
     'IDX_CONFLICT_REL_SUBJECT',
     'IDX_CONFLICT_REL_OBJECT',
     'IDX_REVIEWER_MATCHING_LOOKUP',
     'IDX_ASSIGNMENT_PROPOSAL_BUNDLE',
     'IDX_ASSIGNMENT_PROPOSAL_CANDIDATE',
     'IDX_ASSIGNMENT_OVERRIDE_BUNDLE',
     'IDX_EMAIL_TEMPLATE_KEY',
     'IDX_EMAIL_TEMPLATE_VERSION',
     'IDX_OUTBOUND_EMAIL_STATUS',
     'IDX_OFFLINE_REVIEW_BATCH',
     'IDX_OFFLINE_REVIEW_ROW',
     'IDX_CAMERA_READY_FILE_STATUS',
     'IDX_PUBLICATION_METADATA_STATUS',
     'IDX_PROCEEDINGS_EXPORT_STATUS',
     'IDX_WORKFLOW_FORM_RESPONSE_SUBJ',
     'IDX_CONFERENCE_PHASE_REBUTTAL',
     'IDX_CONFERENCE_PHASE_CAMERA_READY'
   );

  SELECT COUNT(*)
    INTO v_procedure_count
    FROM USER_OBJECTS
   WHERE OBJECT_TYPE = 'PROCEDURE'
     AND OBJECT_NAME IN (
       'PRC_REVIEW_COMPLETION_STATS',
       'PRC_REVIEW_WORKLOAD_SUMMARY'
     );

  SELECT COUNT(*)
    INTO v_invalid_count
    FROM USER_OBJECTS
   WHERE OBJECT_TYPE IN ('TRIGGER', 'PROCEDURE')
     AND OBJECT_NAME IN (
       'TRG_SYS_USER_BI',
       'TRG_SYS_ROLE_BI',
       'TRG_SYS_USER_ROLE_BI',
       'TRG_USER_RESEARCH_AREA_BI',
       'TRG_USER_ACADEMIC_PROFILE_BI',
       'TRG_ROLE_APPLICATION_BI',
       'TRG_EMAIL_VERIFICATION_TOKEN_BI',
       'TRG_CONFERENCE_BI',
       'TRG_CONFERENCE_PHASE_BI',
       'TRG_CONFERENCE_REVIEWER_BI',
       'TRG_REVIEWER_BID_BI',
       'TRG_REVIEW_DISCUSSION_MESSAGE_BI',
       'TRG_CAMERA_READY_SUBMISSION_BIU',
       'TRG_COMMUNICATION_LOG_BI',
       'TRG_MANUSCRIPT_BI',
       'TRG_MANUSCRIPT_VERSION_BI',
       'TRG_MANUSCRIPT_AUTHOR_BI',
       'TRG_REVIEW_ROUND_BI',
       'TRG_ASSIGNMENT_DRAFT_BI',
       'TRG_REVIEW_ASSIGNMENT_BI',
       'TRG_CONFLICT_CHECK_RECORD_BI',
       'TRG_REVIEW_REPORT_BI',
       'TRG_DECISION_RECORD_BI',
       'TRG_ANALYSIS_INTENT_BI',
       'TRG_ANALYSIS_PROJECTION_BI',
       'TRG_ANALYSIS_PROJECTION_BU',
       'TRG_ANALYSIS_OUTBOX_BI',
       'TRG_ANALYSIS_INBOX_BI',
       'TRG_EXECUTION_ATTEMPT_BI',
       'TRG_EXECUTION_ARTIFACT_BI',
       'TRG_EXECUTION_OUTBOX_BI',
       'TRG_EXECUTION_INBOX_BI',
       'TRG_EXECUTION_JOB_BU',
       'TRG_SYS_NOTIFICATION_BI',
       'TRG_AUDIT_LOG_BIU',
       'TRG_MANUSCRIPT_AUDIT_TRACE_AU',
       'TRG_CONFERENCE_FORM_DEFINITION_BIU',
       'TRG_CONFERENCE_FORM_FIELD_BI',
       'TRG_REVIEW_FORM_RESPONSE_BIU',
       'TRG_AUTHOR_FEEDBACK_BIU',
       'TRG_PAPER_TAG_BIU',
       'TRG_IMPORT_BATCH_BI',
       'TRG_PAPER_ROLE_ASSIGNMENT_BI',
       'TRG_REVIEWER_INVITATION_BI',
       'TRG_EXTERNAL_DELEGATION_BI',
       'TRG_CONFLICT_RELATIONSHIP_BI',
       'TRG_REVIEWER_MATCHING_SCORE_BI',
       'TRG_ASSIGNMENT_PROPOSAL_BUNDLE_BI',
       'TRG_ASSIGNMENT_PROPOSAL_BI',
       'TRG_ASSIGNMENT_OVERRIDE_AUDIT_BI',
       'TRG_EMAIL_TEMPLATE_BI',
       'TRG_EMAIL_TEMPLATE_VERSION_BI',
       'TRG_OUTBOUND_EMAIL_HISTORY_BI',
       'TRG_OFFLINE_REVIEW_BATCH_BI',
       'TRG_OFFLINE_REVIEW_ROW_BI',
       'TRG_CAMERA_READY_FILE_BI',
       'TRG_PUBLICATION_METADATA_BI',
       'TRG_PROCEEDINGS_EXPORT_BATCH_BI',
       'TRG_WORKFLOW_FORM_RESPONSE_BIU',
       'TRG_REVIEW_FORM_RESPONSE_REV_BI',
       'PRC_REVIEW_COMPLETION_STATS',
       'PRC_REVIEW_WORKLOAD_SUMMARY'
     )
     AND STATUS <> 'VALID';

  SELECT COUNT(*)
    INTO v_error_count
    FROM USER_ERRORS
   WHERE NAME IN (
     'TRG_SYS_USER_BI',
     'TRG_SYS_ROLE_BI',
     'TRG_SYS_USER_ROLE_BI',
     'TRG_USER_RESEARCH_AREA_BI',
     'TRG_USER_ACADEMIC_PROFILE_BI',
     'TRG_ROLE_APPLICATION_BI',
     'TRG_EMAIL_VERIFICATION_TOKEN_BI',
     'TRG_CONFERENCE_BI',
     'TRG_CONFERENCE_PHASE_BI',
     'TRG_CONFERENCE_REVIEWER_BI',
     'TRG_REVIEWER_BID_BI',
     'TRG_REVIEW_DISCUSSION_MESSAGE_BI',
     'TRG_CAMERA_READY_SUBMISSION_BIU',
     'TRG_COMMUNICATION_LOG_BI',
     'TRG_MANUSCRIPT_BI',
     'TRG_MANUSCRIPT_VERSION_BI',
     'TRG_MANUSCRIPT_AUTHOR_BI',
     'TRG_REVIEW_ROUND_BI',
     'TRG_ASSIGNMENT_DRAFT_BI',
     'TRG_REVIEW_ASSIGNMENT_BI',
     'TRG_CONFLICT_CHECK_RECORD_BI',
     'TRG_REVIEW_REPORT_BI',
     'TRG_DECISION_RECORD_BI',
     'TRG_ANALYSIS_INTENT_BI',
     'TRG_ANALYSIS_PROJECTION_BI',
     'TRG_ANALYSIS_PROJECTION_BU',
     'TRG_ANALYSIS_OUTBOX_BI',
     'TRG_ANALYSIS_INBOX_BI',
     'TRG_EXECUTION_ATTEMPT_BI',
     'TRG_EXECUTION_ARTIFACT_BI',
     'TRG_EXECUTION_OUTBOX_BI',
     'TRG_EXECUTION_INBOX_BI',
     'TRG_EXECUTION_JOB_BU',
     'TRG_SYS_NOTIFICATION_BI',
     'TRG_AUDIT_LOG_BIU',
     'TRG_MANUSCRIPT_AUDIT_TRACE_AU',
     'TRG_CONFERENCE_FORM_DEFINITION_BIU',
     'TRG_CONFERENCE_FORM_FIELD_BI',
     'TRG_REVIEW_FORM_RESPONSE_BIU',
     'TRG_AUTHOR_FEEDBACK_BIU',
     'TRG_PAPER_TAG_BIU',
     'TRG_IMPORT_BATCH_BI',
     'TRG_PAPER_ROLE_ASSIGNMENT_BI',
     'TRG_REVIEWER_INVITATION_BI',
     'TRG_EXTERNAL_DELEGATION_BI',
     'TRG_CONFLICT_RELATIONSHIP_BI',
     'TRG_REVIEWER_MATCHING_SCORE_BI',
     'TRG_ASSIGNMENT_PROPOSAL_BUNDLE_BI',
     'TRG_ASSIGNMENT_PROPOSAL_BI',
     'TRG_ASSIGNMENT_OVERRIDE_AUDIT_BI',
     'TRG_EMAIL_TEMPLATE_BI',
     'TRG_EMAIL_TEMPLATE_VERSION_BI',
     'TRG_OUTBOUND_EMAIL_HISTORY_BI',
     'TRG_OFFLINE_REVIEW_BATCH_BI',
     'TRG_OFFLINE_REVIEW_ROW_BI',
     'TRG_CAMERA_READY_FILE_BI',
     'TRG_PUBLICATION_METADATA_BI',
     'TRG_PROCEEDINGS_EXPORT_BATCH_BI',
     'TRG_WORKFLOW_FORM_RESPONSE_BIU',
     'TRG_REVIEW_FORM_RESPONSE_REV_BI',
     'PRC_REVIEW_COMPLETION_STATS',
     'PRC_REVIEW_WORKLOAD_SUMMARY'
   );

  SELECT COUNT(*)
    INTO v_wave8_wave9_slice_b_constraint
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'CK_IMPORT_BATCH_TYPE'
     AND SEARCH_CONDITION_VC LIKE '%MATCHING_SCORES%';

  SELECT COUNT(*)
    INTO v_role_count
    FROM SYS_ROLE;

  SELECT COUNT(*)
    INTO v_execution_job_attempt_count_column
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EXECUTION_JOB'
     AND COLUMN_NAME = 'ATTEMPT_COUNT';

  SELECT COUNT(*)
    INTO v_execution_job_governance_columns
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'EXECUTION_JOB'
     AND COLUMN_NAME IN (
       'LAST_ERROR_CATEGORY',
       'LAST_ATTEMPT_AT',
       'COMPLETED_AT'
     );

  SELECT COUNT(*)
    INTO v_manuscript_conference_column
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'MANUSCRIPT'
     AND COLUMN_NAME = 'CONFERENCE_ID';

  SELECT COUNT(*)
    INTO v_manuscript_conference_fk
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'MANUSCRIPT'
     AND CONSTRAINT_NAME = 'FK_MANUSCRIPT_CONFERENCE'
     AND CONSTRAINT_TYPE = 'R';

  SELECT COUNT(*)
    INTO v_assignment_assist_type_constraints
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME IN (
       'CK_ANALYSIS_INTENT_TYPE',
       'CK_ANALYSIS_PROJECTION_TYPE',
       'CK_EXECUTION_JOB_TYPE'
     )
     AND SEARCH_CONDITION_VC LIKE '%REVIEWER_ASSIGNMENT_ASSIST%';

  SELECT COUNT(*)
    INTO v_business_operations_tables
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'REVIEW_DISCUSSION_MESSAGE',
     'CAMERA_READY_SUBMISSION',
     'COMMUNICATION_LOG'
   );

  SELECT COUNT(*)
    INTO v_real_platform_wave6_wave7_tables
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'CONFERENCE_FORM_DEFINITION',
     'CONFERENCE_FORM_FIELD',
     'REVIEW_FORM_RESPONSE',
     'AUTHOR_FEEDBACK',
     'PAPER_TAG',
     'IMPORT_BATCH',
     'PAPER_ROLE_ASSIGNMENT'
   );

  SELECT COUNT(*)
    INTO v_assignment_coi_maturity_tables
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'REVIEWER_INVITATION',
     'EXTERNAL_REVIEWER_DELEGATION',
     'CONFLICT_RELATIONSHIP',
     'REVIEWER_MATCHING_SCORE',
     'ASSIGNMENT_PROPOSAL_BUNDLE',
     'ASSIGNMENT_PROPOSAL',
     'ASSIGNMENT_OVERRIDE_AUDIT'
   );

  SELECT COUNT(*)
    INTO v_publication_communication_maturity_tables
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'EMAIL_TEMPLATE',
     'EMAIL_TEMPLATE_VERSION',
     'OUTBOUND_EMAIL_HISTORY',
     'OFFLINE_REVIEW_IMPORT_BATCH',
     'OFFLINE_REVIEW_IMPORT_ROW',
     'CAMERA_READY_FILE',
     'PUBLICATION_METADATA',
     'PROCEEDINGS_EXPORT_BATCH'
   );

  SELECT COUNT(*)
    INTO v_wave3_wave6_full_closure_objects
    FROM (
      SELECT TABLE_NAME AS OBJECT_NAME
      FROM USER_TABLES
      WHERE TABLE_NAME IN ('WORKFLOW_FORM_RESPONSE', 'REVIEW_FORM_RESPONSE_REVISION')
      UNION ALL
      SELECT SEQUENCE_NAME AS OBJECT_NAME
      FROM USER_SEQUENCES
      WHERE SEQUENCE_NAME IN ('SEQ_WORKFLOW_FORM_RESPONSE', 'SEQ_REVIEW_FORM_RESPONSE_REV')
      UNION ALL
      SELECT TRIGGER_NAME AS OBJECT_NAME
      FROM USER_TRIGGERS
      WHERE TRIGGER_NAME IN ('TRG_WORKFLOW_FORM_RESPONSE_BIU', 'TRG_REVIEW_FORM_RESPONSE_REV_BI')
      UNION ALL
      SELECT COLUMN_NAME AS OBJECT_NAME
      FROM USER_TAB_COLUMNS
      WHERE TABLE_NAME = 'CONFERENCE_PHASE'
        AND COLUMN_NAME IN ('REBUTTAL_OPEN_AT', 'REBUTTAL_CLOSE_AT', 'CAMERA_READY_OPEN_AT', 'CAMERA_READY_CLOSE_AT')
    );

  IF v_table_count <> 58 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Expected 58 tables, found ' || v_table_count);
  END IF;

  IF v_sequence_count <> 57 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Expected 57 sequences, found ' || v_sequence_count);
  END IF;

  IF v_trigger_count <> 60 THEN
    RAISE_APPLICATION_ERROR(-20003, 'Expected 60 triggers, found ' || v_trigger_count);
  END IF;

  IF v_procedure_count <> 2 THEN
    RAISE_APPLICATION_ERROR(-20004, 'Expected 2 procedures, found ' || v_procedure_count);
  END IF;

  IF v_index_count <> 87 THEN
    RAISE_APPLICATION_ERROR(-20005, 'Expected 87 indexes, found ' || v_index_count);
  END IF;

  IF v_wave8_wave9_slice_b_constraint <> 1 THEN
    RAISE_APPLICATION_ERROR(-20023, 'Wave8/Wave9 SliceB import constraint is missing');
  END IF;

  IF v_wave3_wave6_full_closure_objects <> 10 THEN
    RAISE_APPLICATION_ERROR(-20024, 'Wave3/Wave6 full closure schema objects are missing');
  END IF;

  IF v_role_count <> 4 THEN
    RAISE_APPLICATION_ERROR(-20006, 'Expected 4 role seeds, found ' || v_role_count);
  END IF;

  IF v_execution_job_attempt_count_column <> 1 THEN
    RAISE_APPLICATION_ERROR(-20009, 'Expected EXECUTION_JOB.ATTEMPT_COUNT column to exist');
  END IF;

  IF v_execution_job_governance_columns <> 3 THEN
    RAISE_APPLICATION_ERROR(-20013, 'Expected EXECUTION_JOB governance columns to exist');
  END IF;

  IF v_manuscript_conference_column <> 1 THEN
    RAISE_APPLICATION_ERROR(-20010, 'Expected MANUSCRIPT.CONFERENCE_ID column to exist');
  END IF;

  IF v_manuscript_conference_fk <> 1 THEN
    RAISE_APPLICATION_ERROR(-20011, 'Expected FK_MANUSCRIPT_CONFERENCE constraint to exist');
  END IF;

  IF v_assignment_assist_type_constraints <> 3 THEN
    RAISE_APPLICATION_ERROR(-20012, 'Expected reviewer assignment assist analysis type constraints to exist');
  END IF;

  IF v_business_operations_tables <> 3 THEN
    RAISE_APPLICATION_ERROR(-20014, 'Expected business operations closure tables to exist');
  END IF;

  IF v_real_platform_wave6_wave7_tables <> 7 THEN
    RAISE_APPLICATION_ERROR(-20015, 'Expected real-platform Wave6/Wave7 tables to exist');
  END IF;

  IF v_assignment_coi_maturity_tables <> 7 THEN
    RAISE_APPLICATION_ERROR(-20016, 'Expected assignment/COI maturity tables to exist');
  END IF;

  IF v_publication_communication_maturity_tables <> 8 THEN
    RAISE_APPLICATION_ERROR(-20017, 'Expected publication/communication maturity tables to exist');
  END IF;

  IF v_invalid_count <> 0 THEN
    RAISE_APPLICATION_ERROR(-20007, 'Expected all verified triggers/procedures to be VALID, found ' || v_invalid_count || ' invalid object(s)');
  END IF;

  IF v_error_count <> 0 THEN
    RAISE_APPLICATION_ERROR(-20008, 'Expected no USER_ERRORS rows for verified objects, found ' || v_error_count);
  END IF;

  DBMS_OUTPUT.PUT_LINE('Schema verification passed.');
END;
/
